import test from 'node:test';import assert from 'node:assert/strict';
import {createSimulation} from '../src/core/sim.js';
import {createSg02DynamicBodyOwner} from '../src/core/sg02DynamicBodyOwner.js';
import {makeBudgetApi} from '../src/systems/spawnBudget.js';
import {createLatchNineRuntime} from '../src/systems/latchNine.js';
import {latchNinePresenceForAsset} from '../src/data/latchNine.js';
import {isLatchActor} from '../src/data/latchNineIdentity.js';
import {latchServicePlacement} from '../src/systems/latchNineTender.js';
import {SECTOR_ANCHORS} from '../src/data/sectorAnchors.js';
import {sectorLocalToGlobalForSector} from '../src/data/sectorCoordinates.js';
import {createDockIntent} from '../src/core/dockIntent.js';
import {commitDockedUiState} from '../src/ui/dockStateCommit.js';
import {resolveDockAnchor,resolveCollisionProxyManifest,corridorStateFor} from '../src/data/collisionProxyManifests.js';
import {readLatchNative} from '../src/core/latchNineNative.js';
import {entityHasDurableMarkers,captureEntityRecord} from '../src/world/worldRecords.js';
import {machineryHasEffectivePresentation,bindMachineryPresentation,recordLatchAuthoredSource} from '../src/core/machineryPresentation.js';
const SECTOR='sector_tethys_junction';
async function fixture(){
 const sim=createSimulation({seed:909,systems:[]}),state=sim.state;state.mode='flight';state.world.currentSectorId=SECTOR;state.world.enterSerial=1;state.ui={docked:false};state.factions={};
 const anchor=SECTOR_ANCHORS[SECTOR].stations.find(x=>x.id==='station_tethys'),pos=sectorLocalToGlobalForSector(anchor.pos,SECTOR);
 const station=sim.spawn({type:'station',pos,vel:{x:0,z:0},radius:90,collides:true,physicsBody:{dynamic:false,mass:1e8,shape:'ball',radius:90},data:{stationId:'station_tethys',dockRadius:90,archetypeGlb:anchor.archetypeGlb,collisionProxy:'helios_trade_hub'}});
 const player=sim.spawn({type:'ship',isPlayer:true,hull:100,hullMax:100,mass:10,radius:2,pos:{x:pos.x+250,z:pos.z+180},vel:{x:0,z:0},rot:0,angVel:0,physicsBody:{dynamic:true,mass:10,inertiaY:20,radius:2,shape:'ball'}});state.playerId=player.id;
 const helpers={...sim.helpers,spawnBudget:makeBudgetApi(state),voice:{say:()=>true}};
 const runtime=createLatchNineRuntime({promoted:()=>true,presenceResolver:s=>{const p=latchNinePresenceForAsset(s,{id:'place_latch_nine',source:'glb',status:'green'});return p&&readLatchNative(p.tender)&&machineryHasEffectivePresentation(p.tender,s)?p:null;}});runtime.init({state,bus:sim.bus,helpers});
 const owner=await createSg02DynamicBodyOwner({frameOrigin:pos});owner.syncFromEntities(state.entityList);owner.step(1/60);runtime.update(1/60);
 return {sim,state,station,player,helpers,runtime,owner,actor(){return state.entityList.find(e=>e.alive&&isLatchActor(e));},close(){runtime.destroy();owner.dispose();sim.dispose();}};
}
test('normal materializer creates one source-origin physical actor and binds one exact spawn-budget slot',async()=>{const h=await fixture();try{const e=h.actor();assert(e);assert.equal(h.helpers.spawnBudget.current(),1);assert.equal(h.state.entityList.filter(isLatchActor).length,1);assert(readLatchNative(e));assert(machineryHasEffectivePresentation(e,h.state));const p=latchServicePlacement(h.station);assert.deepEqual(e.data.latchNineService.box,p.box);assert(Math.hypot(e.pos.x-h.station.pos.x,e.pos.z-h.station.pos.z)>p.stationBound+40);for(let i=0;i<4;i++)h.runtime.update(1/60);assert.equal(h.actor(),e);assert.equal(h.helpers.spawnBudget.current(),1);assert.equal(entityHasDurableMarkers(e,h.player.id),false);assert.equal(captureEntityRecord(e,{sectorId:SECTOR}),null);}finally{h.close();}});
test('ordinary approach guidance does not manufacture clearance; actual berth commit acknowledges once and return can acknowledge again',async()=>{const h=await fixture();try{assert.equal(h.state.latchNine.phase,'APPROACH');assert.equal(h.state.latchNine.dockReady,false);assert(h.state.latchNine.guidance);const anchor=resolveDockAnchor(h.station,resolveCollisionProxyManifest(h.station),h.player);assert(anchor);h.player.pos.x=anchor.x;h.player.pos.z=anchor.z;h.player.vel.x=h.player.vel.z=0;h.runtime.update(1/60);assert.equal(h.state.latchNine.phase,'GUIDE');const receipt=createDockIntent(h.state,{stationId:'station_tethys'});assert(commitDockedUiState(h.state,receipt,h.sim.bus));assert.equal(h.state.latchNine.phase,'ACKNOWLEDGE');const saved=h.runtime.serialize();h.sim.bus.emit('dock:committed',receipt);assert.deepEqual(h.runtime.serialize(),saved);h.runtime.keepalive(4);assert.notEqual(h.state.latchNine.phase,'ACKNOWLEDGE');h.state.ui.docked=false;h.state.ui.dockedStationId=null;h.runtime.update(1/60);assert.equal(h.state.latchNine.phase,'GUIDE');assert(commitDockedUiState(h.state,createDockIntent(h.state,{stationId:'station_tethys'}),h.sim.bus));assert.equal(h.state.latchNine.phase,'ACKNOWLEDGE');}finally{h.close();}});
test('sector exit releases the exact actor and slot; return rematerializes a fresh native life',async()=>{const h=await fixture();try{const old=h.actor();h.sim.bus.emit('sector:exit',{sectorId:SECTOR});assert(!h.actor()||!h.actor().alive);assert.equal(h.helpers.spawnBudget.current(),0);h.state.world.enterSerial++;h.sim.bus.emit('sector:enter',{sectorId:SECTOR,enterEpoch:h.state.world.enterSerial});h.runtime.update(1/60);const fresh=h.actor();assert(fresh&&fresh!==old);h.owner.syncFromEntities(h.state.entityList);h.owner.step(1/60);assert(readLatchNative(fresh));assert.equal(readLatchNative(old),null);assert.equal(h.helpers.spawnBudget.current(),1);}finally{h.close();}});
test('cold semantic restore removes the old runtime body, restores only four fields and does not replay acknowledgement',async()=>{const h=await fixture();try{const old=h.actor();const saved={met:true,cleanArrivals:7,incidentIds:['law-1'],destroyed:false};h.state.ui.docked=true;h.state.ui.dockedStationId='station_tethys';h.runtime.deserialize({...saved,body:old,angles:[1,1,1],native:123});h.sim.bus.emit('save:loaded',{});h.owner.syncFromEntities(h.state.entityList);h.owner.step(1/60);h.runtime.keepalive(.1);assert.notEqual(h.actor(),old);assert.deepEqual(h.runtime.serialize(),saved);assert.notEqual(h.state.latchNine.phase,'ACKNOWLEDGE');assert.deepEqual(readLatchNative(h.actor()).angles,[0,0,0]);assert.equal(readLatchNative(old),null);}finally{h.close();}});
test('destroyed/disabled Latch leaves ordinary docking authority usable and does not respawn a destroyed body',async()=>{const h=await fixture();try{const e=h.actor();e.hull=0;e.alive=false;h.sim.bus.emit('entity:killed',{id:e.id});h.runtime.update(1/60);assert.equal(h.runtime.serialize().destroyed,true);assert.equal(h.state.latchNine.phase,'OFF_DUTY');h.runtime.update(1/60);assert.equal(h.state.entityList.filter(x=>isLatchActor(x)&&x.alive).length,0);const anchor=resolveDockAnchor(h.station,resolveCollisionProxyManifest(h.station),h.player);h.player.pos.x=anchor.x;h.player.pos.z=anchor.z;assert(commitDockedUiState(h.state,createDockIntent(h.state,{stationId:'station_tethys'}),h.sim.bus));assert.equal(h.state.ui.dockedStationId,'station_tethys');}finally{h.close();}});
test('native-observed clean docking recognizes once; stale or replayed commits cannot add arrivals',async()=>{const h=await fixture();try{
 const anchor=resolveDockAnchor(h.station,resolveCollisionProxyManifest(h.station),h.player);h.player.pos.x=anchor.x;h.player.pos.z=anchor.z;h.player.flags.noInterp=true;
 for(let i=0;i<3;i++){h.owner.syncFromEntities(h.state.entityList);h.owner.step(1/60);h.state.simTime+=1/60;h.runtime.update(1/60);}
 assert.equal(h.state.latchNine.phase,'GUIDE');const receipt=createDockIntent(h.state,{stationId:'station_tethys'});assert(commitDockedUiState(h.state,receipt,h.sim.bus));assert.equal(h.runtime.serialize().cleanArrivals,1);h.sim.bus.emit('dock:committed',receipt);assert.equal(h.runtime.serialize().cleanArrivals,1);
 const saved=h.runtime.serialize();h.runtime.deserialize(saved);h.sim.bus.emit('save:loaded',{});h.runtime.keepalive(.1);h.sim.bus.emit('dock:committed',receipt);assert.deepEqual(h.runtime.serialize(),saved);
 }finally{h.close();}});
test('only same-life law-owner player incidents enter the bounded idempotent memory',async()=>{const h=await fixture();try{
 const incident={id:'law:verified-latch-test',stationId:'station_tethys',stationEntityId:h.station.id,stationGeneration:h.station.occupantGeneration,attackerId:h.player.id,attackerGeneration:h.player.occupantGeneration};h.state.lawSecurity={incidents:{one:incident}};
 h.sim.bus.emit('law:incidentOpened',{id:incident.id});h.sim.bus.emit('law:incidentOpened',{id:incident.id});assert.deepEqual(h.runtime.serialize().incidentIds,[incident.id]);
 h.state.lawSecurity.incidents.npc={...incident,id:'law:npc',attackerId:999};h.sim.bus.emit('law:incidentOpened',{id:'law:npc'});h.state.lawSecurity.incidents.stale={...incident,id:'law:stale',attackerGeneration:incident.attackerGeneration+1};h.sim.bus.emit('law:incidentOpened',{id:'law:stale'});h.sim.bus.emit('law:incidentOpened',{id:'law:forged'});assert.deepEqual(h.runtime.serialize().incidentIds,[incident.id]);
 }finally{h.close();}});
test('browser source admission and scene detach fail physical colliders closed without borrowing ready strings',async()=>{const h=await fixture();try{
 const e=h.actor(),sourceBody=e.physicsBody,scene={};h.state.render={scene,renderer:{},admissionRunGeneration:1};e.presentationAdmission='ready';e.mesh={parent:scene,userData:{placeId:'place_latch_nine',authoredAssetState:'authored'}};
 h.runtime.update(1/60);assert.equal(e.physicsBody,false);assert.equal(e.collides,false);bindMachineryPresentation(e,e.mesh,h.state);h.runtime.update(1/60);assert.equal(e.physicsBody,false,'a bound ready string is not source provenance');
 assert(recordLatchAuthoredSource(e.mesh,{assetId:'SF_PLACE_LATCH_NINE',file:'assets/ships/release/parts/places/place_latch_nine.glb'}));h.runtime.update(1/60);assert.equal(e.physicsBody,sourceBody);assert.equal(e.collides,true);
 e.mesh.parent=null;h.runtime.update(1/60);assert.equal(e.physicsBody,false);assert.equal(e.collides,false);e.mesh.parent=scene;h.runtime.update(1/60);assert.equal(e.physicsBody,sourceBody);
 h.state.render.scene=null;h.runtime.update(1/60);assert.equal(e.physicsBody,false,'lost browser scene does not become permissive headless mode');
 }finally{h.close();}});

test('disabled owned death persists immediately and releases the exact budget on event',async()=>{const h=await fixture();try{const e=h.actor();e.data.disabled=true;h.runtime.update(1/60);e.hull=0;e.alive=false;h.sim.bus.emit('entity:killed',{id:e.id});assert.equal(h.runtime.serialize().destroyed,true);assert.equal(h.helpers.spawnBudget.current(),0);assert.equal(h.runtime._tenderOwner.entity,null);assert.equal(e.alive,false);h.sim.bus.emit('entity:killed',{id:e.id});assert.equal(h.runtime.serialize().destroyed,true);}finally{h.close();}});
test('matching foreign textual tags and death do not destroy the owned service',async()=>{const h=await fixture();try{const e=h.actor();e.data.disabled=true;h.runtime.update(1/60);const foreign=h.sim.spawn({type:'prop',hull:0,alive:false,data:{...e.data}});h.sim.bus.emit('entity:killed',{id:foreign.id});assert.equal(h.runtime.serialize().destroyed,false);assert.equal(h.runtime._tenderOwner.entity,e);}finally{h.close();}});
test('replacement under a recycled id cannot be consumed as the owned death',async()=>{const h=await fixture();try{const e=h.actor();e.data.disabled=true;h.runtime.update(1/60);const replacement={...e,occupantGeneration:e.occupantGeneration+1,hull:0,alive:false};h.state.entities.set(e.id,replacement);const i=h.state.entityList.indexOf(e);h.state.entityList[i]=replacement;h.sim.bus.emit('entity:killed',{id:e.id});assert.equal(h.runtime.serialize().destroyed,false);assert.equal(h.state.entities.get(e.id),replacement);}finally{h.close();}});
test('same object in a new generation cannot inherit the old owned death',async()=>{const h=await fixture();try{const e=h.actor();e.data.disabled=true;h.runtime.update(1/60);e.occupantGeneration++;e.hull=0;e.alive=false;h.sim.bus.emit('entity:killed',{id:e.id});assert.equal(h.runtime.serialize().destroyed,false);assert.equal(h.state.entities.get(e.id),e);}finally{h.close();}});
