import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createHash} from 'node:crypto';import * as THREE from 'three';
import{prepareRenderPackageBlueprint,assembleRenderPackageRecord}from'../src/render/assetLoader.js';import{loadMotionBank}from'../src/render/authoredMotion.js';
import{NodeIO}from'@gltf-transform/core';import{ALL_EXTENSIONS}from'@gltf-transform/extensions';import{dequantize}from'@gltf-transform/functions';import{MeshoptDecoder}from'meshoptimizer';
import{createSimulation}from'../src/core/sim.js';import{createSg02DynamicBodyOwner}from'../src/core/sg02DynamicBodyOwner.js';import{latchBodySpec,LATCH_RADIUS}from'../src/data/latchNineBody.js';import{bindLatchNative,readLatchNative,requestLatchPaddles}from'../src/core/latchNineNative.js';import{stepLatchPropulsion}from'../src/systems/latchNinePropulsion.js';
import{ContinuousPlumeSystem}from'../src/render/thruster/systems/continuousPlume.js';import{resolveThrusterRecipes}from'../src/render/thruster/recipes/registry.js';
import{createLatchNineVisualDriver,createLatchNinePlumeBatch}from'../src/render/latchNineVisuals.js';import{createRenderPackageLoader}from'../src/render/renderPackageLoader.js';import{computeRenderPackageContentHash,computeRenderPackageRuntimeHash}from'../src/contracts/renderPackage.js';
const hash=b=>createHash('sha256').update(b).digest('hex'),read=p=>JSON.parse(fs.readFileSync(p));
async function packageFixture(){
 const p=read('assets/ships/render-packages/pilots.json').pilots.find(p=>p.key==='latch-nine'),release=read('assets/ships/release/release_manifest.json').assets.find(r=>r.id==='place_latch_nine');assert(p);assert.equal(release.sourceSha256,hash(fs.readFileSync('assets/ships/parts/places/place_latch_nine.glb')));assert.equal(p.releaseSha256,hash(fs.readFileSync(release.release)));
 const m=read(p.metadataUrl);assert.equal(m.contentHash,await computeRenderPackageContentHash(m,{digest:hash}));assert.equal(m.runtimeHash,await computeRenderPackageRuntimeHash(m,{digest:hash}));assert.equal(m.render.sha256,hash(fs.readFileSync(`${p.outputDir}/render.glb`)));
 await MeshoptDecoder.ready;const io=new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.decoder':MeshoptDecoder}),d=await io.read(`${p.outputDir}/render.glb`);await d.transform(dequantize());
 // Decode actual compiled geometry and transforms; texture pixels/GPU are deliberately outside this CPU contract.
 const convert=n=>{const mesh=n.getMesh(),pr=mesh?.listPrimitives()[0],o=mesh?new THREE.Mesh(new THREE.BufferGeometry(),new THREE.MeshStandardMaterial({emissive:0xffffff,emissiveIntensity:pr.getMaterial()?.getExtension('KHR_materials_emissive_strength')?.getEmissiveStrength()||1})):new THREE.Group();o.name=n.getName();if(pr)o.material.name=pr.getMaterial()?.getName()||'';o.userData={...n.getExtras()};if(pr){const a=pr.getAttribute('POSITION');o.geometry.setAttribute('position',new THREE.BufferAttribute(a.getArray().slice(),a.getElementSize()));if(pr.getIndices())o.geometry.setIndex(new THREE.BufferAttribute(pr.getIndices().getArray().slice(),1));}o.position.fromArray(n.getTranslation());o.quaternion.fromArray(n.getRotation());o.scale.fromArray(n.getScale());for(const c of n.listChildren())o.add(convert(c));return o;};
 const scene=new THREE.Group();for(const n of d.getRoot().listScenes()[0].listChildren())scene.add(convert(n));const loader=createRenderPackageLoader({loadGlb:async()=>({scene,asset:d.getRoot().getAsset()}),prepareDecoded:async(decoded,metadata,url,plan)=>{const prepared=prepareRenderPackageBlueprint(p,decoded,metadata,{plan});const motionBank=await loadMotionBank(metadata.runtime.motionBank,async uri=>{const b=fs.readFileSync(uri);return{ok:true,arrayBuffer:async()=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)};});return{...prepared,motionBank};}}),loaded=await loader.load(m,{expectedContentHash:m.contentHash,expectedRuntimeHash:m.runtimeHash});return{loader,loaded,record:assembleRenderPackageRecord(loaded,p.sourceUrl,p.assetId)};
}
test('canonical compiled Latch package presents only exact consumed native actuation and withdraws on scene loss',async()=>{
 const pkg=await packageFixture(),instance=pkg.loaded.createInstance(),other=pkg.loaded.createInstance();assert.notEqual(instance.root,other.root);
 const sim=createSimulation({seed:9,systems:[]}),s=sim.state;s.mode='flight';s.world.currentSectorId='sector_tethys_junction';s.render={scene:new THREE.Scene()};
 const e=sim.spawn({type:'prop',hull:100,mass:140,radius:LATCH_RADIUS,pos:{x:0,z:0},vel:{x:0,z:0},rot:0,angVel:0,collides:true,physicsBody:latchBodySpec(),data:{role:'latch_nine',placeId:'place_latch_nine',latchNineService:{stationId:'station_tethys',sectorId:'sector_tethys_junction',box:{minX:19,maxX:21,minZ:-1,maxZ:1}}}});e.mesh=new THREE.Group();e.mesh.add(instance.root);s.render.scene.add(e.mesh);instance.root.userData.latchNineAuthoredSource={assetId:'SF_PLACE_LATCH_NINE',file:'places/place_latch_nine.glb'};
 const owner=await createSg02DynamicBodyOwner({mode:'rapier-dynamic'});owner.syncFromEntities(s.entityList);assert(bindLatchNative(owner,owner.records.get(e.id)));let driver,batch;
 try{driver=createLatchNineVisualDriver(instance.root,e);assert(driver);assert(driver.activate(e));assert.equal(driver.binding.samples.length,8);assert(driver.binding.samples.every(t=>t.meshes.length===3));requestLatchPaddles(e,[.1,.1,.1]);let lit=0;
 for(let tick=0;tick<10;tick++){owner.step(1/60);stepLatchPropulsion(s,e,1/60);s.render.scene.updateMatrixWorld(true);driver.update(e,{});if(driver.binding.samples.some(t=>t.level>0))lit++;}assert.equal(lit,9);const plume=new ContinuousPlumeSystem(THREE,resolveThrusterRecipes('engine_industrial').main,{maxSockets:8,distortionEnabled:false});s.render.scene.add(plume.group);plume.bindDynamicBuffers(s.render.scene);batch=createLatchNinePlumeBatch(plume,THREE.Vector3);assert(batch.update(s,1/60,{})>0);assert(plume.pool.activeCount>0);assert.equal(plume.pool.frameAllocations,0);assert(plume.layerBatches.length<=5);assert(plume.layerBatches.every(b=>b.mesh.isInstancedMesh));e.mesh.visible=false;driver.update(e,{});assert.equal(batch.update(s,1/60,{}),0);assert.equal(plume.pool.activeCount,0);assert(driver.binding.samples.every(t=>t.level===0));e.mesh.visible=true;driver.update(e,{});assert(batch.update(s,1/60,{})>0);const hiddenParent=new THREE.Group();s.render.scene.add(hiddenParent);hiddenParent.add(e.mesh);hiddenParent.visible=false;driver.update(e,{});assert.equal(batch.update(s,1/60,{}),0);assert.equal(plume.pool.activeCount,0);assert(driver.binding.samples.every(t=>t.level===0));s.render.scene.add(e.mesh);hiddenParent.removeFromParent();driver.update(e,{});assert(batch.update(s,1/60,{})>0);assert(driver.binding.samples.filter(t=>t.channel.id.startsWith('MAIN')).every(t=>t.level>0));assert(driver.binding.samples.filter(t=>t.channel.id.startsWith('REVERSE')).every(t=>t.level===0));assert(Math.abs(instance.root.getObjectByName('MOTION_LATCH_PADDLE_A').quaternion.y+Math.sin(readLatchNative(e).angles[0]/2))<1e-6);
 s.render.scene.remove(e.mesh);assert.equal(batch.update(s,1/60,{}),0);assert.equal(plume.pool.activeCount,0);driver.update(e,{});assert(driver.binding.samples.every(t=>t.level===0&&t.materials.every(({material})=>material.emissiveIntensity===0)));s.render.scene=null;driver.update(e,{});assert(driver.binding.samples.every(t=>t.level===0));let materialDisposals=0;const owned=new Set(driver.binding.samples.flatMap(t=>t.materials.map(x=>x.material)));for(const m of owned)m.addEventListener('dispose',()=>materialDisposals++);driver.dispose();driver.dispose();assert.equal(materialDisposals,owned.size);
 }finally{batch?.dispose();driver?.dispose();owner.dispose();sim.dispose();instance.dispose();other.dispose();pkg.loader.dispose();}
});

 test('real place publication records the compiled Latch source independently of Ceres metadata',async()=>{
 const {buildAuthoredPlaceProp,upgradeAuthoredPlaceBoundaryForProbe}=await import('../src/render/partsLibrary.js');const {machineryPresentationPlace,bindMachineryPresentation}=await import('../src/core/machineryPresentation.js');
 const pkg=await packageFixture(),e={id:909,occupantGeneration:1,alive:true,type:'prop',hull:100,data:{role:'latch_nine',placeId:'place_latch_nine'}};const fallback=new THREE.Group(),scene=new THREE.Scene(),boundary=buildAuthoredPlaceProp(e,{fallbackRoot:fallback,releaseMode:true});e.mesh=boundary;scene.add(boundary);const state={entities:new Map([[e.id,e]]),entityList:[e],render:{scene}};
 const record=pkg.record;
 try{assert.equal(await upgradeAuthoredPlaceBoundaryForProbe(boundary,fallback,e,'places/place_latch_nine.glb',{},scene,{releaseMode:true,loadAuthoredPart:async()=>record,prepareAuthoredPipelines:async()=>({skipped:false})}),true);bindMachineryPresentation(e,boundary,state);assert.equal(machineryPresentationPlace(e,state),'place_latch_nine');const counts={};for(const lod of ['lod0','lod1','lod2']){boundary.userData.updateLod?.(lod);let meshes=0,triangles=0;boundary.traverse(n=>{if(!n.isMesh)return;for(let a=n;a;a=a.parent)if(a.visible===false)return;meshes++;triangles+=(n.geometry.index?.count||n.geometry.attributes.position?.count||0)/3;});counts[lod]={visibleMeshCandidates:meshes,triangles};}console.log('LATCH_COMPOSED_CPU_COUNTS',JSON.stringify(counts));scene.remove(boundary);assert.equal(machineryPresentationPlace(e,state),null);}finally{boundary.userData.dispose?.();pkg.loader.dispose();}
 });

test('source certificate, current native compound and every rendered LOD agree without relaxing coverage',async()=>{const {authoredCompoundCoverage,authoredCompoundMeasurement}=await import('../scripts/lib/modelTruthAuthoredCompound.mjs');const {latchNineCatalogRow}=await import('../src/render/latchNineVisuals.js');const bytes=fs.readFileSync('assets/ships/release/parts/places/place_latch_nine.glb'),doc=JSON.parse(bytes.subarray(20,20+bytes.readUInt32LE(12))),cert=doc.asset.extras.authoredCompound,measurement=authoredCompoundMeasurement(latchNineCatalogRow(()=>true));assert.equal(authoredCompoundCoverage([],measurement,cert).sourceCompoundParity,true);assert.throws(()=>authoredCompoundCoverage([],measurement,{...cert,assetId:'SF_FOREIGN'}),/identity mismatch/);const row=read('src/data/modelTruthCensus.json').rows.find(x=>x.id==='place_latch_nine');assert.equal(row.status,'green');assert(row.collider.coverageWu<=.05);assert.equal(row.collider.compoundBoxesWU.length,32);assert.equal(row.collider.sourceCompoundParity,true);});
