import test from 'node:test';import assert from 'node:assert/strict';
import {createSimulation} from '/workspace/scratch/d2415e46e35b/recovery-latch-20261004/normal-route-v2/src/core/sim.js';
import {createSg02DynamicBodyOwner} from '/workspace/scratch/d2415e46e35b/recovery-latch-20261004/normal-route-v2/src/core/sg02DynamicBodyOwner.js';
import {LATCH_GEOMETRY as G} from '/workspace/scratch/d2415e46e35b/recovery-latch-20261004/normal-route-v2/src/data/latchNineGeometry.js';
import {latchBodySpec,LATCH_RADIUS,latchPaddleSweep} from '/workspace/scratch/d2415e46e35b/recovery-latch-20261004/normal-route-v2/src/data/latchNineBody.js';
import {bindLatchNative,readLatchNative,requestLatchPaddles,stepLatchNative,detachLatchNative} from '/workspace/scratch/d2415e46e35b/recovery-latch-20261004/normal-route-v2/src/core/latchNineNative.js';
import {stepLatchPropulsion,latchPropulsionFrame} from '/workspace/scratch/d2415e46e35b/recovery-latch-20261004/normal-route-v2/src/systems/latchNinePropulsion.js';
async function fixture(){
 const sim=createSimulation({seed:9,systems:[]}),state=sim.state;state.mode='flight';state.world.currentSectorId='sector_tethys_junction';
 const entity=sim.spawn({type:'prop',hull:100,mass:140,radius:LATCH_RADIUS,pos:{x:0,z:0},vel:{x:0,z:0},rot:0,angVel:0,collides:true,physicsBody:latchBodySpec(),data:{role:'latch_nine',placeId:'place_latch_nine',latchNineService:{stationId:'station_tethys',sectorId:'sector_tethys_junction',box:{minX:19,maxX:21,minZ:-1,maxZ:1}}}});
 const owner=await createSg02DynamicBodyOwner({mode:'rapier-dynamic'});owner.syncFromEntities(state.entityList);const rec=owner.records.get(entity.id);return {sim,state,entity,owner,rec,close(){owner.dispose();sim.dispose();}};
}

import {writePhysicsControl,consumePhysicsCommand} from '/workspace/scratch/d2415e46e35b/recovery-latch-20261004/normal-route-v2/src/core/physicsAuthority.js';
import {forgetLatchPropulsion} from '/workspace/scratch/d2415e46e35b/recovery-latch-20261004/normal-route-v2/src/systems/latchNinePropulsion.js';
test('registry phase ordering publishes the previous witnessed firing after the next submission',async()=>{const h=await fixture();try{bindLatchNative(h.owner,h.rec);let forceTicks=0,visibleTicks=0;for(let i=0;i<10;i++){h.owner.step(1/60);h.state.simTime+=1/60;stepLatchPropulsion(h.state,h.entity,1/60);if(h.rec.controlForce.x>0)forceTicks++;if(latchPropulsionFrame(h.state,h.entity))visibleTicks++;}console.log({forceTicks,visibleTicks});assert(forceTicks>0);assert(visibleTicks>0,'Actual thrust must be visible at render phase following post-physics Latch update');}finally{h.close();}});
test('cleanup does not replace a later foreign control command',async()=>{const h=await fixture();try{bindLatchNative(h.owner,h.rec);stepLatchPropulsion(h.state,h.entity,1/60);writePhysicsControl(h.entity,{source:'foreign-controller',force:{x:0,y:0,z:123}});forgetLatchPropulsion(h.entity);const cmd=consumePhysicsCommand(h.entity);assert.equal(cmd.control.source,'foreign-controller');assert.equal(cmd.control.force.z,123);}finally{h.close();}});

test('full accepted paddle travel does not enter a new fixed hull slab',async()=>{const h=await fixture();try{bindLatchNative(h.owner,h.rec);function overlaps(i){const a=h.rec.colliders[G.staticSlabs.length+i];return G.staticSlabs.flatMap((p,j)=>{const ct=a.contactCollider(h.rec.colliders[j],0);return ct&&ct.distance<-.01?[p.id]:[];});}const rest=[0,1,2].map(overlaps);requestLatchPaddles(h.entity,[1.309,1.309,1.309]);for(let i=0;i<200;i++)stepLatchNative(h.owner,h.rec,1/60);h.owner.world.propagateModifiedBodyPositionsToColliders();const end=[0,1,2].map(overlaps);console.log({angles:readLatchNative(h.entity).angles,rest,end});for(let i=0;i<3;i++)assert.deepEqual(end[i].filter(v=>!rest[i].includes(v)),[]);}finally{h.close();}});
test('equal-valued foreign native force is not proof of Latch actuation',async()=>{const h=await fixture();try{bindLatchNative(h.owner,h.rec);stepLatchPropulsion(h.state,h.entity,1/60);const cmd=consumePhysicsCommand(h.entity);const f={...cmd.control.force},t={...cmd.control.torque};writePhysicsControl(h.entity,{source:'foreign-controller',force:f,torque:t});h.owner.step(1/60);assert.equal(latchPropulsionFrame(h.state,h.entity),null,'Foreign force must not light Latch mouths');}finally{h.close();}});
