import test from 'node:test';import assert from 'node:assert/strict';
import {createSimulation} from '../src/core/sim.js';
import {createSg02DynamicBodyOwner} from '../src/core/sg02DynamicBodyOwner.js';
import {LATCH_GEOMETRY as G} from '../src/data/latchNineGeometry.js';
import {latchBodySpec,LATCH_RADIUS,latchPaddleSweep} from '../src/data/latchNineBody.js';
import {bindLatchNative,readLatchNative,requestLatchPaddles,stepLatchNative,detachLatchNative} from '../src/core/latchNineNative.js';
import {stepLatchPropulsion,latchPropulsionFrame} from '../src/systems/latchNinePropulsion.js';
async function fixture({yaw=0}={}){
 const sim=createSimulation({seed:9,systems:[]}),state=sim.state;state.mode='flight';state.world.currentSectorId='sector_tethys_junction';
 const entity=sim.spawn({type:'prop',hull:100,mass:140,radius:LATCH_RADIUS,pos:{x:0,z:0},vel:{x:0,z:0},rot:yaw,angVel:0,collides:true,physicsBody:latchBodySpec(),data:{role:'latch_nine',placeId:'place_latch_nine',latchNineService:{stationId:'station_tethys',sectorId:'sector_tethys_junction',box:{minX:19,maxX:21,minZ:-1,maxZ:1}}}});
 const owner=await createSg02DynamicBodyOwner({mode:'rapier-dynamic'});owner.syncFromEntities(state.entityList);const rec=owner.records.get(entity.id);return {sim,state,entity,owner,rec,close(){owner.dispose();sim.dispose();}};
}
test('real native compound has source slabs and three solid paddles; never an enclosing convex hull',async()=>{const h=await fixture();try{assert.equal(h.rec.colliders.length,G.staticSlabs.length+3);assert.equal(h.rec.body.isDynamic(),true);assert.equal(bindLatchNative(h.owner,h.rec),true);assert.equal(readLatchNative(h.entity).angles.length,3);assert(h.rec.colliders.every(c=>!c.isSensor()));}finally{h.close();}});
test('paddles move actual native colliders and stale generations cannot command or render',async()=>{const h=await fixture();try{assert(bindLatchNative(h.owner,h.rec));assert(requestLatchPaddles(h.entity,[.2,.2,.2]));const before=h.rec.colliders[G.staticSlabs.length+2].translation();for(let i=0;i<20;i++)stepLatchNative(h.owner,h.rec,1/60);assert(readLatchNative(h.entity).angles[2]>.1);const after=h.rec.colliders[G.staticSlabs.length+2].translation();assert.notDeepEqual(before,after);h.entity.occupantGeneration++;assert.equal(requestLatchPaddles(h.entity,[0,0,0]),false);assert.equal(readLatchNative(h.entity),null);assert.equal(stepLatchNative(h.owner,h.rec,1/60),false);}finally{h.close();}});
test('a real native blocker stops a swept blade before endpoint penetration',async()=>{const h=await fixture();try{bindLatchNative(h.owner,h.rec);const obstacle=h.sim.spawn({type:'prop',alive:true,radius:.4,pos:{x:1.25,z:7.5},vel:{x:0,z:0},collides:true,physicsBody:{dynamic:false,mass:100,radius:.4,shape:'ball'}});h.owner.syncFromEntities(h.state.entityList);requestLatchPaddles(h.entity,[0,0,.8]);for(let i=0;i<100;i++)stepLatchNative(h.owner,h.rec,1/60);const f=readLatchNative(h.entity);assert(f.blocked[2]);assert(f.angles[2]<.8);assert(h.owner.records.get(obstacle.id));}finally{h.close();}});
test('continuous rotational bounds include intermediate arc extrema, not only endpoints',()=>{const b=latchPaddleSweep(0,-.8,.8);assert(b.hz>1.8);assert(b.hx>2.8);});
test('propulsion requires a later native force witness; stale physics and scene lives stay dark',async()=>{const h=await fixture();try{bindLatchNative(h.owner,h.rec);assert(stepLatchPropulsion(h.state,h.entity,1/60));assert.equal(latchPropulsionFrame(h.state,h.entity),null);h.owner.step(1/60);const frame=latchPropulsionFrame(h.state,h.entity);assert(frame);assert(frame.thrusters.some(t=>t.fraction>0));assert(h.entity.vel.x>0);detachLatchNative(h.rec);assert.equal(latchPropulsionFrame(h.state,h.entity),null);}finally{h.close();}});
test('same life with replaced manifest/spec/body cannot inherit accepted motion or plume',async()=>{const h=await fixture();try{bindLatchNative(h.owner,h.rec);requestLatchPaddles(h.entity,[.1,0,0]);stepLatchNative(h.owner,h.rec,1/60);h.entity.physicsBody={...h.entity.physicsBody};assert.equal(readLatchNative(h.entity),null);assert.equal(stepLatchNative(h.owner,h.rec,1/60),false);}finally{h.close();}});
test('forged same-id geometry never obtains a Latch physical binding',async()=>{const h=await fixture();try{h.entity.physicsBody.collisionProxyManifest.primitives[0].hx*=2;assert.equal(bindLatchNative(h.owner,h.rec),false);assert.equal(readLatchNative(h.entity),null);}finally{h.close();}});
test('disabled, dead and disposed native owners immediately invalidate render and command leases',async()=>{const h=await fixture();try{bindLatchNative(h.owner,h.rec);h.entity.data.disabled=true;assert.equal(readLatchNative(h.entity),null);assert.equal(requestLatchPaddles(h.entity,[1,1,1]),false);h.entity.data.disabled=false;h.entity.hull=0;assert.equal(readLatchNative(h.entity),null);h.entity.hull=100;h.owner.dispose();assert.equal(readLatchNative(h.entity),null);}finally{h.sim.dispose();}});
test('full rotational motor remains bounded; accepted native orientation matches its centre arc',async()=>{const h=await fixture();try{bindLatchNative(h.owner,h.rec);requestLatchPaddles(h.entity,[-99,99,99]);for(let i=0;i<200;i++)stepLatchNative(h.owner,h.rec,1/60);const f=readLatchNative(h.entity);assert(f.angles.every(x=>x>=-Math.PI/3&&x<=Math.PI*5/12));const p=h.rec.colliders[G.staticSlabs.length].translationWrtParent(),a=f.angles[0];assert(Math.abs(p.x-(-3.4-Math.sin(a)*1.8))<1e-5);assert(Math.abs(p.z-(4.35+Math.cos(a)*1.8))<1e-5);const q=h.rec.colliders[G.staticSlabs.length].rotationWrtParent();assert(Math.abs(q.y+Math.sin(a/2))<1e-5);}finally{h.close();}});
test('cold semantic Continue creates fresh bindings and never revives prior motor angles or native receipt',async()=>{const h=await fixture();const fresh=await fixture();try{bindLatchNative(h.owner,h.rec);requestLatchPaddles(h.entity,[.2,.2,.2]);for(let i=0;i<10;i++)stepLatchNative(h.owner,h.rec,1/60);const {createLatchNineService}=await import('../src/systems/latchNineService.js');const source=createLatchNineService();source.deserialize({met:true,cleanArrivals:7,incidentIds:['incident1'],destroyed:false,angles:[99],nativeHandle:3});const saved=JSON.parse(JSON.stringify(source.serialize()));assert.deepEqual(Object.keys(saved).sort(),['cleanArrivals','destroyed','incidentIds','met']);const restored=createLatchNineService();restored.deserialize(saved);assert.deepEqual(restored.serialize(),saved);assert(bindLatchNative(fresh.owner,fresh.rec));assert.deepEqual(readLatchNative(fresh.entity).angles,[0,0,0]);assert.equal(latchPropulsionFrame(fresh.state,fresh.entity),null);assert.equal(fresh.entity.vel.x,0);}finally{h.close();fresh.close();}});
test('opaque non-rest native snapshot is rejected rather than misbinding physical paddles on Continue',async()=>{const h=await fixture();const fresh=await fixture();try{bindLatchNative(h.owner,h.rec);requestLatchPaddles(h.entity,[.3,.3,.3]);for(let i=0;i<10;i++)stepLatchNative(h.owner,h.rec,1/60);const saved=h.owner.exportWorldSnapshot();assert.equal(fresh.owner.adoptWorldSnapshot(saved,[fresh.entity],{entityIdRemap:new Map([[String(h.entity.id),fresh.entity.id]])}),false);assert(bindLatchNative(fresh.owner,fresh.rec));assert.deepEqual(readLatchNative(fresh.entity).angles,[0,0,0]);}finally{h.close();fresh.close();}});
// Actual asset/presentation verification now exercises the canonical compiled package
// in latch-nine-package-presentation.test.mjs, replacing the private checkpoint adapter.
test('signed force allocations select opposite real mouths; idle and sector-detached actuation stay dark',async()=>{const h=await fixture();try{bindLatchNative(h.owner,h.rec);stepLatchPropulsion(h.state,h.entity,1/60);h.owner.step(1/60);let f=latchPropulsionFrame(h.state,h.entity);assert(f.thrusters.filter(t=>t.id.startsWith('MAIN')).every(t=>t.fraction>0));assert(f.thrusters.filter(t=>t.id.startsWith('REVERSE')).every(t=>t.fraction===0));h.entity.data.latchNineService.box={minX:-21,maxX:-19,minZ:-1,maxZ:1};stepLatchPropulsion(h.state,h.entity,1/60);h.owner.step(1/60);f=latchPropulsionFrame(h.state,h.entity);assert(f.thrusters.filter(t=>t.id.startsWith('REVERSE')).every(t=>t.fraction>0));assert(f.thrusters.filter(t=>t.id.startsWith('MAIN')).every(t=>t.fraction===0));h.state.world.currentSectorId='elsewhere';assert.equal(latchPropulsionFrame(h.state,h.entity),null);}finally{h.close();}const idle=await fixture();try{bindLatchNative(idle.owner,idle.rec);idle.entity.data.latchNineService.box={minX:-1,maxX:1,minZ:-1,maxZ:1};stepLatchPropulsion(idle.state,idle.entity,1/60);idle.owner.step(1/60);assert(latchPropulsionFrame(idle.state,idle.entity).thrusters.every(t=>t.fraction===0));}finally{idle.close();}});
test('leaving the service sector cancels its queued force without deleting foreign impulses',async()=>{const h=await fixture();try{bindLatchNative(h.owner,h.rec);stepLatchPropulsion(h.state,h.entity,1/60);const {queuePhysicsImpulse}=await import('../src/core/physicsAuthority.js');queuePhysicsImpulse(h.entity,{x:0,y:0,z:140});h.state.world.currentSectorId='elsewhere';assert.equal(stepLatchPropulsion(h.state,h.entity,1/60),false);h.owner.step(1/60);assert(Math.abs(h.rec.controlForce.x)<1e-9);assert(h.entity.vel.z>.5);assert.equal(latchPropulsionFrame(h.state,h.entity),null);}finally{h.close();}});

test('signed socket moment matches native game-yaw torque and turns a misaligned tender toward rest',async()=>{const h=await fixture({yaw:.3});try{bindLatchNative(h.owner,h.rec);stepLatchPropulsion(h.state,h.entity,1/60);h.owner.step(1/60);const f=latchPropulsionFrame(h.state,h.entity);assert(f);const moment=f.thrusters.reduce((sum,t,i)=>{const force=t.fraction*G.thrusters[i].maxForce;return sum+(t.position[0]*-t.exhaust[2]-t.position[2]*-t.exhaust[0])*force;},0);assert(Math.abs(h.rec.controlTorque.y-moment)<1e-5);assert(moment<0);assert(h.entity.rot<.3);}finally{h.close();}});
