// One deep-space light for every authored PBR surface (AQ-LIGHT; surfacing pass 2026-09-30).
//
// spaceReflectionEnvironment.js gave chrome hulls reflected structure, but its three emissive
// cards are an abstract studio rig. The Poly Haven industrial_workshop_foundry HDRI replaced
// them with a real image — and hulls mirrored its indoor structure: window rectangles,
// gantries, a painted floor. This module now serves an authored SPACE environment instead
// (assets/background/env/deep_space_2k.hdr, generated by scripts/generate-space-ibl.mjs):
// a deep-space floor, a galactic band with star glints, one warm sun lobe agreeing with the
// sector key rig, a broad cool planet-bounce lobe, and subtle nebula structure — so bare
// metal, coated paint, and rubber separate under light that belongs to the game's setting.
// The foundry HDRI stays on disk as the retired alternate source; provenance:
// assets/background/env/PROVENANCE.md.
//
// The visible sky is never touched: this texture is a scene.environment input only, and
// scene.background keeps the sector deep-sky plate.
//
// The source's absolute radiance is normalized once at load to the card rig's
// mean-luminance band. Diffuse pickup keeps the shipped balance — muzzle and engine
// emissives stay dominant — while the structure of the reflections is what changes.

// Served path for the promoted runtime copy. Authored in-repo; see PROVENANCE.md.
export const FOUNDRY_IBL_URL = '/assets/background/env/deep_space_2k.hdr';

// Build-time product of the .hdr + the decode/normalize/neutralize chain below
// (scripts/bake-foundry-ibl.mjs --source=deep_space_2k, schema spaceface.foundryIblBake.v1).
// The runtime fast path wraps the shipped Float32 payload in the same DataTexture the decode
// path produces — same pixels, ~120 ms of boot-window main-thread decode+transform skipped.
export const FOUNDRY_IBL_BAKED_URL = '/assets/background/env/deep_space_2k.f32.bin';
export const FOUNDRY_IBL_BAKED_MANIFEST_URL = '/assets/background/env/deep_space_2k.f32.json';
export const FOUNDRY_IBL_BAKED_SCHEMA = 'spaceface.foundryIblBake.v1';

// Normalize the HDR's mean luminance to the card rig's diffuse band (radiance 4.2/3.0/1.15
// cards covering a modest fraction of a near-black sky ≈ ~1 mean). The environment therefore
// lifts surfaces exactly as much as the shipped rig did; only the reflected structure changes.
export const FOUNDRY_IBL_TARGET_MEAN_RADIANCE = 1.0;

export const IBL_SOURCE_FOUNDRY = 'foundry';
export const IBL_SOURCE_BACKGROUND = 'background';
export const IBL_SOURCE_REFLECTION_CARDS = 'reflection-cards';

// Every PMREM bake — foundry HDRI, sector-plate background, or card-rig fallback — must emit the
// same cube-map size. The output texture's cubeUV height sits in each lit material's shader
// program key (envMapCubeUVHeight), so a bake at a different resolution silently re-keys and
// re-links every standard material on the next presented pass — a multi-second GPU brick on the
// live route, not just in probes. Equirect sources size their bake from the input width, so
// renderer._bakeEnv routes them through a fixed-size scene capture instead of fromEquirectangular.
// 512 is the card rig's tuned size: its 0.02 radian prefilter requests ~20 blur taps at 512px and
// PMREM's blur shader caps at 20 — a larger pin would clip the kernel and log a THREE warning on
// every bake (which the performance harness counts as a runtime error). The foundry 2k HDRI
// downsamples to 512 cleanly; its structure survives because env lookups are mip-blurred anyway.
export { SPACE_REFLECTION_PMREM_CUBE_SIZE as IBL_PMREM_CUBE_SIZE } from './spaceReflectionEnvironment.js';

// Priority for the PMREM source: the foundry HDRI wins once loaded; until then the existing
// chain holds (sector-plate background texture, else the emissive card rig). scene.background
// is never reassigned from here — the resolver only reads it.
export function resolveIblSource({ foundryTexture = null, background = null } = {}) {
  if (foundryTexture && foundryTexture.isTexture) return IBL_SOURCE_FOUNDRY;
  if (background && background.isTexture) return IBL_SOURCE_BACKGROUND;
  return IBL_SOURCE_REFLECTION_CARDS;
}

// Load + normalize the foundry HDRI. Prefers the baked f32 artifact (FOUNDRY_IBL_BAKED_URL):
// its bytes ARE the decode + normalize + neutralize output, so the served texture is identical
// and the ~120 ms of Float32 decode + two full-image passes never runs at boot. Any artifact
// that fails the manifest + sha256 check is rejected and the .hdr decode path below produces
// the same pixels instead — the env is identical either way. Returns the DataTexture or null
// when unavailable — the renderer treats it as an optional upgrade and keeps whichever env it
// already has.
export async function loadFoundryIblTexture(THREE, {
  url = FOUNDRY_IBL_URL,
  bakedUrl = FOUNDRY_IBL_BAKED_URL,
  bakedManifestUrl = FOUNDRY_IBL_BAKED_MANIFEST_URL,
  fetchImpl = undefined,
} = {}) {
  if (!THREE) throw new TypeError('loadFoundryIblTexture requires THREE');
  const baked = await loadBakedFoundryIblTexture(THREE, {
    url: bakedUrl,
    manifestUrl: bakedManifestUrl,
    fetchImpl,
  });
  if (baked) return baked;
  let HDRLoader;
  try {
    ({ HDRLoader } = await import('three/addons/loaders/HDRLoader.js'));
  } catch (_) {
    return null;
  }
  try {
    const loader = new HDRLoader();
    // Float data keeps the luminance normalization a plain multiply on Float32Array; the
    // texture is the PMREM source only, so 33 MB resident is a one-time singleton cost.
    loader.setDataType(THREE.FloatType);
    const texture = await loader.loadAsync(url);
    texture.mapping = THREE.EquirectangularReflectionMapping;
    normalizeHdrMeanRadiance(texture, FOUNDRY_IBL_TARGET_MEAN_RADIANCE);
    neutralizeHdrGreenCast(texture);
    texture.needsUpdate = true;
    return texture;
  } catch (_) {
    return null;
  }
}

// Runtime check that the baked value is used: the shipped payload bytes must hash to the
// manifest's sha256 — i.e. the bytes wrapped into the texture are exactly what the bake (and
// therefore the runtime algorithm) produced. A missing/mismatched artifact returns null so the
// caller falls back to the decode path rather than trusting unverified pixels.
export async function loadBakedFoundryIblTexture(THREE, {
  url = FOUNDRY_IBL_BAKED_URL,
  manifestUrl = FOUNDRY_IBL_BAKED_MANIFEST_URL,
  fetchImpl = undefined,
} = {}) {
  const fetcher = fetchImpl || (typeof fetch === 'function' ? fetch : null);
  const subtle = (typeof crypto !== 'undefined' && crypto && crypto.subtle) || null;
  if (!fetcher || !subtle || typeof subtle.digest !== 'function') return null;
  try {
    const [manifestRes, binRes] = await Promise.all([fetcher(manifestUrl), fetcher(url)]);
    if (!manifestRes.ok || !binRes.ok) return null;
    const manifest = await manifestRes.json();
    const payload = await binRes.arrayBuffer();
    if (!manifest || manifest.schema !== FOUNDRY_IBL_BAKED_SCHEMA) return null;
    if (manifest.pixelFormat !== 'float32-rgba' || manifest.channels !== 4) return null;
    const width = manifest.width | 0, height = manifest.height | 0;
    if (width <= 0 || height <= 0) return null;
    if (payload.byteLength !== width * height * 4 * Float32Array.BYTES_PER_ELEMENT) return null;
    if (typeof manifest.sha256 !== 'string' || !/^[0-9a-f]{64}$/i.test(manifest.sha256)) return null;
    const digest = await subtle.digest('SHA-256', payload);
    const hex = [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, '0')).join('');
    if (hex !== manifest.sha256.toLowerCase()) return null;
    const texture = new THREE.DataTexture(new Float32Array(payload), width, height);
    // Match DataTextureLoader's field setup exactly (LinearFilter overrides DataTexture's
    // Nearest defaults; wrap/format/anisotropy already agree with the decode path's product).
    texture.type = THREE.FloatType;
    texture.magFilter = THREE.LinearFilter;
    texture.minFilter = THREE.LinearFilter;
    texture.mapping = THREE.EquirectangularReflectionMapping;
    texture.userData.foundryIblBaked = { verified: true, sha256: manifest.sha256 };
    texture.needsUpdate = true;
    return texture;
  } catch (_) {
    return null;
  }
}

// Scale HDR pixel data in place so the mean luminance lands on targetMean. Returns the applied
// stats, or null when the data is not float RGB(A) pixels (unexpected loader output).
export function normalizeHdrMeanRadiance(texture, targetMean) {
  const image = texture && texture.image;
  const data = image && image.data;
  if (!(data instanceof Float32Array) || !Number.isFinite(targetMean) || targetMean <= 0) return null;
  const channels = Math.round(data.length / Math.max(1, image.width * image.height));
  if (channels < 3 || channels > 4) return null;
  let sum = 0;
  let samples = 0;
  for (let i = 0; i + 2 < data.length; i += channels) {
    const r = data[i], g = data[i + 1], b = data[i + 2];
    if (!Number.isFinite(r) || !Number.isFinite(g) || !Number.isFinite(b)) continue;
    const lum = 0.2126 * Math.max(0, r) + 0.7152 * Math.max(0, g) + 0.0722 * Math.max(0, b);
    sum += lum;
    samples += 1;
  }
  const meanBefore = samples > 0 ? sum / samples : 0;
  if (meanBefore <= 0) return { meanBefore, meanAfter: 0, scaleFactor: 1, samples };
  const scaleFactor = targetMean / meanBefore;
  for (let i = 0; i + 2 < data.length; i += channels) {
    data[i] *= scaleFactor;
    data[i + 1] *= scaleFactor;
    data[i + 2] *= scaleFactor;
  }
  return { meanBefore, meanAfter: targetMean, scaleFactor, samples };
}

// Generic green-cast guard, kept from the foundry source (whose painted floor was
// green-dominant and mirrored as a lime cast on smooth metal — PQ-193). Pull each
// green-dominant texel toward a warm neutral at its own luminance, with a soft knee keyed on how
// far green runs ahead of the warm channels; luminance and structure are preserved, and warm or
// neutral texels are never touched. The authored deep-space source is blue/warm by design, so
// this pass touches only a rounding-error handful of texels there (bake stats record the count).
// Returns the count of altered texels, or null when the data is not float RGB(A) pixels.
export function neutralizeHdrGreenCast(texture) {
  const image = texture && texture.image;
  const data = image && image.data;
  if (!(data instanceof Float32Array)) return null;
  const channels = Math.round(data.length / Math.max(1, image.width * image.height));
  if (channels < 3 || channels > 4) return null;
  let touched = 0;
  for (let i = 0; i + 2 < data.length; i += channels) {
    const r = data[i], g = data[i + 1], b = data[i + 2];
    if (!Number.isFinite(r) || !Number.isFinite(g) || !Number.isFinite(b)) continue;
    const warm = Math.max(r, b);
    const over = g - warm;
    if (over <= 0) continue;
    // Soft knee: a mild lead desaturates gently; the painted floor (G ≈ 1.4-1.8x the warm
    // channels) is fully neutralized rather than merely dimmed.
    const t = Math.min(1, over / Math.max(warm * 0.4, 0.05));
    const lum = 0.2126 * Math.max(0, r) + 0.7152 * Math.max(0, g) + 0.0722 * Math.max(0, b);
    // Warm-neutral target keeps the foundry's cast instead of a sterile grey, normalized so the
    // texel's luminance is preserved exactly.
    const s = lum / (0.2126 * 1.1 + 0.7152 + 0.0722 * 0.78);
    data[i] = r + (s * 1.1 - r) * t;
    data[i + 1] = g + (s - g) * t;
    data[i + 2] = b + (s * 0.78 - b) * t;
    touched += 1;
  }
  return touched;
}
