// Generated by scripts/build-render-package-pilots.mjs. Do not edit by hand.
const PILOTS = [
  {
    "assetId": "sf.render.kestrel",
    "expectedContentHash": "bca09ddea215d022bb80ba188f545c3a09b16567718f2b2f60c93d24afca011b",
    "key": "kestrel",
    "metadataUrl": "assets/ships/release/render-packages/kestrel/render-package.json",
    "runtimeAssetId": "SF_K0_KESTREL_BORROWED_TIME_V4",
    "slot": "hull",
    "sourceSha256": "dc4b841191e76e175f9e3aac93f30a9b4a1578b2f4da4127b83146468185c1a2",
    "sourceUrl": "assets/ships/release/parts/wholeships/kestrel.glb"
  },
  {
    "assetId": "sf.render.ashline-dart",
    "expectedContentHash": "fd133219b7c5600046a1fdb87c8cea87dd562ade3e1cecce5cd05d17e20dd9a9",
    "key": "ashline-dart",
    "metadataUrl": "assets/ships/release/render-packages/ashline-dart/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_ASHLINE_DART",
    "slot": "hull",
    "sourceSha256": "a9129044a5e791efe59cbabfd3c2961642b79a9c1c9ee22e4d3eea22719cc0b7",
    "sourceUrl": "assets/ships/release/parts/wholeships/ashline_dart.glb"
  },
  {
    "assetId": "sf.render.ashline-lode",
    "expectedContentHash": "f30c8484ccbe0eea64a5b223243b020272341869b1fd133ec4c9597cb7699021",
    "key": "ashline-lode",
    "metadataUrl": "assets/ships/release/render-packages/ashline-lode/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_ASHLINE_LODE",
    "slot": "hull",
    "sourceSha256": "d1d30208913b7bc49e96dfc78dc5acc19b8ecfc191a4a5136853828181824656",
    "sourceUrl": "assets/ships/release/parts/wholeships/ashline_lode.glb"
  },
  {
    "assetId": "sf.render.ashline-rig",
    "expectedContentHash": "036e3bb3dcbb3786b01b10c7fceb064b08cab8d0b40b89084a98e2b40fae25c2",
    "key": "ashline-rig",
    "metadataUrl": "assets/ships/release/render-packages/ashline-rig/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_ASHLINE_RIG",
    "slot": "hull",
    "sourceSha256": "32ecc2bc92b351ff68186b1eca331149a14d200561d445309d6d9b1a322723c9",
    "sourceUrl": "assets/ships/release/parts/wholeships/ashline_rig.glb"
  },
  {
    "assetId": "sf.render.helios-lark",
    "expectedContentHash": "0f102b291fe663976a191ec859c6e349fa02cec0b786bc0ec34a1d0d64683280",
    "key": "helios-lark",
    "metadataUrl": "assets/ships/release/render-packages/helios-lark/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_HELIOS_LARK",
    "slot": "hull",
    "sourceSha256": "5dfb6c2a2baaa4c8e92758f4e969d262ee668cbf22e5de73020df659e782a473",
    "sourceUrl": "assets/ships/release/parts/wholeships/helios_lark.glb"
  },
  {
    "assetId": "sf.render.helios-cradle",
    "expectedContentHash": "8cba03203acacab66fafd0239876cbb460d79cba907fcf15ebd24f27fa4ee0fb",
    "key": "helios-cradle",
    "metadataUrl": "assets/ships/release/render-packages/helios-cradle/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_HELIOS_CRADLE",
    "slot": "hull",
    "sourceSha256": "6f400dfd7caf7e18df1b0cb951e77ec2c8773a4cd8321243e4c259c840c778de",
    "sourceUrl": "assets/ships/release/parts/wholeships/helios_cradle.glb"
  },
  {
    "assetId": "sf.render.helios-span",
    "expectedContentHash": "ad527d2261b16c43f45a01bd08b77031b6670a84d5ecd8a621aa007783565b06",
    "key": "helios-span",
    "metadataUrl": "assets/ships/release/render-packages/helios-span/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_HELIOS_SPAN",
    "slot": "hull",
    "sourceSha256": "5fb2a62c79d3bc07777c5bf5ff9d2e26554e2bf3bfca051ba470d28adb6ed1b5",
    "sourceUrl": "assets/ships/release/parts/wholeships/helios_span.glb"
  },
  {
    "assetId": "sf.render.helios-trade-hub",
    "expectedContentHash": "aebd617d4de9385036ff86117b790df95385085c18ecfb9554e15f9f2d60b5be",
    "key": "helios-trade-hub",
    "metadataUrl": "assets/ships/release/render-packages/helios-trade-hub/render-package.json",
    "runtimeAssetId": "SF_PLACE_STATION_TRADE_HUB",
    "slot": "place",
    "sourceSha256": "9540c8fa263359ff3b78302a9d48080af17cb903f47d43361814ba3666f0754a",
    "sourceUrl": "assets/ships/release/parts/places/place_station_trade_hub.glb"
  },
  {
    "assetId": "sf.render.ceres-refinery",
    "expectedContentHash": "74abae3de971e354b1714e5103575e4041a588992226296b371a77330ab3e225",
    "key": "ceres-refinery",
    "metadataUrl": "assets/ships/release/render-packages/ceres-refinery/render-package.json",
    "runtimeAssetId": "SF_PLACE_STATION_REFINERY",
    "slot": "place",
    "sourceSha256": "3b673f761f8e47c32ffa0563b933ad099380d2df75629dca927481cec4c8b7c0",
    "sourceUrl": "assets/ships/release/parts/places/place_station_refinery.glb"
  },
  {
    "assetId": "sf.render.jump-ring",
    "expectedContentHash": "42973d138278c42f7c014d087d687fcce0ff7e5ccffbe5112a88ccb2055f8b6c",
    "key": "jump-ring",
    "metadataUrl": "assets/ships/release/render-packages/jump-ring/render-package.json",
    "runtimeAssetId": "SF_PLACE_GATE_JUMP_RING",
    "slot": "place",
    "sourceSha256": "01ccf2695678cb42c5b086308b7bea6dc366b029b4efc9e12393a10e8b209ead",
    "sourceUrl": "assets/ships/release/parts/places/place_gate_jump_ring.glb"
  },
  {
    "assetId": "sf.render.debris-chunk",
    "expectedContentHash": "bcdc56af24fa720b46cd5b9679335b83bae5ff7466b7aad0274cdccec2778ece",
    "key": "debris-chunk",
    "metadataUrl": "assets/ships/release/render-packages/debris-chunk/render-package.json",
    "runtimeAssetId": "place_debris_chunk",
    "slot": "place",
    "sourceSha256": "016e7a103a40b7ba3183d56fcef1362aea0c3723274b49d4ab2439ae51151a26",
    "sourceUrl": "assets/ships/release/parts/places/place_debris_chunk.glb"
  },
  {
    "assetId": "sf.render.dead-hulk",
    "expectedContentHash": "1540cec5990525e6690df0f75da777b828e937ef404cd04e3ce23bf0301be672",
    "key": "dead-hulk",
    "metadataUrl": "assets/ships/release/render-packages/dead-hulk/render-package.json",
    "runtimeAssetId": "place_dead_hulk",
    "slot": "place",
    "sourceSha256": "c2c421c6ff4b87cb92566560e080190f77ac14336b0fc43045bd2be9d02ba185",
    "sourceUrl": "assets/ships/release/parts/places/place_dead_hulk.glb"
  },
  {
    "assetId": "sf.render.dock-interior",
    "expectedContentHash": "84e22e90240c8baf497b432871ae7b6b73e3d7ac36dc7ef9f067857ee48c8467",
    "key": "dock-interior",
    "metadataUrl": "assets/ships/release/render-packages/dock-interior/render-package.json",
    "runtimeAssetId": "place_dock_interior",
    "slot": "place",
    "sourceSha256": "926cb7784e61f8adcc533945c4c254f8d7e0af14efeff465bfd8b2caa6f0a6de",
    "sourceUrl": "assets/ships/release/parts/places/place_dock_interior.glb"
  },
  {
    "assetId": "sf.render.wasp",
    "expectedContentHash": "c593b69d726c28ed88f331c90a1324da925702cc5b434356fd3208458e079c7e",
    "key": "wasp",
    "metadataUrl": "assets/ships/release/render-packages/wasp/render-package.json",
    "runtimeAssetId": "SF_WASP_PRODUCTION_V1",
    "slot": "hull",
    "sourceSha256": "a23354195d95d57bdc2d2e8e32d5cd4fcc1f6c05d570033a7c1849ac87408dde",
    "sourceUrl": "assets/ships/release/parts/wholeships/wasp_production_v1.glb"
  }
];

export const RENDER_PACKAGE_PILOTS = Object.freeze(PILOTS.map((entry) => Object.freeze(entry)));

const BY_SOURCE_URL = new Map(RENDER_PACKAGE_PILOTS.map((entry) => [entry.sourceUrl, entry]));
const BY_ASSET_ID = new Map(RENDER_PACKAGE_PILOTS.map((entry) => [entry.assetId, entry]));

export function renderPackagePilotForSourceUrl(url) {
  const clean = String(url || '').replace(/\\/g, '/').split(/[?#]/, 1)[0].replace(/^\.\//, '');
  return BY_SOURCE_URL.get(clean) || null;
}

export function renderPackagePilotForAssetId(assetId) {
  return BY_ASSET_ID.get(String(assetId || '')) || null;
}
