// Generated by scripts/build-render-package-pilots.mjs. Do not edit by hand.
const PILOTS = [
  {
    "assetId": "sf.render.kestrel",
    "expectedContentHash": "75bdc376afc9d37d2e73500458d64b06179a3fb7cc4174a444e25a1f088b0c01",
    "key": "kestrel",
    "metadataUrl": "assets/ships/release/render-packages/kestrel/render-package.json",
    "runtimeAssetId": "SF_K0_KESTREL_BORROWED_TIME_V4",
    "slot": "hull",
    "sourceSha256": "dc4b841191e76e175f9e3aac93f30a9b4a1578b2f4da4127b83146468185c1a2",
    "sourceUrl": "assets/ships/release/parts/wholeships/kestrel.glb"
  },
  {
    "assetId": "sf.render.ashline-dart",
    "expectedContentHash": "55c2a250ad0bb855d3009e025cd4c4b4e7c492e26a17c28eb924657ec3a6d5c3",
    "key": "ashline-dart",
    "metadataUrl": "assets/ships/release/render-packages/ashline-dart/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_ASHLINE_DART",
    "slot": "hull",
    "sourceSha256": "a9129044a5e791efe59cbabfd3c2961642b79a9c1c9ee22e4d3eea22719cc0b7",
    "sourceUrl": "assets/ships/release/parts/wholeships/ashline_dart.glb"
  },
  {
    "assetId": "sf.render.ashline-lode",
    "expectedContentHash": "6a76528a28bc94e3a2b125524fecbb8f10102bc7ec7fb4f5537fb62a0b0c4e7f",
    "key": "ashline-lode",
    "metadataUrl": "assets/ships/release/render-packages/ashline-lode/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_ASHLINE_LODE",
    "slot": "hull",
    "sourceSha256": "d1d30208913b7bc49e96dfc78dc5acc19b8ecfc191a4a5136853828181824656",
    "sourceUrl": "assets/ships/release/parts/wholeships/ashline_lode.glb"
  },
  {
    "assetId": "sf.render.ashline-rig",
    "expectedContentHash": "a8fbf45bb4370742cd6ff7bd03332f36ad57cd7dc440ae425b9ce9f54a3d14b0",
    "key": "ashline-rig",
    "metadataUrl": "assets/ships/release/render-packages/ashline-rig/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_ASHLINE_RIG",
    "slot": "hull",
    "sourceSha256": "32ecc2bc92b351ff68186b1eca331149a14d200561d445309d6d9b1a322723c9",
    "sourceUrl": "assets/ships/release/parts/wholeships/ashline_rig.glb"
  },
  {
    "assetId": "sf.render.helios-lark",
    "expectedContentHash": "6867a5814261010f3f1da26c55f0241e04562d557e7bb250e1841ee08ab4a784",
    "key": "helios-lark",
    "metadataUrl": "assets/ships/release/render-packages/helios-lark/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_HELIOS_LARK",
    "slot": "hull",
    "sourceSha256": "5dfb6c2a2baaa4c8e92758f4e969d262ee668cbf22e5de73020df659e782a473",
    "sourceUrl": "assets/ships/release/parts/wholeships/helios_lark.glb"
  },
  {
    "assetId": "sf.render.helios-cradle",
    "expectedContentHash": "74906c07b0d8455b5753f26d92ddba74b50ec35d7ae5ad6777904dc9d8003350",
    "key": "helios-cradle",
    "metadataUrl": "assets/ships/release/render-packages/helios-cradle/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_HELIOS_CRADLE",
    "slot": "hull",
    "sourceSha256": "6f400dfd7caf7e18df1b0cb951e77ec2c8773a4cd8321243e4c259c840c778de",
    "sourceUrl": "assets/ships/release/parts/wholeships/helios_cradle.glb"
  },
  {
    "assetId": "sf.render.helios-span",
    "expectedContentHash": "c2e4267f26d23b6f7e38b3b206aa72b52c949787123a6b49b26250c350ad9b27",
    "key": "helios-span",
    "metadataUrl": "assets/ships/release/render-packages/helios-span/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_HELIOS_SPAN",
    "slot": "hull",
    "sourceSha256": "5fb2a62c79d3bc07777c5bf5ff9d2e26554e2bf3bfca051ba470d28adb6ed1b5",
    "sourceUrl": "assets/ships/release/parts/wholeships/helios_span.glb"
  },
  {
    "assetId": "sf.render.helios-trade-hub",
    "expectedContentHash": "3d1cf0e0a50ece87889bb2281663934ccee7fc34115d1a7e34a1eaa4e5a7e1e6",
    "key": "helios-trade-hub",
    "metadataUrl": "assets/ships/release/render-packages/helios-trade-hub/render-package.json",
    "runtimeAssetId": "SF_PLACE_STATION_TRADE_HUB",
    "slot": "place",
    "sourceSha256": "9540c8fa263359ff3b78302a9d48080af17cb903f47d43361814ba3666f0754a",
    "sourceUrl": "assets/ships/release/parts/places/place_station_trade_hub.glb"
  },
  {
    "assetId": "sf.render.jump-ring",
    "expectedContentHash": "c6a8bc50f71c1cc6d1c62314e6dc3c2a4aaadffe0cfc2bf9fee443f2291afddd",
    "key": "jump-ring",
    "metadataUrl": "assets/ships/release/render-packages/jump-ring/render-package.json",
    "runtimeAssetId": "SF_PLACE_GATE_JUMP_RING",
    "slot": "place",
    "sourceSha256": "01ccf2695678cb42c5b086308b7bea6dc366b029b4efc9e12393a10e8b209ead",
    "sourceUrl": "assets/ships/release/parts/places/place_gate_jump_ring.glb"
  },
  {
    "assetId": "sf.render.debris-chunk",
    "expectedContentHash": "7ba76a470abad7ae070584105f00dedd397d055c9657637a2a341a126a84b788",
    "key": "debris-chunk",
    "metadataUrl": "assets/ships/release/render-packages/debris-chunk/render-package.json",
    "runtimeAssetId": "place_debris_chunk",
    "slot": "place",
    "sourceSha256": "016e7a103a40b7ba3183d56fcef1362aea0c3723274b49d4ab2439ae51151a26",
    "sourceUrl": "assets/ships/release/parts/places/place_debris_chunk.glb"
  },
  {
    "assetId": "sf.render.dead-hulk",
    "expectedContentHash": "c7a5c06aaf1c21550e35de216d6ec654a473580ba3fedcfe14537b10d4ade1f7",
    "key": "dead-hulk",
    "metadataUrl": "assets/ships/release/render-packages/dead-hulk/render-package.json",
    "runtimeAssetId": "place_dead_hulk",
    "slot": "place",
    "sourceSha256": "c2c421c6ff4b87cb92566560e080190f77ac14336b0fc43045bd2be9d02ba185",
    "sourceUrl": "assets/ships/release/parts/places/place_dead_hulk.glb"
  },
  {
    "assetId": "sf.render.dock-interior",
    "expectedContentHash": "8850775c293c07b26ae7acf4a0d3568dc97102726b4896fece8accc93e03d9d8",
    "key": "dock-interior",
    "metadataUrl": "assets/ships/release/render-packages/dock-interior/render-package.json",
    "runtimeAssetId": "place_dock_interior",
    "slot": "place",
    "sourceSha256": "926cb7784e61f8adcc533945c4c254f8d7e0af14efeff465bfd8b2caa6f0a6de",
    "sourceUrl": "assets/ships/release/parts/places/place_dock_interior.glb"
  },
  {
    "assetId": "sf.render.wasp",
    "expectedContentHash": "0d8d2ab9ce5dd88fd4a67c0f929af993cce06d441c7458694ad9dc882dde633d",
    "key": "wasp",
    "metadataUrl": "assets/ships/release/render-packages/wasp/render-package.json",
    "runtimeAssetId": "SF_WASP_PRODUCTION_V1",
    "slot": "hull",
    "sourceSha256": "a23354195d95d57bdc2d2e8e32d5cd4fcc1f6c05d570033a7c1849ac87408dde",
    "sourceUrl": "assets/ships/release/parts/wholeships/wasp_production_v1.glb"
  }
];

export const RENDER_PACKAGE_PILOTS = Object.freeze(PILOTS.map((entry) => Object.freeze(entry)));

const BY_SOURCE_URL = new Map(RENDER_PACKAGE_PILOTS.map((entry) => [entry.sourceUrl, entry]));
const BY_ASSET_ID = new Map(RENDER_PACKAGE_PILOTS.map((entry) => [entry.assetId, entry]));

export function renderPackagePilotForSourceUrl(url) {
  const clean = String(url || '').replace(/\\/g, '/').split(/[?#]/, 1)[0].replace(/^\.\//, '');
  return BY_SOURCE_URL.get(clean) || null;
}

export function renderPackagePilotForAssetId(assetId) {
  return BY_ASSET_ID.get(String(assetId || '')) || null;
}
