// Generated by scripts/build-render-package-pilots.mjs. Do not edit by hand.
const PILOTS = [
  {
    "assetId": "sf.render.kestrel",
    "expectedContentHash": "ac171b1c76119947da7212fb4ca023a9f2902ffb8885510b8ec9530565611a0f",
    "key": "kestrel",
    "metadataUrl": "assets/ships/release/render-packages/kestrel/render-package.json",
    "runtimeAssetId": "SF_K0_KESTREL_BORROWED_TIME_V4",
    "slot": "hull",
    "sourceSha256": "24f1cb48dcf8c1e4a8e35b09c8f0f76ea92277b04fa0127d102927e10d068aae",
    "sourceUrl": "assets/ships/release/parts/wholeships/kestrel.glb"
  },
  {
    "assetId": "sf.render.ashline-dart",
    "expectedContentHash": "243a82705f976603c0bc12e3137549157171d97c6a6dd9599dcea7ed4c17ec3b",
    "key": "ashline-dart",
    "metadataUrl": "assets/ships/release/render-packages/ashline-dart/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_ASHLINE_DART",
    "slot": "hull",
    "sourceSha256": "a9129044a5e791efe59cbabfd3c2961642b79a9c1c9ee22e4d3eea22719cc0b7",
    "sourceUrl": "assets/ships/release/parts/wholeships/ashline_dart.glb"
  },
  {
    "assetId": "sf.render.ashline-lode",
    "expectedContentHash": "e141118b5dcd139ffcbf86375c412442ece1444fb93ac9dafe180dfe11f1193b",
    "key": "ashline-lode",
    "metadataUrl": "assets/ships/release/render-packages/ashline-lode/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_ASHLINE_LODE",
    "slot": "hull",
    "sourceSha256": "d1d30208913b7bc49e96dfc78dc5acc19b8ecfc191a4a5136853828181824656",
    "sourceUrl": "assets/ships/release/parts/wholeships/ashline_lode.glb"
  },
  {
    "assetId": "sf.render.ashline-rig",
    "expectedContentHash": "e31a3497ddb4a219983cdd2a8db8e65724ff8ee2ec943ef20582dbc231c16cd4",
    "key": "ashline-rig",
    "metadataUrl": "assets/ships/release/render-packages/ashline-rig/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_ASHLINE_RIG",
    "slot": "hull",
    "sourceSha256": "32ecc2bc92b351ff68186b1eca331149a14d200561d445309d6d9b1a322723c9",
    "sourceUrl": "assets/ships/release/parts/wholeships/ashline_rig.glb"
  },
  {
    "assetId": "sf.render.helios-lark",
    "expectedContentHash": "74f138261c0ccbef24f6c4112af080ad72b2bdba0c419b9f2c62149136043713",
    "key": "helios-lark",
    "metadataUrl": "assets/ships/release/render-packages/helios-lark/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_HELIOS_LARK",
    "slot": "hull",
    "sourceSha256": "5dfb6c2a2baaa4c8e92758f4e969d262ee668cbf22e5de73020df659e782a473",
    "sourceUrl": "assets/ships/release/parts/wholeships/helios_lark.glb"
  },
  {
    "assetId": "sf.render.helios-cradle",
    "expectedContentHash": "7f67a495ec0a7489250e24c6c301a85758f224363c761507a83e6df94668e4c3",
    "key": "helios-cradle",
    "metadataUrl": "assets/ships/release/render-packages/helios-cradle/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_HELIOS_CRADLE",
    "slot": "hull",
    "sourceSha256": "6f400dfd7caf7e18df1b0cb951e77ec2c8773a4cd8321243e4c259c840c778de",
    "sourceUrl": "assets/ships/release/parts/wholeships/helios_cradle.glb"
  },
  {
    "assetId": "sf.render.helios-span",
    "expectedContentHash": "76be052f0a00f7ad9f9410c1014fdda9552f5c729b7e0e94ac33baffc90b0a84",
    "key": "helios-span",
    "metadataUrl": "assets/ships/release/render-packages/helios-span/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_HELIOS_SPAN",
    "slot": "hull",
    "sourceSha256": "5fb2a62c79d3bc07777c5bf5ff9d2e26554e2bf3bfca051ba470d28adb6ed1b5",
    "sourceUrl": "assets/ships/release/parts/wholeships/helios_span.glb"
  },
  {
    "assetId": "sf.render.helios-trade-hub",
    "expectedContentHash": "95cc98ec70dbb04b3c34d7da0742b51813d4dea2d69a3f1cfe0ad341d49bf422",
    "key": "helios-trade-hub",
    "metadataUrl": "assets/ships/release/render-packages/helios-trade-hub/render-package.json",
    "runtimeAssetId": "SF_PLACE_STATION_TRADE_HUB",
    "slot": "place",
    "sourceSha256": "9540c8fa263359ff3b78302a9d48080af17cb903f47d43361814ba3666f0754a",
    "sourceUrl": "assets/ships/release/parts/places/place_station_trade_hub.glb"
  },
  {
    "assetId": "sf.render.ceres-refinery",
    "expectedContentHash": "650b9d4a94dca9371d25c4f21711f3bca1962cf90e354e4cf3fd88272200654c",
    "key": "ceres-refinery",
    "metadataUrl": "assets/ships/release/render-packages/ceres-refinery/render-package.json",
    "runtimeAssetId": "SF_PLACE_STATION_REFINERY",
    "slot": "place",
    "sourceSha256": "3b673f761f8e47c32ffa0563b933ad099380d2df75629dca927481cec4c8b7c0",
    "sourceUrl": "assets/ships/release/parts/places/place_station_refinery.glb"
  },
  {
    "assetId": "sf.render.jump-ring",
    "expectedContentHash": "10c3fac725f9838231d2639b37cea1928a013eee56d13842f2e1f1f95ac56047",
    "key": "jump-ring",
    "metadataUrl": "assets/ships/release/render-packages/jump-ring/render-package.json",
    "runtimeAssetId": "SF_PLACE_GATE_JUMP_RING",
    "slot": "place",
    "sourceSha256": "01ccf2695678cb42c5b086308b7bea6dc366b029b4efc9e12393a10e8b209ead",
    "sourceUrl": "assets/ships/release/parts/places/place_gate_jump_ring.glb"
  },
  {
    "assetId": "sf.render.helios-rock-a",
    "expectedContentHash": "2cd566a052ec73b89fbcc36cc22c31e10b44e21f597b499bb425bc40e40297fd",
    "key": "helios-rock-a",
    "metadataUrl": "assets/ships/release/render-packages/helios-rock-a/render-package.json",
    "runtimeAssetId": "SF_PLACE_HELIOS_ROCK_A",
    "slot": "place",
    "sourceSha256": "05d8ed9c2770df65d48c331a843a92052efe5bc86990932364d403fe7e1983a6",
    "sourceUrl": "assets/ships/release/parts/places/place_asteroid_rock_a.glb"
  },
  {
    "assetId": "sf.render.helios-rock-b",
    "expectedContentHash": "ffc68fa2437c3addc470a306f81720628019ab6b83b2a5a8ce7cc2b0958efd38",
    "key": "helios-rock-b",
    "metadataUrl": "assets/ships/release/render-packages/helios-rock-b/render-package.json",
    "runtimeAssetId": "SF_PLACE_HELIOS_ROCK_B",
    "slot": "place",
    "sourceSha256": "4d6dfecdbbd783a4694a19f03aa65300a3ea6bfd905785950b33f7eacaec114f",
    "sourceUrl": "assets/ships/release/parts/places/place_asteroid_rock_b.glb"
  },
  {
    "assetId": "sf.render.helios-rock-c",
    "expectedContentHash": "bfa88af2e1af12c99e4ce74c3e5f49f1583fd9c5b667cbb3c4076888465f2638",
    "key": "helios-rock-c",
    "metadataUrl": "assets/ships/release/render-packages/helios-rock-c/render-package.json",
    "runtimeAssetId": "SF_PLACE_HELIOS_ROCK_C",
    "slot": "place",
    "sourceSha256": "6e6d96ad5f75fb1908236204171462329fb491de5a14ee3ac0c29ba98fe42752",
    "sourceUrl": "assets/ships/release/parts/places/place_asteroid_rock_c.glb"
  },
  {
    "assetId": "sf.render.seamed-asteroid",
    "expectedContentHash": "ef8ae63de9599057f6c023149ec7d814056842053b1dcbad4d7c851a5bb46afb",
    "key": "seamed-asteroid",
    "metadataUrl": "assets/ships/release/render-packages/seamed-asteroid/render-package.json",
    "runtimeAssetId": "SF_PLACE_ASTEROID_SEAMED_GEOLOGY_V3",
    "slot": "place",
    "sourceSha256": "31cc9bae776abf00913e98bbc788b56a363cc6eaedcd4e1d5ae8a3cd624323d4",
    "sourceUrl": "assets/ships/release/parts/places/place_asteroid_seamed.glb"
  },
  {
    "assetId": "sf.render.conveyor-barge",
    "expectedContentHash": "6fd9ab85fdf69d06fc3b5cc540ffc8dd5c57ef2ae6023c657832fd125667677f",
    "key": "conveyor-barge",
    "metadataUrl": "assets/ships/release/render-packages/conveyor-barge/render-package.json",
    "runtimeAssetId": "SF_PLACE_CONVEYOR_BARGE",
    "slot": "place",
    "sourceSha256": "73e832008e376acadf54f74fd46cd258ca15286e2f65945ee75300b9b1d93683",
    "sourceUrl": "assets/ships/release/parts/places/place_conveyor_barge.glb"
  },
  {
    "assetId": "sf.render.claim-outpost-base",
    "expectedContentHash": "0046a8ce9e2b75597762baa721197438f368f856f269d08753971d16022b2327",
    "key": "claim-outpost-base",
    "metadataUrl": "assets/ships/release/render-packages/claim-outpost-base/render-package.json",
    "runtimeAssetId": "SF_PLACE_CLAIM_OUTPOST_BASE",
    "slot": "place",
    "sourceSha256": "6dab7e40086ddd6c0041977fac879069875d99a1aed52f2cb37962352658b4f0",
    "sourceUrl": "assets/ships/release/parts/places/place_claim_outpost_base.glb"
  },
  {
    "assetId": "sf.render.claim-outpost-refinery",
    "expectedContentHash": "8f951fce9c55e99ed61750d4984d614c6ec481ccbce704244b909e4f56c961d6",
    "key": "claim-outpost-refinery",
    "metadataUrl": "assets/ships/release/render-packages/claim-outpost-refinery/render-package.json",
    "runtimeAssetId": "SF_PLACE_CLAIM_OUTPOST_REFINERY",
    "slot": "place",
    "sourceSha256": "63802aa4f426a9031139e939e16f47d0e1e9fc37ea4c1f6c86bb914ec9cf82c7",
    "sourceUrl": "assets/ships/release/parts/places/place_claim_outpost_refinery.glb"
  },
  {
    "assetId": "sf.render.claim-outpost-relay",
    "expectedContentHash": "91a0693019c81d2796a70beb86827f2c0f4359033251dc0a63396d93c2ba654e",
    "key": "claim-outpost-relay",
    "metadataUrl": "assets/ships/release/render-packages/claim-outpost-relay/render-package.json",
    "runtimeAssetId": "SF_PLACE_CLAIM_OUTPOST_RELAY",
    "slot": "place",
    "sourceSha256": "85b8d74e7719203766937289b2ed5756294c4a9d48612c0432c6f036644167a8",
    "sourceUrl": "assets/ships/release/parts/places/place_claim_outpost_relay.glb"
  },
  {
    "assetId": "sf.render.nav-buoy",
    "expectedContentHash": "157459429f962a0cc5165610328710717e38ab0f3c9ef3442e80ab47a03a1a86",
    "key": "nav-buoy",
    "metadataUrl": "assets/ships/release/render-packages/nav-buoy/render-package.json",
    "runtimeAssetId": "SF_PLACE_HELIOS_NAV_SPIRE",
    "slot": "place",
    "sourceSha256": "5f7c43a66b4563d40e4a6df1fe35698c11489263f81746b55a86b7eabcc886e6",
    "sourceUrl": "assets/ships/release/parts/places/place_nav_buoy.glb"
  },
  {
    "assetId": "sf.render.lane-beacon",
    "expectedContentHash": "99e8fcee2c3cea04b845c2cfe21bf68a79f13472e3587315621a9cf4ae6f4d55",
    "key": "lane-beacon",
    "metadataUrl": "assets/ships/release/render-packages/lane-beacon/render-package.json",
    "runtimeAssetId": "SF_PLACE_HELIOS_SUPPORT_GANTRY",
    "slot": "place",
    "sourceSha256": "72bb0fabefed2b1b81c8cd4d70a3b3ef7abbad1f09010dde14c5f0fe15d1cbbe",
    "sourceUrl": "assets/ships/release/parts/places/place_lane_beacon.glb"
  },
  {
    "assetId": "sf.render.station-billboard",
    "expectedContentHash": "cceca8947c91dfe5e3b0468b2312f1f8e571ae0124525d1df8f22f626d5f8f58",
    "key": "station-billboard",
    "metadataUrl": "assets/ships/release/render-packages/station-billboard/render-package.json",
    "runtimeAssetId": "SF_PLACE_HELIOS_SUPPORT_DOCK_ARM",
    "slot": "place",
    "sourceSha256": "1a780be072b47a1ba38dbd977fdcfb16c5d1a7318213c1edc167cd5025b5d0c5",
    "sourceUrl": "assets/ships/release/parts/places/place_station_billboard.glb"
  },
  {
    "assetId": "sf.render.memorial-array",
    "expectedContentHash": "637aae4087cc6df430da7d0d1bd7bff29857d39e6f0ecb89133e21f5a3fecceb",
    "key": "memorial-array",
    "metadataUrl": "assets/ships/release/render-packages/memorial-array/render-package.json",
    "runtimeAssetId": "SF_PLACE_MEMORIAL_ARRAY",
    "slot": "place",
    "sourceSha256": "7bb0c7709a33e7b3972d5a32226037605792666b439c94b934dc04d15b238667",
    "sourceUrl": "assets/ships/release/parts/places/place_memorial_array.glb"
  },
  {
    "assetId": "sf.render.debris-chunk",
    "expectedContentHash": "2336f1e963009149c432da66d119e75432e4b97659ac80eedb9ef24ae5bf780a",
    "key": "debris-chunk",
    "metadataUrl": "assets/ships/release/render-packages/debris-chunk/render-package.json",
    "runtimeAssetId": "place_debris_chunk",
    "slot": "place",
    "sourceSha256": "016e7a103a40b7ba3183d56fcef1362aea0c3723274b49d4ab2439ae51151a26",
    "sourceUrl": "assets/ships/release/parts/places/place_debris_chunk.glb"
  },
  {
    "assetId": "sf.render.dead-hulk",
    "expectedContentHash": "4ae47f0ff48ab77b2d4838f6e33d793cd71619c1c40bc2f5b558b26aa0817211",
    "key": "dead-hulk",
    "metadataUrl": "assets/ships/release/render-packages/dead-hulk/render-package.json",
    "runtimeAssetId": "place_dead_hulk",
    "slot": "place",
    "sourceSha256": "c2c421c6ff4b87cb92566560e080190f77ac14336b0fc43045bd2be9d02ba185",
    "sourceUrl": "assets/ships/release/parts/places/place_dead_hulk.glb"
  },
  {
    "assetId": "sf.render.dock-interior",
    "expectedContentHash": "c7467c588a11ef7dcf285755713251f4700eb689474952a9cf34a5044205ab5f",
    "key": "dock-interior",
    "metadataUrl": "assets/ships/release/render-packages/dock-interior/render-package.json",
    "runtimeAssetId": "place_dock_interior",
    "slot": "place",
    "sourceSha256": "926cb7784e61f8adcc533945c4c254f8d7e0af14efeff465bfd8b2caa6f0a6de",
    "sourceUrl": "assets/ships/release/parts/places/place_dock_interior.glb"
  },
  {
    "assetId": "sf.render.wasp",
    "expectedContentHash": "3ead8efb8ca906cbf8ba73a87ccb41348de0d6956d7870d8665c0b887d5112bb",
    "key": "wasp",
    "metadataUrl": "assets/ships/release/render-packages/wasp/render-package.json",
    "runtimeAssetId": "SF_WASP_PRODUCTION_V1",
    "slot": "hull",
    "sourceSha256": "a23354195d95d57bdc2d2e8e32d5cd4fcc1f6c05d570033a7c1849ac87408dde",
    "sourceUrl": "assets/ships/release/parts/wholeships/wasp_production_v1.glb"
  },
  {
    "assetId": "sf.render.hull-starter",
    "expectedContentHash": "1a40aa2d472257a95bb7b347c83f72fd303ac699088d937ef8103d45f05104fd",
    "key": "hull-starter",
    "metadataUrl": "assets/ships/release/render-packages/hull-starter/render-package.json",
    "runtimeAssetId": "SF_HULL_STARTER",
    "slot": "hull",
    "sourceSha256": "f7db31ff57b878054d801c680048640eaea150870830584515ef77bc08b3527d",
    "sourceUrl": "assets/ships/release/parts/hulls/hull_starter.glb"
  },
  {
    "assetId": "sf.render.hull-fighter",
    "expectedContentHash": "78b87cb7257b7b710959e9910d2c430ff61701964f02965ac1947fae86d0fe9d",
    "key": "hull-fighter",
    "metadataUrl": "assets/ships/release/render-packages/hull-fighter/render-package.json",
    "runtimeAssetId": "SF_HULL_FIGHTER",
    "slot": "hull",
    "sourceSha256": "95efbc667817d45730f911db2346a9b66b49e3a39d535a7f0fcf8a338c32377d",
    "sourceUrl": "assets/ships/release/parts/hulls/hull_fighter.glb"
  },
  {
    "assetId": "sf.render.hull-miner",
    "expectedContentHash": "2278176a2ec324fe4cb290972ccc8f50826bc9abe5174fc0c2378a09216c4552",
    "key": "hull-miner",
    "metadataUrl": "assets/ships/release/render-packages/hull-miner/render-package.json",
    "runtimeAssetId": "SF_HULL_MINER",
    "slot": "hull",
    "sourceSha256": "b8903083c75a0aa498e930e02b61ff4bc9496ea3fe699ef55765a42753e58246",
    "sourceUrl": "assets/ships/release/parts/hulls/hull_miner.glb"
  },
  {
    "assetId": "sf.render.hull-freighter",
    "expectedContentHash": "d91079e30cbceb923744e416add8dfd7d45951cb2577bdf30a5a357b03b1951d",
    "key": "hull-freighter",
    "metadataUrl": "assets/ships/release/render-packages/hull-freighter/render-package.json",
    "runtimeAssetId": "SF_HULL_FREIGHTER",
    "slot": "hull",
    "sourceSha256": "c975f5171a4f730463a6e545b92d51f6cc18f54671f64f13d93bff5ead22f8ba",
    "sourceUrl": "assets/ships/release/parts/hulls/hull_freighter.glb"
  },
  {
    "assetId": "sf.render.hull-interceptor",
    "expectedContentHash": "20d0ccfdc55152846eadb13b226aa0e11a056004037ef57c963bd78fff6dfc76",
    "key": "hull-interceptor",
    "metadataUrl": "assets/ships/release/render-packages/hull-interceptor/render-package.json",
    "runtimeAssetId": "SF_HULL_INTERCEPTOR",
    "slot": "hull",
    "sourceSha256": "a81ebf01e2baaae4ce53e5ff6c129c9cc8e42d4f9630b689cf3385b63c4468a1",
    "sourceUrl": "assets/ships/release/parts/hulls/hull_interceptor.glb"
  },
  {
    "assetId": "sf.render.hull-corvette",
    "expectedContentHash": "ed6d5ab1e50b125a6126e21672bd6110a1bf8a077bd0d811a16d1f04c1325090",
    "key": "hull-corvette",
    "metadataUrl": "assets/ships/release/render-packages/hull-corvette/render-package.json",
    "runtimeAssetId": "SF_HULL_CORVETTE",
    "slot": "hull",
    "sourceSha256": "777e93999ca39317bac283f342fafc82fb2553646bb67512d2f3be5bbfee31fa",
    "sourceUrl": "assets/ships/release/parts/hulls/hull_corvette.glb"
  },
  {
    "assetId": "sf.render.hull-frigate",
    "expectedContentHash": "f05c9681484434d05e4b36aae81202d886eb161aed49342c62060d5aa744fabb",
    "key": "hull-frigate",
    "metadataUrl": "assets/ships/release/render-packages/hull-frigate/render-package.json",
    "runtimeAssetId": "SF_HULL_FRIGATE",
    "slot": "hull",
    "sourceSha256": "b84c70c57c29477ae00ddbf6b888a90ba36a57c08c453029b4426aed9fab209a",
    "sourceUrl": "assets/ships/release/parts/hulls/hull_frigate.glb"
  },
  {
    "assetId": "sf.render.hull-capital",
    "expectedContentHash": "fb6e8dd5f14b65ded3b2a23fbed62877dd2fac4e1fc2ba7c3622894788d58d4b",
    "key": "hull-capital",
    "metadataUrl": "assets/ships/release/render-packages/hull-capital/render-package.json",
    "runtimeAssetId": "SF_HULL_CAPITAL",
    "slot": "hull",
    "sourceSha256": "0520c0e61697ea2f2cafeab45744865759eaa7f76f36a5ed4505f26154b8b24a",
    "sourceUrl": "assets/ships/release/parts/hulls/hull_capital.glb"
  },
  {
    "assetId": "sf.render.hull-multirole",
    "expectedContentHash": "6e2e4ce711d913c06e7278ffe904440f79d9b21e49feee8dd1866863e3d3e735",
    "key": "hull-multirole",
    "metadataUrl": "assets/ships/release/render-packages/hull-multirole/render-package.json",
    "runtimeAssetId": "SF_HULL_MULTIROLE",
    "slot": "hull",
    "sourceSha256": "d7cc7156177ad3a4b1b89d2d76c4a78604c791e16ec944a609bdf407db05ab06",
    "sourceUrl": "assets/ships/release/parts/hulls/hull_multirole.glb"
  },
  {
    "assetId": "sf.render.hull-gunship",
    "expectedContentHash": "62070c0854f4ac3a752aa5172ed7b4e7ee990568ed050f5936d039b32fc7f250",
    "key": "hull-gunship",
    "metadataUrl": "assets/ships/release/render-packages/hull-gunship/render-package.json",
    "runtimeAssetId": "SF_HULL_GUNSHIP",
    "slot": "hull",
    "sourceSha256": "9dcf83114eeddf5f45f5dcb32f50d970661a3bb3989d53ed9b62d6b8d66b42da",
    "sourceUrl": "assets/ships/release/parts/hulls/hull_gunship.glb"
  },
  {
    "assetId": "sf.render.cockpit-dome",
    "expectedContentHash": "edf2cb3e2e77efd8ea48d4bceb9a8e2598010a18ba801d5a1eb2e401f62441b6",
    "key": "cockpit-dome",
    "metadataUrl": "assets/ships/release/render-packages/cockpit-dome/render-package.json",
    "runtimeAssetId": "SF_COCKPIT_DOME",
    "slot": "cockpit",
    "sourceSha256": "e5b940e287a63b0bddf82cdf24b8c756f3c82846da65f71464cb4bf0cec3ebe6",
    "sourceUrl": "assets/ships/release/parts/cockpits/cockpit_dome.glb"
  },
  {
    "assetId": "sf.render.cockpit-slab",
    "expectedContentHash": "8daafe0924e61de44dc41228e38b0cda212e75aef9fd55c113b4c28a39f60187",
    "key": "cockpit-slab",
    "metadataUrl": "assets/ships/release/render-packages/cockpit-slab/render-package.json",
    "runtimeAssetId": "SF_COCKPIT_SLAB",
    "slot": "cockpit",
    "sourceSha256": "3dd3077f278426b07f812b527f7399d6947647aae32fd350ebbc321156577289",
    "sourceUrl": "assets/ships/release/parts/cockpits/cockpit_slab.glb"
  },
  {
    "assetId": "sf.render.cockpit-recessed",
    "expectedContentHash": "057db0f0f65e3bbfee4e9216ee9be626fd6c53f39431de241a6bab000f0272e5",
    "key": "cockpit-recessed",
    "metadataUrl": "assets/ships/release/render-packages/cockpit-recessed/render-package.json",
    "runtimeAssetId": "SF_COCKPIT_RECESSED",
    "slot": "cockpit",
    "sourceSha256": "ce597dddd3d0e370aec1921b40e592047e7eb57dca9e865f5e58332d8c0fb145",
    "sourceUrl": "assets/ships/release/parts/cockpits/cockpit_recessed.glb"
  },
  {
    "assetId": "sf.render.engine-ion-small",
    "expectedContentHash": "514ae4a99c2f54c84efd0532dbfa2b8657fa8fac04ff3e026f2580fd9977323c",
    "key": "engine-ion-small",
    "metadataUrl": "assets/ships/release/render-packages/engine-ion-small/render-package.json",
    "runtimeAssetId": "SF_ENGINE_ION_SMALL",
    "slot": "engine",
    "sourceSha256": "e753a614694fa0af32480555c0ff34537a9b490aba13f281ebcab29a4b992141",
    "sourceUrl": "assets/ships/release/parts/engines/engine_ion_small.glb"
  },
  {
    "assetId": "sf.render.engine-ion-twin",
    "expectedContentHash": "92635a0610b8981e737530afa6a866d96de1784cee5d2a05cc7db3e35efae5b5",
    "key": "engine-ion-twin",
    "metadataUrl": "assets/ships/release/render-packages/engine-ion-twin/render-package.json",
    "runtimeAssetId": "SF_ENGINE_ION_TWIN",
    "slot": "engine",
    "sourceSha256": "f37cd5456c5b93b999499001621a4e6ef50d24b9a02a4e486e2a129f41eec06e",
    "sourceUrl": "assets/ships/release/parts/engines/engine_ion_twin.glb"
  },
  {
    "assetId": "sf.render.engine-industrial",
    "expectedContentHash": "fc8b4701f33ab9ab5a3a4e82d93c51a531810866e0cae0d2098b3ce9bb16039c",
    "key": "engine-industrial",
    "metadataUrl": "assets/ships/release/render-packages/engine-industrial/render-package.json",
    "runtimeAssetId": "SF_ENGINE_INDUSTRIAL",
    "slot": "engine",
    "sourceSha256": "b3dff895895c7cb709010f90c5b0e6a7b34af2f58d47c503dc7f09c672b7b102",
    "sourceUrl": "assets/ships/release/parts/engines/engine_industrial.glb"
  },
  {
    "assetId": "sf.render.engine-resonator",
    "expectedContentHash": "1e2985200cf07b141df4118507684e18f3247a74dd1c85aa5ee7bd2dd277abdc",
    "key": "engine-resonator",
    "metadataUrl": "assets/ships/release/render-packages/engine-resonator/render-package.json",
    "runtimeAssetId": "SF_ENGINE_RESONATOR",
    "slot": "engine",
    "sourceSha256": "d6bcad63c151360f0ac61f44fd38a98b623d2dc493441d07002588817832e8cf",
    "sourceUrl": "assets/ships/release/parts/engines/engine_resonator.glb"
  },
  {
    "assetId": "sf.render.engine-vector",
    "expectedContentHash": "d6b72dcf49b8e8870f2a00306bcb4ef55d69116ed8d88bd07dfdadb490d740c5",
    "key": "engine-vector",
    "metadataUrl": "assets/ships/release/render-packages/engine-vector/render-package.json",
    "runtimeAssetId": "SF_ENGINE_VECTOR",
    "slot": "engine",
    "sourceSha256": "305395c2ecbe679697f1b6c58534bce75a2b12333e1c663b92c36db3575a3d68",
    "sourceUrl": "assets/ships/release/parts/engines/engine_vector.glb"
  },
  {
    "assetId": "sf.render.engine-plasma-ring",
    "expectedContentHash": "be17f7a39b00b02eeeccd123f1c8592e8449269ba6063f4c961cfcce2c1e290e",
    "key": "engine-plasma-ring",
    "metadataUrl": "assets/ships/release/render-packages/engine-plasma-ring/render-package.json",
    "runtimeAssetId": "SF_ENGINE_PLASMA_RING",
    "slot": "engine",
    "sourceSha256": "d95e8d93c4a80fe05d01aed7787f38c1870058d7bc6fedc0f120462656cd8633",
    "sourceUrl": "assets/ships/release/parts/engines/engine_plasma_ring.glb"
  },
  {
    "assetId": "sf.render.weapon-pulse-cannon",
    "expectedContentHash": "e07d4b7c3ce8cdc620c289d4356ef8203fe4d36e69e72e5c0a3287c78981629b",
    "key": "weapon-pulse-cannon",
    "metadataUrl": "assets/ships/release/render-packages/weapon-pulse-cannon/render-package.json",
    "runtimeAssetId": "SF_WEAPON_PULSE_CANNON",
    "slot": "weapon",
    "sourceSha256": "0d3f6f238019958c893ddd598bf63092d626274de063ac3b9ca2236421d47511",
    "sourceUrl": "assets/ships/release/parts/weapons/weapon_pulse_cannon.glb"
  },
  {
    "assetId": "sf.render.weapon-heavy-cannon",
    "expectedContentHash": "a842053263bfa1d7948961d224198d6d5838716afa860e2f708e4bf90fbcde45",
    "key": "weapon-heavy-cannon",
    "metadataUrl": "assets/ships/release/render-packages/weapon-heavy-cannon/render-package.json",
    "runtimeAssetId": "SF_WEAPON_HEAVY_CANNON",
    "slot": "weapon",
    "sourceSha256": "e9692901fd420427d03a17de0b818c77c3c417d3ea1c76fd5d4839ae07bff366",
    "sourceUrl": "assets/ships/release/parts/weapons/weapon_heavy_cannon.glb"
  },
  {
    "assetId": "sf.render.weapon-turret-dual",
    "expectedContentHash": "8aaf52a79450015f629557e1b0d53e0d789c38fbd202841c59b65da73fee10a0",
    "key": "weapon-turret-dual",
    "metadataUrl": "assets/ships/release/render-packages/weapon-turret-dual/render-package.json",
    "runtimeAssetId": "SF_WEAPON_TURRET_DUAL",
    "slot": "weapon",
    "sourceSha256": "decb67cccee3f9ab1b1517e51831025c774a1ff8229533f7e7afa40bbb65195a",
    "sourceUrl": "assets/ships/release/parts/weapons/weapon_turret_dual.glb"
  },
  {
    "assetId": "sf.render.weapon-lance",
    "expectedContentHash": "424dbbdabf37bbc748ff38bbe672bb8724a49f388cdcea05761345a549500c33",
    "key": "weapon-lance",
    "metadataUrl": "assets/ships/release/render-packages/weapon-lance/render-package.json",
    "runtimeAssetId": "SF_WEAPON_LANCE",
    "slot": "weapon",
    "sourceSha256": "ae616831b90679cb53db2c099cb255da645a2b5af1de1f51ff9557707dea985c",
    "sourceUrl": "assets/ships/release/parts/weapons/weapon_lance.glb"
  },
  {
    "assetId": "sf.render.weapon-railgun",
    "expectedContentHash": "ddfa8d591a96798bca6851921d28b112da438bb7009f91c4f9a34198867103f4",
    "key": "weapon-railgun",
    "metadataUrl": "assets/ships/release/render-packages/weapon-railgun/render-package.json",
    "runtimeAssetId": "SF_WEAPON_RAILGUN",
    "slot": "weapon",
    "sourceSha256": "a003c6efc15c56b5aa92d06d01ff98e7d6456a2141cd0defa0218c614b334179",
    "sourceUrl": "assets/ships/release/parts/weapons/weapon_railgun.glb"
  },
  {
    "assetId": "sf.render.fin-wedge",
    "expectedContentHash": "2ffda72a701035e3ca9104b2b43d214e5b59c0ebfc8a5a927bcea64b2439f9fc",
    "key": "fin-wedge",
    "metadataUrl": "assets/ships/release/render-packages/fin-wedge/render-package.json",
    "runtimeAssetId": "SF_FIN_WEDGE",
    "slot": "fin",
    "sourceSha256": "b916552d4b687d9c682ddba1890d0c5fe9ae5c596f17ae2190280955721a05ac",
    "sourceUrl": "assets/ships/release/parts/fins/fin_wedge.glb"
  },
  {
    "assetId": "sf.render.fin-radiator-grid",
    "expectedContentHash": "7cbbd1e5049e374f60764be2ca7efa6ee3e790d9094de0d21424e50471b45491",
    "key": "fin-radiator-grid",
    "metadataUrl": "assets/ships/release/render-packages/fin-radiator-grid/render-package.json",
    "runtimeAssetId": "SF_FIN_RADIATOR_GRID",
    "slot": "fin",
    "sourceSha256": "f36ed9ce2824338d92340621b911931e51d242a964bb5e052800b9c71ebb0270",
    "sourceUrl": "assets/ships/release/parts/fins/fin_radiator_grid.glb"
  },
  {
    "assetId": "sf.render.fin-swept-smuggler",
    "expectedContentHash": "b41fe9c5315a850ca4263ae041bcdb873c60e751fdbe4c66573bc8fac6fe18b3",
    "key": "fin-swept-smuggler",
    "metadataUrl": "assets/ships/release/render-packages/fin-swept-smuggler/render-package.json",
    "runtimeAssetId": "SF_PART_FIN_SWEPT_SMUGGLER",
    "slot": "fin",
    "sourceSha256": "3263b0ce4a315ef9734019e24db664d05bb7a34bd64788602ea4279eed399beb",
    "sourceUrl": "assets/ships/release/parts/fins/fin_swept_smuggler.glb"
  },
  {
    "assetId": "sf.render.fin-delta",
    "expectedContentHash": "9fcfa3e48e07f3be2a712d21a3f39fdc34eabb7133b312143863339489f78642",
    "key": "fin-delta",
    "metadataUrl": "assets/ships/release/render-packages/fin-delta/render-package.json",
    "runtimeAssetId": "SF_FIN_DELTA",
    "slot": "fin",
    "sourceSha256": "63bed8f39a6f3b54bb6504561e2991548da69b2a5f8c42156fe9cfaff07df464",
    "sourceUrl": "assets/ships/release/parts/fins/fin_delta.glb"
  },
  {
    "assetId": "sf.render.fin-stabilator",
    "expectedContentHash": "181ae2857b7078769d82abf8cbceca8ee6d713952092abb879411a5048381e3e",
    "key": "fin-stabilator",
    "metadataUrl": "assets/ships/release/render-packages/fin-stabilator/render-package.json",
    "runtimeAssetId": "SF_FIN_STABILATOR",
    "slot": "fin",
    "sourceSha256": "e14d30d573518463e0f084087cd827021a8113a00e4fc269b8b19617bbe20807",
    "sourceUrl": "assets/ships/release/parts/fins/fin_stabilator.glb"
  },
  {
    "assetId": "sf.render.greeble-vents",
    "expectedContentHash": "e369838da330a4b1a953494e382aca38a83d2d6ea89850ee51d1b8f793951332",
    "key": "greeble-vents",
    "metadataUrl": "assets/ships/release/render-packages/greeble-vents/render-package.json",
    "runtimeAssetId": "SF_PART_GREEBLE_VENTS",
    "slot": "greeble",
    "sourceSha256": "ffbd4bcab14bbcf81a18cd171cd0ffec2deda80b0c66ed148c3c135b085e5e89",
    "sourceUrl": "assets/ships/release/parts/greebles/greeble_vents.glb"
  },
  {
    "assetId": "sf.render.greeble-hatches",
    "expectedContentHash": "51eb279fe73a86e9a83b2dea1a7efb03dab2e28a83040bdd233bb3389253c2a5",
    "key": "greeble-hatches",
    "metadataUrl": "assets/ships/release/render-packages/greeble-hatches/render-package.json",
    "runtimeAssetId": "SF_GREEBLE_HATCHES",
    "slot": "greeble",
    "sourceSha256": "8c8686cd1cbdc8fafc6d166f643d5858a408ac1d2ec1f7391a1bc0049caaaaf9",
    "sourceUrl": "assets/ships/release/parts/greebles/greeble_hatches.glb"
  },
  {
    "assetId": "sf.render.greeble-pipes",
    "expectedContentHash": "779033d75f89d7b18ea25f5d0dae3a75f5b593fac3ec63ab2cdd9c8c776dbad1",
    "key": "greeble-pipes",
    "metadataUrl": "assets/ships/release/render-packages/greeble-pipes/render-package.json",
    "runtimeAssetId": "SF_GREEBLE_PIPES",
    "slot": "greeble",
    "sourceSha256": "014444ada089137b21b740ad0b3d55eddf3f5e5bafd016b6ba358baf272b9a0f",
    "sourceUrl": "assets/ships/release/parts/greebles/greeble_pipes.glb"
  },
  {
    "assetId": "sf.render.greeble-rcs",
    "expectedContentHash": "cee76f5e7c7dbb088295c7216f3862ea5ebbb68380bdcab6367eb92f8f2bf785",
    "key": "greeble-rcs",
    "metadataUrl": "assets/ships/release/render-packages/greeble-rcs/render-package.json",
    "runtimeAssetId": "SF_GREEBLE_RCS",
    "slot": "greeble",
    "sourceSha256": "8d081d9418e12b730e0ea982f43d66555b7db0194d2ff6021b4f690d12aebdb8",
    "sourceUrl": "assets/ships/release/parts/greebles/greeble_rcs.glb"
  },
  {
    "assetId": "sf.render.greeble-antennas",
    "expectedContentHash": "d5e3ce70c08a5b0a7d79af060198e739a771f0a750eee855964bf2af92a8f5cf",
    "key": "greeble-antennas",
    "metadataUrl": "assets/ships/release/render-packages/greeble-antennas/render-package.json",
    "runtimeAssetId": "SF_GREEBLE_ANTENNAS",
    "slot": "greeble",
    "sourceSha256": "d10d243145afc63f3fd3a3b741c7298be09f48fbb7e9108bedd8de844a57470b",
    "sourceUrl": "assets/ships/release/parts/greebles/greeble_antennas.glb"
  },
  {
    "assetId": "sf.render.greeble-nav-lights",
    "expectedContentHash": "8ff6d31e1b3edda01117a83ea7e7a6a30274ea68bd3e973a420bbde0d3d63227",
    "key": "greeble-nav-lights",
    "metadataUrl": "assets/ships/release/render-packages/greeble-nav-lights/render-package.json",
    "runtimeAssetId": "SF_GREEBLE_NAV_LIGHTS",
    "slot": "greeble",
    "sourceSha256": "3ae9b0fdf7b57ceeec123b7c96b1cd2cf0f8a955b21f8750e4815f7666207fd8",
    "sourceUrl": "assets/ships/release/parts/greebles/greeble_nav_lights.glb"
  },
  {
    "assetId": "sf.render.greeble-armor-plates",
    "expectedContentHash": "844878e2bc1a6f247bcb11a3b5c1bb419072cd0c15489c1a0f54be74023b2b39",
    "key": "greeble-armor-plates",
    "metadataUrl": "assets/ships/release/render-packages/greeble-armor-plates/render-package.json",
    "runtimeAssetId": "SF_GREEBLE_ARMOR_PLATES",
    "slot": "greeble",
    "sourceSha256": "eb7b61fbf18142ba4c3a14c3cc5d836faa998c2ac2f82f317f7167adaffafd16",
    "sourceUrl": "assets/ships/release/parts/greebles/greeble_armor_plates.glb"
  },
  {
    "assetId": "sf.render.skid-trio",
    "expectedContentHash": "9bcc7ffd928964754cf129243aeceeb7b4262e5714473370d933f7e7673994b2",
    "key": "skid-trio",
    "metadataUrl": "assets/ships/release/render-packages/skid-trio/render-package.json",
    "runtimeAssetId": "SF_SKID_TRIO",
    "slot": "gear",
    "sourceSha256": "cdfa7612fa6587878f43f98bfbfbfce9e82dca46371c8d5ff939985a60315d4d",
    "sourceUrl": "assets/ships/release/parts/gear/skid_trio.glb"
  },
  {
    "assetId": "sf.render.skid-quad",
    "expectedContentHash": "b48f93902f921e9658e27112149cf26a1af0607dbd29a1250c14f8118c4561d2",
    "key": "skid-quad",
    "metadataUrl": "assets/ships/release/render-packages/skid-quad/render-package.json",
    "runtimeAssetId": "SF_SKID_QUAD",
    "slot": "gear",
    "sourceSha256": "3185391b6028d87a30fc7a4697e4ba22fd75b8befd03d533cb70230dcab24c1e",
    "sourceUrl": "assets/ships/release/parts/gear/skid_quad.glb"
  },
  {
    "assetId": "sf.render.pod-utility",
    "expectedContentHash": "a89b076b34630cbf4bc6c2335a42732b0613dbaac712d5fbb6207ade22ac1df1",
    "key": "pod-utility",
    "metadataUrl": "assets/ships/release/render-packages/pod-utility/render-package.json",
    "runtimeAssetId": "SF_POD_UTILITY",
    "slot": "pod",
    "sourceSha256": "59ed68be9d459227dbb1f9bafcccbfa0064511f71b5628b58abcde837ccbbd9c",
    "sourceUrl": "assets/ships/release/parts/pods/pod_utility.glb"
  },
  {
    "assetId": "sf.render.pod-cargo-container",
    "expectedContentHash": "0b7f0e98fba3537f52086bc41674202cac382bd75e50c678089df7e9b0457128",
    "key": "pod-cargo-container",
    "metadataUrl": "assets/ships/release/render-packages/pod-cargo-container/render-package.json",
    "runtimeAssetId": "SF_POD_CARGO_CONTAINER",
    "slot": "pod",
    "sourceSha256": "fd5b538629d17a9191a147be1a3ef6222d6fb890565f5cf4d11722c7ece0d5fa",
    "sourceUrl": "assets/ships/release/parts/pods/pod_cargo_container.glb"
  },
  {
    "assetId": "sf.render.pod-repair-patch",
    "expectedContentHash": "31b58f413cb3c7f1ce154b2f8094e0835e961d4404d1728cda40e00cafac322d",
    "key": "pod-repair-patch",
    "metadataUrl": "assets/ships/release/render-packages/pod-repair-patch/render-package.json",
    "runtimeAssetId": "SF_POD_REPAIR_PATCH",
    "slot": "pod",
    "sourceSha256": "5c749c12efabff01c7668447cd418b0317f46e3cda0212aabd897687038e498d",
    "sourceUrl": "assets/ships/release/parts/pods/pod_repair_patch.glb"
  },
  {
    "assetId": "sf.render.mining-drone",
    "expectedContentHash": "e3470508629b9f64286612f90cfdf6dfb4651d368e09be87efff62538e3ebf11",
    "key": "mining-drone",
    "metadataUrl": "assets/ships/release/render-packages/mining-drone/render-package.json",
    "runtimeAssetId": "SF_PART_PLACE_MINING_DRONE",
    "slot": "place",
    "sourceSha256": "79cffc2f9e03eff1168eaa6d2896aa700d44f5af4399b03adee19f07ff185661",
    "sourceUrl": "assets/ships/release/parts/places/place_mining_drone.glb"
  },
  {
    "assetId": "sf.render.dock-interior-military",
    "expectedContentHash": "f3a0187bd5039d88b47e96ff7a1aecf69e7bf397089f2fb0c9e81fd7bc2dffb8",
    "key": "dock-interior-military",
    "metadataUrl": "assets/ships/release/render-packages/dock-interior-military/render-package.json",
    "runtimeAssetId": "SF_PLACE_DOCK_INTERIOR_MILITARY",
    "slot": "place",
    "sourceSha256": "e3c9838321fa637f2af06486ae45a58d1bdde3d06e10d59d50070e2469686fab",
    "sourceUrl": "assets/ships/release/parts/places/place_dock_interior_military.glb"
  },
  {
    "assetId": "sf.render.dock-interior-grit",
    "expectedContentHash": "671c6761c80e2f2332929b8db0e9a2d024037d7a72ea4e8ad89d42dd7d2f7553",
    "key": "dock-interior-grit",
    "metadataUrl": "assets/ships/release/render-packages/dock-interior-grit/render-package.json",
    "runtimeAssetId": "SF_PLACE_DOCK_INTERIOR_GRIT",
    "slot": "place",
    "sourceSha256": "2a2a6a5a1c2f170024ee635101eb6737866d3de3b71795ea25eec945f8b500a9",
    "sourceUrl": "assets/ships/release/parts/places/place_dock_interior_grit.glb"
  },
  {
    "assetId": "sf.render.blackmarket",
    "expectedContentHash": "d44d3ccc2e0c93f3afe7b5f656b85035ae744dd7c1056c04724fd153953f5765",
    "key": "blackmarket",
    "metadataUrl": "assets/ships/release/render-packages/blackmarket/render-package.json",
    "runtimeAssetId": "SF_PLACE_STATION_BLACKMARKET",
    "slot": "place",
    "sourceSha256": "18b91187afbbaf3a01149bb079ee646a95c519478726d621d8e149f761c44e9f",
    "sourceUrl": "assets/ships/release/parts/places/place_station_blackmarket.glb"
  },
  {
    "assetId": "sf.render.mining",
    "expectedContentHash": "f975476b7f182e4976d7893a432e1557e8c94e8d58e1e5789cabead574a5a529",
    "key": "mining",
    "metadataUrl": "assets/ships/release/render-packages/mining/render-package.json",
    "runtimeAssetId": "SF_PLACE_STATION_MINING",
    "slot": "place",
    "sourceSha256": "b14c82ec6add74c525def05ca57e081805f3f4a09f8773ab662847ad41314b3a",
    "sourceUrl": "assets/ships/release/parts/places/place_station_mining.glb"
  },
  {
    "assetId": "sf.render.fab",
    "expectedContentHash": "fff6d2bb36c00e8c4aa41770e6d1d2ec43f33cdba7a76f943d0344ae80a875ad",
    "key": "fab",
    "metadataUrl": "assets/ships/release/render-packages/fab/render-package.json",
    "runtimeAssetId": "SF_PLACE_STATION_FAB",
    "slot": "place",
    "sourceSha256": "cbf20c022012ba956c90cf9fdb7710b59700623c6f1ebfa0b05186b1ec9ef0fa",
    "sourceUrl": "assets/ships/release/parts/places/place_station_fab.glb"
  },
  {
    "assetId": "sf.render.research",
    "expectedContentHash": "d1e684f3694ab4953c464fc39e281a25d0cfeb5d831178c15550081e903a3456",
    "key": "research",
    "metadataUrl": "assets/ships/release/render-packages/research/render-package.json",
    "runtimeAssetId": "SF_PLACE_STATION_RESEARCH",
    "slot": "place",
    "sourceSha256": "4d965bb6c2b801193a9b0ba187a65f868cfa57a08849f7932bd4fd8da552a346",
    "sourceUrl": "assets/ships/release/parts/places/place_station_research.glb"
  },
  {
    "assetId": "sf.render.outpost-bastion",
    "expectedContentHash": "2cdd7d849639e9ceafadd939c921cf6cdd80a966bc0ee7c15726a66c96deded1",
    "key": "outpost-bastion",
    "metadataUrl": "assets/ships/release/render-packages/outpost-bastion/render-package.json",
    "runtimeAssetId": "SF_PLACE_CLAIM_OUTPOST_BASTION",
    "slot": "place",
    "sourceSha256": "bfb256d3eb1a78564011d60abd50480c1af97ab4d2358d5db5d89e08c3097eff",
    "sourceUrl": "assets/ships/release/parts/places/place_claim_outpost_bastion.glb"
  },
  {
    "assetId": "sf.render.kestrel-lod1",
    "expectedContentHash": "c20cb54eef05459230a70d59686b049748af284a11eafe286b82242a65d70f4d",
    "key": "kestrel-lod1",
    "metadataUrl": "assets/ships/release/render-packages/kestrel-lod1/render-package.json",
    "runtimeAssetId": "SF_K0_KESTREL_BORROWED_TIME_V4",
    "slot": "hull",
    "sourceSha256": "c88807a05dd0ae0c1e7dad5ac64984b53301b14be921b9f19dc95c2e85362399",
    "sourceUrl": "assets/ships/release/parts/wholeships/kestrel_lod1.glb"
  },
  {
    "assetId": "sf.render.kestrel-lod2",
    "expectedContentHash": "c463d305f7705caa434914697cad5cc32d8b69e24e916ac48aa842dfbd6b8ebc",
    "key": "kestrel-lod2",
    "metadataUrl": "assets/ships/release/render-packages/kestrel-lod2/render-package.json",
    "runtimeAssetId": "SF_K0_KESTREL_BORROWED_TIME_V4",
    "slot": "hull",
    "sourceSha256": "4313192f1ee4da77c293d6ea84c2ddeaa10e3f91175c045f58a0c72f3e70824a",
    "sourceUrl": "assets/ships/release/parts/wholeships/kestrel_lod2.glb"
  },
  {
    "assetId": "sf.render.graffiti",
    "expectedContentHash": "61e77de3f7e64d2030b4295190b9906e5e6c6340e713f139e6b9b9f58a2e21c1",
    "key": "graffiti",
    "metadataUrl": "assets/ships/release/render-packages/graffiti/render-package.json",
    "runtimeAssetId": "SF_PLACE_ASTEROID_GRAFFITI_GEOLOGY_V3",
    "slot": "place",
    "sourceSha256": "2293ab300d2eb9fc07cd0c01e78e521f7ea44283e02b0d9635d0021f5e39e128",
    "sourceUrl": "assets/ships/release/parts/places/place_asteroid_graffiti.glb"
  },
  {
    "assetId": "sf.render.military",
    "expectedContentHash": "4d2afcea5337b773988c878c51aa69c55b5ffd6ff292127a781c3e0827a44b27",
    "key": "military",
    "metadataUrl": "assets/ships/release/render-packages/military/render-package.json",
    "runtimeAssetId": "SF_PLACE_STATION_MILITARY",
    "slot": "place",
    "sourceSha256": "a92f5c2b53262defcbfea27b22ec07ce8d7798f856dbd8e3fc9b12475ea67806",
    "sourceUrl": "assets/ships/release/parts/places/place_station_military.glb"
  },
  {
    "assetId": "sf.render.wreck-cathedral",
    "expectedContentHash": "c331be4665a30738e4efc292f7eccdd7edb992fbedc426400db6b32908515a1f",
    "key": "wreck-cathedral",
    "metadataUrl": "assets/ships/release/render-packages/wreck-cathedral/render-package.json",
    "runtimeAssetId": "SF_LANDMARK_PLACE_LANDMARK_WRECK_CATHEDRAL",
    "slot": "place",
    "sourceSha256": "32094bcd6df7671e9e2d93ae491a6aab33aa1ca9bd2a32cc3548cb7532eedcca",
    "sourceUrl": "assets/ships/release/parts/places/place_landmark_wreck_cathedral.glb"
  },
  {
    "assetId": "sf.render.weapon-gatling",
    "expectedContentHash": "883fd0d99a138bc4a4124a84c8db41eb507cc375d7321f230168d7554b5092cb",
    "key": "weapon-gatling",
    "metadataUrl": "assets/ships/release/render-packages/weapon-gatling/render-package.json",
    "runtimeAssetId": "SF_WEAPON_GATLING",
    "slot": "weapon",
    "sourceSha256": "56fe0abe8bf5251d81fb288fe29fb1dab0f0f2b64005c23722714d92fa45f679",
    "sourceUrl": "assets/ships/release/parts/weapons/weapon_gatling.glb"
  },
  {
    "assetId": "sf.render.ore-barge",
    "expectedContentHash": "8c612e293c24e929f5ee8e6d88c3610e0cc5160c7fdcd41d789979afb0e5aaaa",
    "key": "ore-barge",
    "metadataUrl": "assets/ships/release/render-packages/ore-barge/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_ORE_BARGE",
    "slot": "hull",
    "sourceSha256": "e5ae383ddb397a4d0a1d5dbb5e159f3ea6293404a1f2e5c52bbc363046febb9e",
    "sourceUrl": "assets/ships/release/parts/wholeships/ore_barge.glb"
  },
  {
    "assetId": "sf.render.repair-tender",
    "expectedContentHash": "1eac5e9f5c69c71588189f899518ac1312e3bf80a797cadc1056b5321b39ff80",
    "key": "repair-tender",
    "metadataUrl": "assets/ships/release/render-packages/repair-tender/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_REPAIR_TENDER",
    "slot": "hull",
    "sourceSha256": "ed9a05a89f397e353a8bbd6dca819665e628bdef10ddad22dccbe54d303673b6",
    "sourceUrl": "assets/ships/release/parts/wholeships/repair_tender.glb"
  },
  {
    "assetId": "sf.render.salvage-cutter",
    "expectedContentHash": "d5b35ecc9451f7a3df9debfcd2ec3b382390947895abc322239322ca914645b1",
    "key": "salvage-cutter",
    "metadataUrl": "assets/ships/release/render-packages/salvage-cutter/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_SALVAGE_CUTTER",
    "slot": "hull",
    "sourceSha256": "2424ab27e5dd6d28357089c235dca0ef9bd4801f00942cd1f2a55e9ff305acf8",
    "sourceUrl": "assets/ships/release/parts/wholeships/salvage_cutter.glb"
  },
  {
    "assetId": "sf.render.survey-pin",
    "expectedContentHash": "e2410872520c5a0c3ef51617dea3955daf4d1727c0337789ac8f3166283dde8c",
    "key": "survey-pin",
    "metadataUrl": "assets/ships/release/render-packages/survey-pin/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_SURVEY_PIN",
    "slot": "hull",
    "sourceSha256": "9493f4214591fd9d2e205aefc3535a070226951dbadb3d6d3ba4d37d398b825a",
    "sourceUrl": "assets/ships/release/parts/wholeships/survey_pin.glb"
  },
  {
    "assetId": "sf.render.ceres-bait-wreck",
    "expectedContentHash": "99245c27637fdb4d70300f297a234b63b5fd71de1ada630189e060c5e917c1f2",
    "key": "ceres-bait-wreck",
    "metadataUrl": "assets/ships/release/render-packages/ceres-bait-wreck/render-package.json",
    "runtimeAssetId": "SF_PLACE_CERES_BAIT_WRECK",
    "slot": "place",
    "sourceSha256": "90d2700c241c21723425d194aae79b7bdfdd6e8c57d3d075741a5232427e8d64",
    "sourceUrl": "assets/ships/release/parts/places/place_ceres_bait_wreck.glb"
  },
  {
    "assetId": "sf.render.ceres-grave-shard",
    "expectedContentHash": "16a5763ba3e487f56c7b31988a508370300016b485b6ca6a8bde0d416e027010",
    "key": "ceres-grave-shard",
    "metadataUrl": "assets/ships/release/render-packages/ceres-grave-shard/render-package.json",
    "runtimeAssetId": "SF_PLACE_CERES_GRAVE_SHARD",
    "slot": "place",
    "sourceSha256": "a69e3d2b1652067ea2eb91b500ca1128ad9a3cbaeef060661b6a7c7e45883764",
    "sourceUrl": "assets/ships/release/parts/places/place_ceres_grave_shard.glb"
  },
  {
    "assetId": "sf.render.cargo-pod-standard",
    "expectedContentHash": "a3e611474d2e0733c4dad0066f690479d7413e16aef096e61264964417f8fcba",
    "key": "cargo-pod-standard",
    "metadataUrl": "assets/ships/release/render-packages/cargo-pod-standard/render-package.json",
    "runtimeAssetId": "place_cargo_pod_standard",
    "slot": "place",
    "sourceSha256": "269c7b162bb0049afd29a31a63d825f73fbdab368fa116cac2635b8a43107c1e",
    "sourceUrl": "assets/ships/release/parts/places/place_cargo_pod_standard.glb"
  },
  {
    "assetId": "sf.render.container-rack",
    "expectedContentHash": "ce50b1220b0b2294103753452f512f7b67730a2e79f8d46cdd39708f086c00dc",
    "key": "container-rack",
    "metadataUrl": "assets/ships/release/render-packages/container-rack/render-package.json",
    "runtimeAssetId": "place_container_rack",
    "slot": "place",
    "sourceSha256": "d4e5f355f28c1eeb185beebc60d2e3870b0afdbb3cf6344e4ddbb3fe1aaa8c78",
    "sourceUrl": "assets/ships/release/parts/places/place_container_rack.glb"
  },
  {
    "assetId": "sf.render.freight-platform",
    "expectedContentHash": "81e377ca3cb9af85e1046952f5724dc6cb3cc4b3ddc6d265d580e0d51e16cbbb",
    "key": "freight-platform",
    "metadataUrl": "assets/ships/release/render-packages/freight-platform/render-package.json",
    "runtimeAssetId": "place_freight_platform",
    "slot": "place",
    "sourceSha256": "48e7175e6634edf35d568b2fe67d9cf9bb0af021bf9e3c5dddb217ede0d6753f",
    "sourceUrl": "assets/ships/release/parts/places/place_freight_platform.glb"
  },
  {
    "assetId": "sf.render.transfer-arm",
    "expectedContentHash": "ba5874fbde6deafa884c7f8fbf40930b3f3be85128905eea69477f724d15c81d",
    "key": "transfer-arm",
    "metadataUrl": "assets/ships/release/render-packages/transfer-arm/render-package.json",
    "runtimeAssetId": "place_transfer_arm",
    "slot": "place",
    "sourceSha256": "9d43793dab3a263d8a0ec806b178be1cb9ebf40c5c4c2c2b10a91e1a6124c172",
    "sourceUrl": "assets/ships/release/parts/places/place_transfer_arm.glb"
  },
  {
    "assetId": "sf.render.radiator-bank",
    "expectedContentHash": "2aa3b8d30d353b24519f75339f3ee977ff156236fd432f100f9fb10dea9a907a",
    "key": "radiator-bank",
    "metadataUrl": "assets/ships/release/render-packages/radiator-bank/render-package.json",
    "runtimeAssetId": "place_radiator_bank",
    "slot": "place",
    "sourceSha256": "168c66c7d861c8d4270e710d5f6b938694b026e27377e57066d4d2147052066f",
    "sourceUrl": "assets/ships/release/parts/places/place_radiator_bank.glb"
  },
  {
    "assetId": "sf.render.slurry-tank",
    "expectedContentHash": "bf522576bace7ae66d28e4fd14d162c399f2c2aac4fe71ae91cd557121e751e1",
    "key": "slurry-tank",
    "metadataUrl": "assets/ships/release/render-packages/slurry-tank/render-package.json",
    "runtimeAssetId": "place_slurry_tank",
    "slot": "place",
    "sourceSha256": "6225c23aea5d4717bfa04fe2c34c243677b99c3fa750cfa4bc4224d01b238b83",
    "sourceUrl": "assets/ships/release/parts/places/place_slurry_tank.glb"
  },
  {
    "assetId": "sf.render.drill-platform",
    "expectedContentHash": "2579d879f326cb439fcb89b624d7bee670d62bdef31f641dc8d372823e932232",
    "key": "drill-platform",
    "metadataUrl": "assets/ships/release/render-packages/drill-platform/render-package.json",
    "runtimeAssetId": "place_drill_platform",
    "slot": "place",
    "sourceSha256": "3c739e93aafd1362b4e8c6e6b53d1a8c91b094e48552000cfc47a9c7d154842e",
    "sourceUrl": "assets/ships/release/parts/places/place_drill_platform.glb"
  },
  {
    "assetId": "sf.render.conveyor-truss",
    "expectedContentHash": "52eb4dc709db3c236ee3e9bc2f3dc6090f90c17eabbd4235e6ed4d95a9d60343",
    "key": "conveyor-truss",
    "metadataUrl": "assets/ships/release/render-packages/conveyor-truss/render-package.json",
    "runtimeAssetId": "place_conveyor_truss",
    "slot": "place",
    "sourceSha256": "6cb26e191e038b95536d78debee4acabd326962c5a92b850d77368fa1d2703c2",
    "sourceUrl": "assets/ships/release/parts/places/place_conveyor_truss.glb"
  },
  {
    "assetId": "sf.render.extraction-mast",
    "expectedContentHash": "1e168a7138dc301276b806f0fe0963c3b6b3d0a8d4e668d07320ce484226700e",
    "key": "extraction-mast",
    "metadataUrl": "assets/ships/release/render-packages/extraction-mast/render-package.json",
    "runtimeAssetId": "place_extraction_mast",
    "slot": "place",
    "sourceSha256": "a3395afa0c21b7f34d2f2331cfd6b9bc5f86c98009c6ea1655a349b92fe2112c",
    "sourceUrl": "assets/ships/release/parts/places/place_extraction_mast.glb"
  },
  {
    "assetId": "sf.render.worklight-tower",
    "expectedContentHash": "be8dc7dfd111cdf85774e39dda0d188cff04a38f6be49e9d283e8dbad3f29ee8",
    "key": "worklight-tower",
    "metadataUrl": "assets/ships/release/render-packages/worklight-tower/render-package.json",
    "runtimeAssetId": "place_worklight_tower",
    "slot": "place",
    "sourceSha256": "01a32f25f2e10a1a19a359273570cacebcee59196652a2fddd9eafd4c99416d4",
    "sourceUrl": "assets/ships/release/parts/places/place_worklight_tower.glb"
  },
  {
    "assetId": "sf.render.transponder-gate",
    "expectedContentHash": "80266b4ab6f2975120e9bb527bb1f8b735ccfb746fe8e410551b4401306b37dc",
    "key": "transponder-gate",
    "metadataUrl": "assets/ships/release/render-packages/transponder-gate/render-package.json",
    "runtimeAssetId": "place_transponder_gate",
    "slot": "place",
    "sourceSha256": "44de3b452d1c83193418785ce3acf0f19cc3cf92bdff23b07cf60cf4ff43dcab",
    "sourceUrl": "assets/ships/release/parts/places/place_transponder_gate.glb"
  },
  {
    "assetId": "sf.render.interdiction-buoy",
    "expectedContentHash": "cdbc74c3530f7e5cc5f919013a3c445ac2e6bd08203fa5e39e520ef3d89278fe",
    "key": "interdiction-buoy",
    "metadataUrl": "assets/ships/release/render-packages/interdiction-buoy/render-package.json",
    "runtimeAssetId": "place_interdiction_buoy",
    "slot": "place",
    "sourceSha256": "c3bacf85983f5425f8f3532589de384d62035cb701a21d5e2bf95336dd30e7dc",
    "sourceUrl": "assets/ships/release/parts/places/place_interdiction_buoy.glb"
  },
  {
    "assetId": "sf.render.sensor-mast",
    "expectedContentHash": "65822cc6d87f646e22babc53e490595065be605a58cadb61acac99b767842327",
    "key": "sensor-mast",
    "metadataUrl": "assets/ships/release/render-packages/sensor-mast/render-package.json",
    "runtimeAssetId": "place_sensor_mast",
    "slot": "place",
    "sourceSha256": "fd64505fd9d7639cfe38400e61dec6c38edc956327bb040e65d367c4487957f3",
    "sourceUrl": "assets/ships/release/parts/places/place_sensor_mast.glb"
  },
  {
    "assetId": "sf.render.scrap-cage",
    "expectedContentHash": "8b5e893eb4038118a55f3c6a707850b630e80d3869eb999c29402149bee005c6",
    "key": "scrap-cage",
    "metadataUrl": "assets/ships/release/render-packages/scrap-cage/render-package.json",
    "runtimeAssetId": "place_scrap_cage",
    "slot": "place",
    "sourceSha256": "5c10a41e4fdaf6c64c5bbc870d0bd4670ef1ee4458a96b989a9394ebdc2c45dd",
    "sourceUrl": "assets/ships/release/parts/places/place_scrap_cage.glb"
  },
  {
    "assetId": "sf.render.improvised-dock",
    "expectedContentHash": "bb9e1160502d435e5ddcb00c0bf0479e4b7cd8e1e233cb7cb308b09fd4c5becf",
    "key": "improvised-dock",
    "metadataUrl": "assets/ships/release/render-packages/improvised-dock/render-package.json",
    "runtimeAssetId": "place_improvised_dock",
    "slot": "place",
    "sourceSha256": "1af62c2398004def62408fe7ec9c514f93a6606715f900923dfcdc8ccc7ef434",
    "sourceUrl": "assets/ships/release/parts/places/place_improvised_dock.glb"
  },
  {
    "assetId": "sf.render.maintenance-gantry",
    "expectedContentHash": "ab7015b76cf0db48f8098f2d94b5392b116506309b52834902c3c6e412644b18",
    "key": "maintenance-gantry",
    "metadataUrl": "assets/ships/release/render-packages/maintenance-gantry/render-package.json",
    "runtimeAssetId": "place_maintenance_gantry",
    "slot": "place",
    "sourceSha256": "8667acf58dd4e628591e5cacb53d6ceeb4c231283e179eff7efbbb4ed6adc8a8",
    "sourceUrl": "assets/ships/release/parts/places/place_maintenance_gantry.glb"
  },
  {
    "assetId": "sf.render.rescue-lifter",
    "expectedContentHash": "310cb9b22d28b6959759bba57e9b865274bf7069997cbe9d3ddd4c0163045c53",
    "key": "rescue-lifter",
    "metadataUrl": "assets/ships/release/render-packages/rescue-lifter/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_RESCUE_LIFTER",
    "slot": "hull",
    "sourceSha256": "9fc0f41bafcbc234facf5e45d3a4b719adf7645de3fb81d009b4f677e6b4e632",
    "sourceUrl": "assets/ships/release/parts/wholeships/rescue_lifter.glb"
  },
  {
    "assetId": "sf.render.volatiles-tanker",
    "expectedContentHash": "db3eb31e4d26412e781700858d89f2f5baf46315a929931375d2039d83c078d8",
    "key": "volatiles-tanker",
    "metadataUrl": "assets/ships/release/render-packages/volatiles-tanker/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_VOLATILES_TANKER",
    "slot": "hull",
    "sourceSha256": "7e7e905132c5f6c114eceed630f6e9c14d32610e374f56413b559b168bc32a29",
    "sourceUrl": "assets/ships/release/parts/wholeships/volatiles_tanker.glb"
  },
  {
    "assetId": "sf.render.prospector-skiff",
    "expectedContentHash": "3bac054da1340a3625e85db44f4246352234d43dea4ce4e1a03dd6ebc0fde39c",
    "key": "prospector-skiff",
    "metadataUrl": "assets/ships/release/render-packages/prospector-skiff/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_PROSPECTOR_SKIFF",
    "slot": "hull",
    "sourceSha256": "2ca6bd3fab779e660f53fb8f788122bb52a3cbb82391204e5cad66ad5d42468b",
    "sourceUrl": "assets/ships/release/parts/wholeships/prospector_skiff.glb"
  },
  {
    "assetId": "sf.render.scrap-sweeper",
    "expectedContentHash": "bddbf91bdce08dc88c9c713f9041f9208e49dda4dcaf168c8b64f716d74e424e",
    "key": "scrap-sweeper",
    "metadataUrl": "assets/ships/release/render-packages/scrap-sweeper/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_SCRAP_SWEEPER",
    "slot": "hull",
    "sourceSha256": "717833e1250ed6950846c32366a06267b7b2c64b84244abfd409899884a6f51b",
    "sourceUrl": "assets/ships/release/parts/wholeships/scrap_sweeper.glb"
  },
  {
    "assetId": "sf.render.yard-tug",
    "expectedContentHash": "ccbbf30923daa5fb92b8c876eec0cbf6b578907b4585f38346f0ee9539dd75fc",
    "key": "yard-tug",
    "metadataUrl": "assets/ships/release/render-packages/yard-tug/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_YARD_TUG",
    "slot": "hull",
    "sourceSha256": "3eb9d11172a6ba04a017d8ddc9bbf1ff35f37dcc293a9dfd865783afb8893f45",
    "sourceUrl": "assets/ships/release/parts/wholeships/yard_tug.glb"
  },
  {
    "assetId": "sf.render.inspection-cutter",
    "expectedContentHash": "16f940b1d5c25e20e95c2e6918cdaed8822297ae14d4197ac47487da158f1ae0",
    "key": "inspection-cutter",
    "metadataUrl": "assets/ships/release/render-packages/inspection-cutter/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_INSPECTION_CUTTER",
    "slot": "hull",
    "sourceSha256": "509cb3660deee8ad8c649d86e34fd83d3c89e7b93f4f1a51d46a688d610622aa",
    "sourceUrl": "assets/ships/release/parts/wholeships/inspection_cutter.glb"
  },
  {
    "assetId": "sf.render.apron-shuttle",
    "expectedContentHash": "38b3189edf0044466e90a4fb44c972e7916eeed29d020d9d7879907dd470cd86",
    "key": "apron-shuttle",
    "metadataUrl": "assets/ships/release/render-packages/apron-shuttle/render-package.json",
    "runtimeAssetId": "SF_WHOLESHIP_APRON_SHUTTLE",
    "slot": "hull",
    "sourceSha256": "cb770e46a9115973b43f699b08d843de024fcfb5bfa8291ae91e94499e84c5a2",
    "sourceUrl": "assets/ships/release/parts/wholeships/apron_shuttle.glb"
  }
];

export const RENDER_PACKAGE_PILOTS = Object.freeze(PILOTS.map((entry) => Object.freeze(entry)));

const BY_SOURCE_URL = new Map(RENDER_PACKAGE_PILOTS.map((entry) => [entry.sourceUrl, entry]));
const BY_ASSET_ID = new Map(RENDER_PACKAGE_PILOTS.map((entry) => [entry.assetId, entry]));

export function renderPackagePilotForSourceUrl(url) {
  const clean = String(url || '').replace(/\\/g, '/').split(/[?#]/, 1)[0].replace(/^\.\//, '');
  return BY_SOURCE_URL.get(clean) || null;
}

export function renderPackagePilotForAssetId(assetId) {
  return BY_ASSET_ID.get(String(assetId || '')) || null;
}
