// LIVE TITLE stage content (build_map.md §25 "Zero to hero", Phase 5.2).
//
// Plays the baked deterministic Crucible tape (src/sim/titleAttractTapeData.js —
// generated by scripts/bake-title-attract.mjs) inside the uiStage's own THREE.Scene.
// This is a *player*: it reads poses out of the tape and moves meshes. It never steps
// a simulation and never writes game state — the replay the visitor watches is the
// exact fight the seeded sim produced at bake time.
//
// Scene structure (all sim XZ → stage XZ, y = 0):
//   stageRoot (visible after prepare)
//     ├─ prototypes  — one normalized GLB group per roster visual, visible=false forever
//     ├─ fleet       — live ship instances + short-lived wrecks, spawned/posed from tape
//     ├─ bolts       — InstancedMesh: every straight round AND every guided round
//     └─ flashes     — InstancedMesh: impact pops and kill bursts (real geometry, additive)
//
// Failure contract: this module throws only from buildTitleAttractStage's async load;
// uiStage then keeps the authored plate (status 'unavailable'). Per-ship failures degrade
// to "that hull is missing" — the fight still plays with whoever loaded.

import * as THREE from 'three';
import { wholeShipVisualForEntity } from './partsLibrary.js';
import { decodeTape } from '../sim/titleAttractTape.js';
import { TITLE_ATTRACT_TAPE } from '../sim/titleAttractTapeData.js';

/** Sim wu → stage units. The ~460 wu arena becomes ~160 stage units across. */
const SCALE = 0.35;
/** Hull reads bigger than its collision disc; attract distance makes it smaller again. */
const SHIP_VISUAL_BOOST = 1.35;
/** Wreck drift time after a kill (seconds of stage time). */
const WRECK_SECONDS = 2.4;
/** Impact / kill flash duration. */
const FLASH_SECONDS = 0.5;
/** Instanced pool sizes — sized from the bake's real peaks, not guessed per frame. */
const MAX_BOLTS = 512;
const MAX_FLASHES = 256;
/** Camera: slow orbit around the smoothed fight centroid, clamped to the arena. */
const CAM_ORBIT_RAD_S = 0.055;
const CAM_RADIUS = 150;
const CAM_HEIGHT = 96;
const CAM_CENTROID_CLAMP = 64;
const CAM_LERP = 1.6;

const TEAM_BOLT_COLORS = [0xbfd4ff, 0xffc27a, 0x8fc7ff];
const GUIDED_COLOR = 0xffe9c4;

const _pos = new THREE.Vector3();
const _quat = new THREE.Quaternion();
const _scl = new THREE.Vector3(1, 1, 1);
const _unit = new THREE.Vector3(1, 1, 1);
const _eul = new THREE.Euler();
const _mat = new THREE.Matrix4();
const _centroid = new THREE.Vector3();
const _camTarget = new THREE.Vector3();
const _color = new THREE.Color();
const ZERO_SCALE = new THREE.Matrix4().makeScale(0, 0, 0);

function wrapPi(a) {
  let v = a % (Math.PI * 2);
  if (v > Math.PI) v -= Math.PI * 2;
  else if (v < -Math.PI) v += Math.PI * 2;
  return v;
}

/**
 * Build the attract content for a live uiStage scene.
 * @param built  the uiStage's stage record (scene, camera, clock, renderer, residencyOwner)
 * @param io     { loadPart(file, slot) -> Promise<record|null> } — uiStage's loader so the
 *               same release/source path and residency rules apply to the fight's hulls.
 */
export async function buildTitleAttractStage(built, io) {
  const tape = decodeTape(TITLE_ATTRACT_TAPE); // throws on malformed tape → caller fails closed
  const { scene } = built;

  const stageRoot = new THREE.Group();
  stageRoot.name = 'UiStageAttract';
  stageRoot.scale.setScalar(SCALE);
  stageRoot.visible = false; // uiStage reveals it after the compile pass, like every root

  const prototypes = new THREE.Group();
  prototypes.name = 'UiStageAttractPrototypes';
  prototypes.visible = false;
  stageRoot.add(prototypes);
  const fleet = new THREE.Group();
  fleet.name = 'UiStageAttractFleet';
  stageRoot.add(fleet);

  // -- Ship visuals: one GLB blueprint per roster archetype the tape actually uses.
  const visualKeys = new Map(); // key -> {file, unitScale, proto}
  for (const ship of tape.ships) {
    const key = `${ship.visual || ''}|${ship.silhouette || ''}`;
    if (visualKeys.has(key)) continue;
    visualKeys.set(key, null);
    let selection = null;
    try {
      selection = wholeShipVisualForEntity({
        type: 'ship', team: ship.team,
        data: { lootTableId: ship.visual, silhouette: ship.silhouette },
      });
    } catch (error) {
      console.warn('[titleAttract] visual lookup failed for', key, error);
    }
    const file = selection && selection.file;
    if (!file) continue;
    const record = await io.loadPart(file, 'hull');
    if (!record) continue;
    const proto = new THREE.Group();
    let span = 0;
    for (const primitive of record.primitives) {
      const mesh = new THREE.Mesh(primitive.geometry, primitive.material);
      mesh.name = primitive.name;
      primitive.matrix.decompose(mesh.position, mesh.quaternion, mesh.scale);
      proto.add(mesh);
    }
    proto.updateWorldMatrix(true, true);
    const box = new THREE.Box3().setFromObject(proto);
    if (!box.isEmpty()) {
      const size = new THREE.Vector3();
      box.getSize(size);
      span = Math.max(size.x, size.y, size.z);
      // Recentre so poses are the hull's centre, like the live track expects.
      const centre = new THREE.Vector3();
      box.getCenter(centre);
      for (const mesh of proto.children) mesh.position.sub(centre);
    }
    prototypes.add(proto);
    visualKeys.set(key, { proto, unitScale: span > 0 ? 1 / span : 0 });
  }
  const ready = [...visualKeys.values()].some((v) => v && v.unitScale > 0);

  // -- Bolt pool: stretched boxes, team-tinted per instance. Real lit-adjacent geometry —
  //    a basic material keeps them self-lit at tracer brightness without a sprite.
  const boltGeometry = new THREE.BoxGeometry(5.4, 0.55, 0.55);
  const boltMaterial = new THREE.MeshBasicMaterial({ color: 0xffffff, toneMapped: false });
  const bolts = new THREE.InstancedMesh(boltGeometry, boltMaterial, MAX_BOLTS);
  bolts.name = 'UiStageAttractBolts';
  bolts.count = 0;
  bolts.frustumCulled = false;
  bolts.instanceMatrix.setUsage(THREE.DynamicDrawUsage);
  for (let i = 0; i < MAX_BOLTS; i++) bolts.setColorAt(i, _color.setHex(0xffffff));
  markOwned(bolts);
  stageRoot.add(bolts);

  // -- Flash pool: icosahedron pops that grow and shrink — an honest mesh, not a card.
  const flashGeometry = new THREE.IcosahedronGeometry(1, 1);
  const flashMaterial = new THREE.MeshBasicMaterial({
    color: 0xffd9a8, transparent: true, opacity: 0.9,
    blending: THREE.AdditiveBlending, depthWrite: false, toneMapped: false,
  });
  const flashes = new THREE.InstancedMesh(flashGeometry, flashMaterial, MAX_FLASHES);
  flashes.name = 'UiStageAttractFlashes';
  flashes.count = 0;
  flashes.frustumCulled = false;
  flashes.instanceMatrix.setUsage(THREE.DynamicDrawUsage);
  markOwned(flashes);
  stageRoot.add(flashes);

  // -- Death events, precomputed once: ship kills (big) + every round's end (small).
  const events = [];
  for (const ship of tape.ships) {
    const n = ship.n | 0;
    if (n <= 0) continue;
    events.push({
      tick: ship.died,
      x: ship.x[n - 1] / tape.quant.pos,
      z: ship.z[n - 1] / tape.quant.pos,
      size: Math.max(2.5, ship.radius * 2.6),
    });
  }
  for (let i = 0; i < tape.shots.count; i++) {
    const b = tape.shots.b[i], d = tape.shots.d[i];
    const life = Math.max(0, (d - b) / tape.tickRate);
    events.push({
      tick: d,
      x: tape.shots.x[i] / tape.quant.pos + (tape.shots.vx[i] / tape.quant.vel) * life,
      z: tape.shots.z[i] / tape.quant.pos + (tape.shots.vz[i] / tape.quant.vel) * life,
      size: 1.4,
    });
  }
  for (const g of tape.guided) {
    const n = g.n | 0;
    if (n <= 0) continue;
    events.push({ tick: g.died, x: g.x[n - 1] / tape.quant.pos, z: g.z[n - 1] / tape.quant.pos, size: 2.0 });
  }
  events.sort((a, b) => a.tick - b.tick);

  // Per-track play state, parallel to tape.ships.
  const slots = tape.ships.map((ship) => ({
    ship,
    key: `${ship.visual || ''}|${ship.silhouette || ''}`,
    obj: null,
    phase: 0, // 0 waiting, 1 alive, 2 wreck, 3 done
    wreckT0: null,
    wreckSeeded: false,
    wreckX: 0, wreckZ: 0, wreckRot: 0,
  }));

  const activeFlashes = [];

  function spawnShip(slot) {
    const visual = visualKeys.get(slot.key);
    const proto = visual && visual.proto;
    if (!proto) return null;
    const obj = proto.clone(true);
    const diameter = Math.max(4, slot.ship.radius * 2 * SHIP_VISUAL_BOOST);
    obj.scale.setScalar((visual.unitScale || 0) * diameter);
    obj.visible = true;
    fleet.add(obj);
    return obj;
  }

  function sampleShip(ship, tickFloat, out) {
    const n = ship.n | 0;
    if (n <= 0) { out.x = 0; out.z = 0; out.rot = 0; return out; }
    const f = (tickFloat - ship.born) / tape.shipRate;
    const i0 = Math.max(0, Math.min(n - 1, Math.floor(f)));
    const i1 = Math.min(n - 1, i0 + 1);
    const a = Math.max(0, Math.min(1, f - i0));
    const q = tape.quant;
    out.x = (ship.x[i0] + (ship.x[i1] - ship.x[i0]) * a) / q.pos;
    out.z = (ship.z[i0] + (ship.z[i1] - ship.z[i0]) * a) / q.pos;
    const dr = wrapPi((ship.r[i1] - ship.r[i0]) / q.ang);
    out.rot = ship.r[i0] / q.ang + dr * a;
    out.rotRate = dr * (tape.tickRate / tape.shipRate); // rad/s — cosmetic bank source
    return out;
  }

  const pose = { x: 0, z: 0, rot: 0, rotRate: 0 };
  let eventCursor = 0;
  let prevTickFloat = 0;

  function pushFlash(x, z, size, clock) {
    activeFlashes.push({ t0: clock, x, z, size });
  }

  function update(built2, dt) {
    const clock = built2.clock;
    const tickFloat = ((clock % tape.seconds) + tape.seconds) % tape.seconds * tape.tickRate;

    // Fire the death events this window passed (handles the loop wrap as one window).
    const lo = prevTickFloat, hi = tickFloat;
    if (events.length) {
      if (hi >= lo) {
        while (eventCursor < events.length && events[eventCursor].tick <= hi) {
          const ev = events[eventCursor++];
          if (ev.tick > lo) pushFlash(ev.x, ev.z, ev.size, clock);
        }
      } else {
        // wrapped: consume (lo, end] then [0, hi]
        while (eventCursor < events.length && events[eventCursor].tick > lo) {
          const ev = events[eventCursor++];
          pushFlash(ev.x, ev.z, ev.size, clock);
        }
        if (eventCursor >= events.length) eventCursor = 0;
        while (eventCursor < events.length && events[eventCursor].tick <= hi) {
          pushFlash(events[eventCursor].x, events[eventCursor].z, events[eventCursor].size, clock);
          eventCursor++;
        }
      }
      if (eventCursor >= events.length) eventCursor = 0;
    }
    prevTickFloat = tickFloat;

    // -- Ships.
    _centroid.set(0, 0, 0);
    let centroidN = 0;
    for (const slot of slots) {
      const ship = slot.ship;
      const wreckEnd = ship.died + WRECK_SECONDS * tape.tickRate;
      if (tickFloat < ship.born || tickFloat >= wreckEnd) {
        if (slot.obj) {
          fleet.remove(slot.obj); slot.obj = null; slot.phase = 0;
          slot.wreckT0 = null; slot.wreckSeeded = false;
        }
        continue;
      }
      const dead = tickFloat >= ship.died;
      if (!slot.obj) {
        slot.obj = spawnShip(slot);
        slot.phase = dead ? 2 : 1;
        if (!slot.obj) { slot.phase = 3; continue; }
      }
      if (!dead) {
        sampleShip(ship, tickFloat, pose);
        slot.obj.position.set(pose.x, 0, pose.z);
        slot.obj.rotation.y = -pose.rot;
        // Cosmetic bank: lean into the turn. The tape carries no bank channel — this is
        // presentation polish on real yaw-rate data, not a simulated value.
        slot.obj.rotation.x = Math.max(-0.5, Math.min(0.5, -pose.rotRate * 0.32));
        slot.obj.rotation.z = 0;
        slot.wreckX = pose.x; slot.wreckZ = pose.z; slot.wreckRot = pose.rot;
        slot.wreckSeeded = true;
        _centroid.x += pose.x; _centroid.z += pose.z; centroidN++;
      } else {
        if (slot.phase !== 2 || slot.wreckT0 == null) {
          slot.phase = 2;
          slot.wreckT0 = clock;
          if (!slot.wreckSeeded) {
            // The instance spawned after the kill (a hitch skipped the alive window):
            // the drift starts at the recorded death pose, not the arena origin.
            sampleShip(ship, ship.died, pose);
            slot.wreckX = pose.x; slot.wreckZ = pose.z; slot.wreckRot = pose.rot;
            slot.wreckSeeded = true;
          }
        }
        const age = clock - slot.wreckT0;
        // The wreck keeps its recorded death velocity — a body conserving momentum,
        // not a despawning sprite.
        slot.obj.position.set(
          slot.wreckX + ship.vx * age, 0,
          slot.wreckZ + ship.vz * age,
        );
        slot.obj.rotation.y = -(slot.wreckRot + ship.wz * age);
        slot.obj.rotation.x += dt * 1.7; // dead tumbling — a body, not a pop
        slot.obj.rotation.z += dt * 0.9;
      }
    }

    // -- Bolts (straight rounds + guided tracks share the pool).
    let bi = 0;
    const q = tape.quant;
    for (let i = 0; i < tape.shots.count && bi < MAX_BOLTS; i++) {
      const b = tape.shots.b[i], d = tape.shots.d[i];
      if (tickFloat < b || tickFloat >= d) continue;
      const age = (tickFloat - b) / tape.tickRate;
      const vx = tape.shots.vx[i] / q.vel, vz = tape.shots.vz[i] / q.vel;
      _pos.set(tape.shots.x[i] / q.pos + vx * age, 0, tape.shots.z[i] / q.pos + vz * age);
      _eul.set(0, -Math.atan2(vz, vx), 0);
      _quat.setFromEuler(_eul);
      _mat.compose(_pos, _quat, _unit);
      bolts.setMatrixAt(bi, _mat);
      bolts.setColorAt(bi, _color.setHex(TEAM_BOLT_COLORS[tape.shots.t[i]] || 0xffe0b0));
      bi++;
    }
    for (const g of tape.guided) {
      if (bi >= MAX_BOLTS) break;
      if (tickFloat < g.born || tickFloat >= g.died) continue;
      const n = g.n | 0;
      const f = Math.max(0, Math.min(n - 1, tickFloat - g.born));
      const i0 = Math.floor(f), i1 = Math.min(n - 1, i0 + 1), a = f - i0;
      _pos.set(
        (g.x[i0] + (g.x[i1] - g.x[i0]) * a) / q.pos, 0,
        (g.z[i0] + (g.z[i1] - g.z[i0]) * a) / q.pos,
      );
      const dr = wrapPi((g.r[i1] - g.r[i0]) / q.ang);
      _eul.set(0, -(g.r[i0] / q.ang + dr * a), 0);
      _quat.setFromEuler(_eul);
      _mat.compose(_pos, _quat, _unit);
      bolts.setMatrixAt(bi, _mat);
      bolts.setColorAt(bi, _color.setHex(GUIDED_COLOR));
      bi++;
    }
    // Park the unused tail so a slow frame cannot leave ghosts standing.
    for (let i = bi; i < bolts.count; i++) bolts.setMatrixAt(i, ZERO_SCALE);
    bolts.count = bi;
    bolts.instanceMatrix.needsUpdate = true;
    if (bolts.instanceColor) bolts.instanceColor.needsUpdate = true;

    // -- Flashes.
    let fi = 0;
    for (let i = activeFlashes.length - 1; i >= 0; i--) {
      const fl = activeFlashes[i];
      const age = (clock - fl.t0) / FLASH_SECONDS;
      if (age >= 1) { activeFlashes.splice(i, 1); continue; }
      if (fi >= MAX_FLASHES) break;
      const s = fl.size * Math.sin(Math.min(1, Math.max(0, age)) * Math.PI) + 0.001;
      _pos.set(fl.x, 0, fl.z);
      _scl.setScalar(s);
      _mat.compose(_pos, _quat.identity(), _scl);
      flashes.setMatrixAt(fi++, _mat);
      _scl.set(1, 1, 1);
    }
    for (let i = fi; i < flashes.count; i++) flashes.setMatrixAt(i, ZERO_SCALE);
    flashes.count = fi;
    flashes.instanceMatrix.needsUpdate = true;

    // -- Camera: slow orbit around the smoothed fight centroid.
    if (centroidN > 0) _centroid.multiplyScalar(1 / centroidN); else _centroid.set(0, 0, 0);
    const len = Math.hypot(_centroid.x, _centroid.z);
    if (len > CAM_CENTROID_CLAMP) _centroid.multiplyScalar(CAM_CENTROID_CLAMP / len);
    if (!update._camInit) { _camTarget.copy(_centroid); update._camInit = true; }
    const k = 1 - Math.exp(-Math.max(0, dt) * CAM_LERP);
    _camTarget.lerp(_centroid, k);
    const az = clock * CAM_ORBIT_RAD_S;
    const height = CAM_HEIGHT + Math.sin(clock * 0.047) * 14;
    const radius = CAM_RADIUS + Math.sin(clock * 0.031) * 18;
    built2.camera.position.set(
      _camTarget.x + Math.cos(az) * radius,
      height,
      _camTarget.z + Math.sin(az) * radius,
    );
    built2.camera.lookAt(_camTarget.x, 0, _camTarget.z);
  }

  return {
    ready,
    roots: [stageRoot],
    /** uiStage drawStage hook — runs before the render call each presented frame. */
    update,
    controlsCamera: true,
    dispose() {
      for (const slot of slots) if (slot.obj) { fleet.remove(slot.obj); slot.obj = null; }
      activeFlashes.length = 0;
      slots.length = 0;
      events.length = 0;
      for (const v of visualKeys.values()) if (v && v.proto) prototypes.remove(v.proto);
      visualKeys.clear();
    },
  };
}

/** uiStage's release disposes every node flagged uiStageOwned — pools opt in. */
function markOwned(mesh) {
  mesh.userData.uiStageOwned = true;
}
