// Inference lines — new groups (FIGHT / ECON / STORY / LAW / MACH / PRO / TEACH), each ≥5 lines.
export const lines = [
  // ───────────────────────────── FIGHT ─────────────────────────────
  { key: 'fight-mine-layer-one-file', group: 'FIGHT', area: 'fight',
    change: 'The mine-layer jackal has one doctrine: the enemy row says what the override already makes it',
    paths: ['src/data/enemies.js', 'src/data/combatDefs.js'],
    done: 'A focused test proves `mine_layer_jackal` resolves `mine_layer_wake` from its own row and `ENEMY_DOCTRINE_OVERRIDES` no longer needs the entry; `test/mine-layer.test.mjs` stays green',
    doNot: 'Change the wake cue. Change the jackal\'s stats' },
  { key: 'fight-boss-defeated', group: 'FIGHT', area: 'fight',
    change: 'A defeated boss is announced by the run\'s own voice',
    paths: ['src/systems/world.js', 'src/systems/survivalAnnounce.js'],
    done: 'On seed 4242 `boss:defeated` produces one announcement line; a focused test pins one per defeat',
    doNot: 'Add an achievement here. Announce for NPC-vs-NPC kills' },
  { key: 'fight-run-modifiers', group: 'FIGHT', area: 'fight',
    change: 'Run modifier records are built by the module that authors and validates them',
    paths: ['src/data/runModifiers.js', 'src/systems/survivalDraft.js'],
    done: 'A focused test proves `survivalDraft.js` builds `run:modifierRecordRequested` payloads through `runModifierRecord` and `validateRunModifier` rejects a malformed one; today the module has zero importers',
    doNot: 'Change modifier verbs. Add a modifier' },
  { key: 'fight-modifier-chosen', group: 'FIGHT', area: 'fight',
    change: 'The run hears the modifier choice it listens for',
    paths: ['src/systems/survivalRun.js', 'src/systems/survivalDraft.js'],
    done: 'A focused test proves `run:modifierChosen` has a real emitter on the draft resolve path and the run\'s listener advances; today nothing emits it',
    doNot: 'Add a second listener. Change draft prices' },
  { key: 'fight-halo-verb', group: 'FIGHT', area: 'fight',
    change: 'The threat halo names the specialist\'s live verb window, not only its tier',
    paths: ['src/ui/threatHalo.js', 'src/ai/specialistPlans.js'],
    done: 'On seed 4242 a tether raider in its cut window sets the halo label from `nameThreatFromVisibleRead` and clears it after; a focused test pins the label lifecycle',
    doNot: 'Reveal a plan the player cannot see. Restyle the halo (ORRERY)' },
  { key: 'fight-counter-hint-adventure', group: 'FIGHT', area: 'fight',
    change: 'An enemy type\'s counter hint is spoken once in adventure on its first sighting',
    paths: ['src/systems/combat.js', 'src/systems/barkDirector.js'],
    done: 'On seed 4242 the first spawned `bruiser_brawler` in adventure produces one hint bark from its `counterHint` and the second produces none; a focused test pins once per type per profile',
    doNot: 'Speak hints in the Crucible (it has its own). Change hint text' },
  { key: 'fight-mine-cap', group: 'FIGHT', area: 'fight',
    change: 'Placing a mine past the cap is refused with the count, not swallowed',
    paths: ['src/systems/mines.js', 'src/audio/audioSystem.js'],
    done: 'On seed 4242 `mines:capReached` routes to the refusal voice with the cap in the caption; a focused test pins it',
    doNot: 'Raise the cap. Use the UI error blip' },
  { key: 'fight-mine-trigger', group: 'FIGHT', area: 'fight',
    change: 'A triggered mine snaps before it detonates, so the last half-second is readable',
    paths: ['src/systems/mines.js', 'src/render/vfx/actionEventRecipes.js'],
    done: 'On seed 4242 `mines:triggered` produces one trigger record before the detonation record; a focused test pins the order',
    doNot: 'Lengthen the fuse. Add particles to the detonation' },
  { key: 'fight-ward-target-halo', group: 'FIGHT', area: 'fight',
    change: 'The hull a warden is screening is marked while the ward holds',
    paths: ['src/ai/specialistCounterplay.js', 'src/ui/threatHalo.js'],
    done: 'On seed 4242 `wardScreenTarget` publishes the warded id and the halo marks it until the ward drops; a focused test pins add and clear',
    doNot: 'Mark from the warden\'s side only. Change ward math' },

  // ───────────────────────────── ECON ─────────────────────────────
  { key: 'econ-tiers-complete', group: 'ECON', area: 'longgame',
    change: 'Every commodity has a market tier, so refined and tech goods appear where the tier law says',
    paths: ['src/data/commodities.js', 'src/systems/economy.js'],
    done: 'A focused test proves 47/47 commodities carry `marketTier` and a seed-4242 tier-0 station lists no tier-3 good; today 26 are untiered',
    doNot: 'Change prices. Add commodities' },
  { key: 'econ-research-faucet', group: 'ECON', area: 'longgame',
    change: 'Research points have a repeatable faucet after the finite firsts run dry',
    paths: ['src/data/researchGrants.js', 'src/systems/missions.js'],
    done: 'On seed 4242 after 256 firsts a completed research contract still grants points through `RESEARCH_GRANTS`; a focused test pins the repeatable row and its cap per day',
    doNot: 'Grant points for kills. Remove the dedupe' },
  { key: 'econ-trade-failed', group: 'ECON', area: 'longgame',
    change: 'A failed trade refuses with its reason, not silently',
    paths: ['src/systems/economy.js', 'src/audio/audioSystem.js'],
    done: 'On seed 4242 `economy:tradeFailed` routes to the refusal voice with the reason word captioned; a focused test pins it',
    doNot: 'Count the failure toward station growth (NXI-105). Use the UI blip' },
  { key: 'econ-salvage-intake', group: 'ECON', area: 'longgame',
    change: 'A salvage intake that the market absorbed posts a one-line receipt',
    paths: ['src/systems/economy.js', 'src/ui/alerts.js'],
    done: 'On seed 4242 `economy:salvageIntakeApplied` raises one receipt line with the value; a focused test pins it',
    doNot: 'Add a receipts screen. Change intake pricing' },
  { key: 'econ-sink-receipt', group: 'ECON', area: 'longgame',
    change: 'A sink charge posts a receipt line naming the kind',
    paths: ['src/systems/economy.js', 'src/ui/alerts.js'],
    done: 'On seed 4242 `economy:sinkCharged` raises one line per charge with its `SESSION_SINK_KINDS` word; a focused test pins it',
    doNot: 'Post for zero-credit charges. Add a screen' },
  { key: 'econ-drone-ore-listener', group: 'ECON', area: 'longgame',
    change: 'Drone ore sales go through the economy\'s listener or the listener goes',
    paths: ['src/systems/economy.js', 'src/systems/automation.js'],
    done: 'A focused test proves `miningDrone:sellOre` has one real emitter on the drone unload path and the credit lands through the economy once; today the listener has no emitter',
    doNot: 'Let automation write credits. Sell twice' },

  // ───────────────────────────── STORY ─────────────────────────────
  { key: 'story-pull-news', group: 'STORY', area: 'longgame',
    change: 'A finished endgame pull is news, with the power hole it left named',
    paths: ['src/data/conflictReactions.js', 'src/systems/claims.js', 'src/ui/marketNews.js'],
    done: 'On seed 4242 a completed pull publishes one cited headline built from `endgamePullLine`; a focused test pins it',
    doNot: 'Publish uncited. Change pull power' },
  { key: 'story-rp-toast', group: 'STORY', area: 'longgame',
    change: 'Research points earned are announced with their source',
    paths: ['src/systems/missions.js', 'src/ui/alerts.js'],
    done: 'On seed 4242 `research:pointsChanged` raises one line naming the grant; a focused test pins it and none for a zero delta',
    doNot: 'Toast per point. Add a research screen' },
  { key: 'story-orrin-stages', group: 'STORY', area: 'longgame',
    change: 'Each stage of the Orrin witness case gets a comms line, not only the submission',
    paths: ['src/systems/world.js', 'src/ui/comms.js'],
    done: 'On seed 4242 each `orrinWitness:*` stage event produces one comms popup; a focused test pins one per stage',
    doNot: 'Add a dialogue choice. Change case rules' },
  { key: 'story-continuity-log', group: 'STORY', area: 'longgame',
    change: 'The post-ending continuity objective appears in the mission log',
    paths: ['src/systems/story.js', 'src/ui/screens/missionLog.js'],
    done: 'On seed 4242 `story:postEndingContinuity` adds one objective row to the log model; a focused test pins it',
    doNot: 'Add an ending. Re-present a resolved ending (NXI-186)' },
  { key: 'story-gates-revoked', group: 'STORY', area: 'longgame',
    change: 'When the Verge revokes the Vale gates, the map shows the gates closed and a line says why',
    paths: ['src/systems/story.js', 'src/ui/galaxyMap.js'],
    done: 'On seed 4242 `story:vergeValeGatesRevoked` closes the gate markers and posts one comms line; a focused test pins both',
    doNot: 'Change revocation rules. Add a faction screen' },
  { key: 'story-complication-rumor', group: 'STORY', area: 'world',
    change: 'A scheduled wreck complication is foreshadowed by a rumour line',
    paths: ['src/systems/uniqueWrecks.js', 'src/ui/marketNews.js'],
    done: 'On seed 4242 `uniqueWreck:complicationScheduled` publishes one cited rumour before the complication fires; a focused test pins order',
    doNot: 'Reveal the complication kind. Change schedule' },
  { key: 'story-hauler-origin-listeners', group: 'STORY', area: 'longgame',
    change: 'The hauler origin\'s accept and decline listeners are reachable or removed',
    paths: ['src/careers/origins/haulerOriginSystem.js'],
    done: 'A focused test proves the `career:hauler:accept`/`career:hauler:decline` listeners have real emitters on the origin prompt path, or the dead pair is deleted and the constant-named ladder path is the only door',
    doNot: 'Add a second origin prompt' },

  // ───────────────────────────── LAW ─────────────────────────────
  { key: 'law-customs-submit-ack', group: 'LAW', area: 'world',
    change: 'Submitting to a customs scan is acknowledged by the law',
    paths: ['src/ui/customsPrompt.js', 'src/systems/lawSecurity.js'],
    done: 'On seed 4242 `customs:submit` produces one lawful acknowledgement bark and records the compliance on the incident; a focused test pins both (today the emit has no listener)',
    doNot: 'Charge a second fine. Change scan odds' },
  { key: 'law-customs-break-cue', group: 'LAW', area: 'world',
    change: 'Breaking a customs scan has the flight cue its seam was authored for',
    paths: ['src/ui/customsPrompt.js', 'src/render/vfx/actionEventRecipes.js'],
    done: 'On seed 4242 `customs:breakScan` produces one recipe record on the player hull; a focused test pins it',
    doNot: 'Add heat here (the engine owns it). Add a banner' },
  { key: 'law-patrol-intervened', group: 'LAW', area: 'world',
    change: 'A patrol that took your fight says so',
    paths: ['src/systems/encounterDirector.js', 'src/systems/barkDirector.js'],
    done: 'On seed 4242 `encounter:patrolIntervened` produces one lawful bark; a focused test pins one per intervention',
    doNot: 'Bark from the pirates. Change intervention odds' },
  { key: 'law-custody-chain', group: 'LAW', area: 'world',
    change: 'A custody record appears in the footprint\'s provenance chains',
    paths: ['src/systems/custodyConsequences.js', 'src/systems/provenanceLedger.js'],
    done: 'On seed 4242 `custody:recorded` adds one chain entry with the closing verb; a focused test pins it and the cap',
    doNot: 'Exceed the chain cap. Add a screen' },
  { key: 'law-custody-ack', group: 'LAW', area: 'world',
    change: 'A station acknowledging custody says it at the berth',
    paths: ['src/systems/custodyConsequences.js', 'src/systems/barkDirector.js'],
    done: 'On seed 4242 `law:custodyAcknowledged` produces one bark in the lawful register; a focused test pins it',
    doNot: 'Bark twice for one transfer' },
  { key: 'law-launder-door', group: 'LAW', area: 'world',
    change: 'The laundering verb the market ledger describes is reachable',
    paths: ['src/systems/pirateDisguise.js', 'src/ui/station/screens/market.js'],
    done: 'A focused test proves `dock:launder` has a real emitter on the black-market path and the ledger entry is written once; today the listener has no emitter',
    doNot: 'Let the UI write the ledger. Launder legal cargo' },
  { key: 'law-bounty-cool-said', group: 'LAW', area: 'world',
    change: 'Paying a bounty says how much heat it bought off',
    paths: ['src/systems/heat.js', 'src/systems/barkDirector.js'],
    done: 'On seed 4242 `bounty:cleared` produces one line naming the cooled amount capped by `BOUNTY_PAID_COOL_MAX`; a focused test pins the number',
    doNot: 'Change the cooling rate. Let a payoff clear a massacre' },
  { key: 'law-unwitnessed', group: 'LAW', area: 'world',
    change: 'An incident nobody saw is recorded as unwitnessed in your footprint',
    paths: ['src/systems/lawSecurity.js', 'src/ui/screens/footprint.js'],
    done: 'On seed 4242 a kill with no witness inside 450 WU adds a footprint row marked unwitnessed and no warrant; a focused test pins both',
    doNot: 'Invent a witness (NXI-161). Change the witness radius' },
  { key: 'law-defense-ignore-verb', group: 'LAW', area: 'longgame',
    change: 'A claim defense can be ignored on purpose, which the claims owner already listens for',
    paths: ['src/systems/claims.js', 'src/ui/galaxyMap.js'],
    done: 'On seed 4242 the raid marker offers an ignore verb that emits `claim:defenseIgnore` and settles the defense as ignored; a focused test pins settlement (today the listener has no emitter)',
    doNot: 'Change raid odds. Add a claims panel' },

  // ───────────────────────────── MACH ─────────────────────────────
  { key: 'mach-memorial-manifest', group: 'MACH', area: 'machine',
    change: 'The memorial thief is a declared system or a declared sub-object, never an undeclared ticker',
    paths: ['src/runtime/authoritativeSystemManifest.js', 'src/systems/memorialThief.js'],
    done: 'A focused test proves `memorialThief.js` is either registered with a clock in the manifest or documented as owned by `uniqueWrecks.js` with no independent tick; the manifest identity payload is unchanged',
    doNot: 'Add a second ticker. Change thief behaviour' },
  { key: 'mach-chronicler-cap', group: 'MACH', area: 'machine',
    change: 'The chronicler has a hard cap on facts and prunes to it',
    paths: ['src/systems/chronicler.js', 'src/chronicler/ledger.js'],
    done: 'A focused test proves a named MAX constant bounds the fact ledger and a 10,000-fact seed-4242 soak stays under it with lineage intact',
    doNot: 'Drop cited facts before uncited ones. Change stages' },
  { key: 'mach-instance-prereserve', group: 'MACH', area: 'machine',
    change: 'Instance buffers reserve capacity on arrival so population spikes do not rebuild the matrix buffer',
    paths: ['src/render/renderer.js', 'src/render/asteroidInstancePool.js'],
    done: 'On seed 4242 Ceres arrival, `reserveAsteroidInstanceCapacity` is called with the roster count and zero power-of-two rebuilds occur in the first 600 presents; a focused test pins the count',
    doNot: 'Reserve above the residency budget. Change LOD' },
  { key: 'mach-software-gate-test', group: 'MACH', area: 'machine',
    change: 'The one automatic visual reduction (bloom off on software GL) is pinned to the software tier by a test',
    paths: ['src/render/renderer.js'],
    done: 'A focused test proves bloom is disabled only when `gpu.software === true`, never persisted, and the toast names the cause; an integrated-tier profile keeps bloom',
    doNot: 'Widen the gate. Persist the reduction' },
  { key: 'mach-world-to-screen-out', group: 'MACH', area: 'machine',
    change: 'Hot callers of the screen projection never allocate: the out parameter is required or checked',
    paths: ['src/render/renderer.js'],
    done: 'A focused test scans `src/ui` and `src/render` for projection calls without an `out` argument and finds zero; the HUD\'s 10 Hz numerics still pass their suites',
    doNot: 'Change projection math. Allocate a default per call' },
  { key: 'mach-spawn-deferred-witness', group: 'MACH', area: 'machine',
    change: 'Deferred or limited spawns are counted in the runtime witness',
    paths: ['src/systems/world.js', 'src/core/runtimeWitness.js'],
    done: 'A focused test proves `world:spawnLimited` and `world:criticalSpawnDeferred` increment two witness counters; a seed-4242 dense scene shows non-zero limited and zero critical',
    doNot: 'Raise spawn limits. Log per event' },
  { key: 'mach-geometry-pending', group: 'MACH', area: 'machine',
    change: 'The number of geometry roots still pending is one witness number, not a per-mesh flag',
    paths: ['src/render/renderer.js', 'src/core/runtimeWitness.js'],
    done: 'A focused test proves the geometry queue\'s stats publish `state.render.geometryPending` and the witness prints it; seed-4242 arrival shows it falling to 0',
    doNot: 'Add a per-frame walk to compute it' },
  { key: 'mach-byte-budget-policy', group: 'MACH', area: 'machine',
    change: 'The residency byte ceiling is a governor policy constant, not a caller-supplied null',
    paths: ['src/render/assetResidency.js', 'src/render/resourceGovernor.js', 'src/render/renderer.js'],
    done: 'A focused test proves `evictOldestSoftEntries` never runs unbounded: the governor supplies the ceiling from the one named constant and the renderer no longer passes null',
    doNot: 'Lower the ceiling. Evict pinned roles' },
  { key: 'mach-snapshot-bytes', group: 'MACH', area: 'machine',
    change: 'The packed presentation snapshot reports its bytes per frame in the witness',
    paths: ['src/render/snapshotFence.js', 'src/core/runtimeWitness.js'],
    done: 'A focused test proves the fence publishes bytes packed per present and the witness prints p50/p95; seed-4242 Ceres fight numbers are recorded in the test',
    doNot: 'Pack more. Start a worker' },

  // ───────────────────────────── PRO ─────────────────────────────
  { key: 'pro-stray-bak', group: 'PRO', area: 'professionalism',
    change: 'The stray nine-thousand-line backup file inside the systems folder is gone',
    paths: ['src/systems/missions.js.economy-pulse.bak'],
    done: 'The file is deleted and a focused test proves no `.bak` file exists under `src/`; the reachability check still passes',
    doNot: 'Move it elsewhere in the tree' },
  { key: 'pro-pseudo-dev-only', group: 'PRO', area: 'professionalism',
    change: 'The pseudo-locale is a dev tool, not a language a player can pick',
    paths: ['src/localization/gameLocalization.js', 'src/core/devMode.js'],
    done: 'A focused test proves `LANGUAGE_OPTIONS` omits `PSEUDO_LOCALE` when `IS_DEV` is false and includes it when true; `test/pq-166-01-pseudo-locale.test.mjs` stays green',
    doNot: 'Remove the pseudo-locale. Gate the five shipped locales' },
  { key: 'pro-locale-numbers', group: 'PRO', area: 'professionalism',
    change: 'Numbers format in the player\'s locale, not a pinned en-US',
    paths: ['src/combat/playerDefeat.js', 'src/ui/hud.js'],
    done: 'A focused test proves the death summary and the HUD tooltip format 12345 with the active locale\'s separators under de-DE and en-US',
    doNot: 'Change the numbers. Add a formatting dependency' },
  { key: 'pro-canvas-text', group: 'PRO', area: 'professionalism',
    change: 'Canvas-drawn labels on the range, radar and maps go through the localizer',
    paths: ['src/ui/screens/range.js', 'src/ui/radar.js', 'src/localization/domBridge.js'],
    done: 'A focused test proves the `fillText` sites in the three files resolve through a translate call and the pseudo-locale grows them by the 1.4 target',
    doNot: 'Translate numbers. Add a canvas font' },
  { key: 'pro-concat-copy', group: 'PRO', area: 'professionalism',
    change: 'Concatenated settings and pause strings become interpolated keys the localizer can translate',
    paths: ['src/ui/screens/settings.js', 'src/ui/screens/pause.js'],
    done: 'A focused test proves the In-use, Keeps, restart and Local Map strings resolve through `localizeText` with placeholders and render identically in en-US',
    doNot: 'Change copy. Restyle rows (ORRERY)' },
  { key: 'pro-autosave-exit', group: 'PRO', area: 'professionalism',
    change: 'Exiting to the menu forces an autosave first',
    paths: ['src/save/saveSystem.js'],
    done: 'A focused test proves an exit-to-menu request triggers a forced autosave that verifies before the screen changes, and never while dead or mid-jump',
    doNot: 'Autosave over an arena run onto a campaign slot. Skip the verify' },
  { key: 'pro-orbit-assist-profile', group: 'PRO', area: 'professionalism',
    change: 'The orbit assist strength survives a new game like the other accessibility keys',
    paths: ['src/save/saveSystem.js'],
    done: '`node scripts/check-settings-profile-persistence.mjs` passes with `orbitAssistStrength` added to `profileSettingsSnapshot`; a focused test pins the round-trip',
    doNot: 'Persist difficulty in the profile' },
  { key: 'pro-touch-scale', group: 'PRO', area: 'parity',
    change: 'The touch overlay has a size and layout option',
    paths: ['src/systems/touch.js', 'src/ui/screens/settings.js'],
    done: 'A focused test proves `controls.touch.scale` and `controls.touch.layout` are read by the overlay builder and persist; the Steam Deck viewport gate is unchanged',
    doNot: 'Change the trackpad lane. Add a fourth layout' },
  { key: 'pro-voice-dismiss', group: 'PRO', area: 'professionalism',
    change: 'The floor voice pill can be dismissed with a key, which the arbiter already listens for',
    paths: ['src/ui/voiceArbiter.js', 'src/ui/bindings.js'],
    done: 'A focused test proves a registered binding emits `voice:dismiss` and the arbiter clears the pill once; today the listener has no emitter',
    doNot: 'Dismiss critical squelch lines. Add a chord' },
  { key: 'pro-export-recovery-toast', group: 'PRO', area: 'professionalism',
    change: 'Exporting a save says that a recovery copy was written too',
    paths: ['src/save/saveSystem.js', 'src/ui/toasts.js'],
    done: 'A focused test proves `save:exportRecovery` raises one toast naming the slot; today the emit has no listener',
    doNot: 'Write a second export. Toast on every autosave' },
  { key: 'pro-entity-route', group: 'PRO', area: 'professionalism',
    change: 'The route verb on an entity link reaches the route follower',
    paths: ['src/ui/entityLinks.js', 'src/systems/routeFollower.js'],
    done: 'A focused test proves `ui:entityRoute` is consumed and results in `nav:engageRoute` for a routable entity; today the emit has no listener',
    doNot: 'Set the active route for unroutable entities. Add a map layer' },
  { key: 'pro-release-assist-row', group: 'PRO', area: 'professionalism',
    change: 'The Massline release-assist row always renders, disabled with its reason when the family is off',
    paths: ['src/ui/screens/settings.js', 'src/data/featureFlags.js'],
    done: 'A focused test proves the row exists with `massline2.enabled` false (disabled, reason text) and true (enabled)',
    doNot: 'Seed flags from the settings screen' },
  { key: 'pro-more-achievements', group: 'PRO', area: 'parity',
    change: 'Six more achievements from counters the game already keeps',
    paths: ['src/data/achievements.js', 'src/systems/achievements.js'],
    done: 'A focused test proves 26 definitions validate through `validateAchievementDefinitions` and each new one binds to an existing counter; seed-4242 scripts earn two of them',
    doNot: 'Add a counter here. Add hidden-only achievements' },

  // ───────────────────────────── TEACH ─────────────────────────────
  { key: 'teach-drop-kick', group: 'TEACH', area: 'hands',
    change: 'The cargo drop-kick is spoken once when the pilot first jettisons at speed',
    paths: ['src/systems/jettisonImpulse.js', 'src/systems/onboarding.js'],
    done: 'On seed 4242 the first `cargo:jettisoned` above `DROP_KICK_CRUISE_SPEED` produces one hint line and the second none; a focused test pins once per profile',
    doNot: 'Hint at rest. Change the kick impulse' },
  { key: 'teach-reel-hold', group: 'TEACH', area: 'hands',
    change: 'The reel rebind rows name the hold path when no key is bound',
    paths: ['src/ui/screens/settings.js', 'src/systems/masslineInputGrammar.js'],
    done: 'A focused test proves an unbound reel row shows the hold-grammar sentence instead of a blank (NXI-217 covers fake keys; this is the true alternative)',
    doNot: 'Invent a key. Change the grammar' },
  { key: 'teach-cadence-hint', group: 'TEACH', area: 'hands',
    change: 'The cadence winch is spoken once on the first swing that could pump',
    paths: ['src/systems/masslineControlLaw.js', 'src/systems/onboarding.js'],
    done: 'On seed 4242 the first swing whose `readCadencePair` shows a pump window produces one hint line; a focused test pins once per profile',
    doNot: 'Hint on every swing. Change cadence law' },
  { key: 'teach-snare-hint', group: 'TEACH', area: 'hands',
    change: 'Fitting the transverse snare head speaks its verb once',
    paths: ['src/systems/masslineSnares.js', 'src/systems/onboarding.js'],
    done: 'On seed 4242 fitting `mod_transverse_snare_m` produces one hint naming the deploy key; a focused test pins once per profile',
    doNot: 'Hint before the head is fitted. Change snare rules' },
  { key: 'teach-seed-hint', group: 'TEACH', area: 'hands',
    change: 'The first mass seed deploy is spoken with its warning-then-collapse rule',
    paths: ['src/systems/massSeed.js', 'src/systems/onboarding.js'],
    done: 'Deploying a mass seed for the first time on seed 4242 yields exactly one hint and later deploys none; a focused test pins the profile flag',
    doNot: 'Hint at the collapse. Change seed timing' },
  { key: 'teach-field-escapes', group: 'TEACH', area: 'hands',
    change: 'Each field\'s authored escape is taught once, the first time the player is caught in it',
    paths: ['src/data/fields.js', 'src/systems/onboarding.js'],
    done: 'On seed 4242 the first capture by a well produces one hint from `FIELD_ESCAPES` and the second none; a focused test pins once per field kind (today the table has no consumer)',
    doNot: 'Hint for NPC captures. Change field law' },
  { key: 'teach-returning-summary', group: 'TEACH', area: 'hands',
    change: 'A returning pilot hears one line about what changed since the last save',
    paths: ['src/systems/onboarding.js', 'src/ui/dockArrival.js'],
    done: 'On seed 4242 loading a save older than one sim day produces one summary line from the offline summary; a focused test pins it and none for a fresh save',
    doNot: 'Replay the first-hour rail. Add a screen' },
  { key: 'teach-range-from-death', group: 'TEACH', area: 'hands',
    change: 'A death caused by a control verb offers the Range rung for that verb from the death screen',
    paths: ['src/combat/playerDefeat.js', 'src/systems/onboarding.js'],
    done: 'On seed 4242 a death attributed to a slack-line snap offers the reel rung once; a focused test pins the offer and its absence for a combat death',
    doNot: 'Force the Range. Change the death summary' },
];
