// Inference lines — existing groups (PICTURE / VERB / WORLD / INSTRUMENT). Ids assigned by generate.mjs.
// Every path exists today; every done is pinned to seed 4242 or a focused test.
export const lines = [
  // ───────────────────────────── PICTURE (PIC-13+) ─────────────────────────────
  { key: 'pic-strain-glow', group: 'PICTURE', area: 'hands',
    change: 'The rope glows with the swing energy it is storing, so a loaded whip reads before it snaps',
    paths: ['src/render/masslinePresentation.js', 'src/systems/tetherGameplay.js'],
    done: 'On seed 4242 a scripted whip wind-up raises the rope material\'s glow uniform in step with `whipStrainGlow`, and a slack line reads 0; a focused test pins both values',
    doNot: 'Add particles to the rope. Change the whip K or the strain law' },
  { key: 'pic-broadcast-tic', group: 'PICTURE', area: 'world',
    change: 'A station\'s broadcast tic pulses its dish, the way a side event already lights the bay',
    paths: ['src/render/vfx.js', 'src/systems/stationBroadcast.js'],
    done: 'On seed 4242 docked at Helios, each `station:broadcastTic` produces one dish-beat VFX record and none when the broadcaster is quiet; the existing `station:sideEvent` subscription pattern is reused',
    doNot: 'Add a light per tic. Make the tic audible (voice already owns it)' },
  { key: 'pic-pds-spark', group: 'PICTURE', area: 'fight',
    change: 'A point-defence intercept is a spark and a snap at the missile, not a missile that silently vanishes',
    paths: ['src/render/vfx/actionEventRecipes.js', 'src/systems/countermeasures.js', 'src/audio/audioSystem.js'],
    done: 'On seed 4242 a scripted `pds:intercept` yields one recipe record at the intercept point and one short cue; a focused test pins both',
    doNot: 'Reuse the kill burst. Add a UI marker' },
  { key: 'pic-warded', group: 'PICTURE', area: 'fight',
    change: 'A hull the warden is shielding flashes its ward sheet on the hit it absorbed',
    paths: ['src/render/vfx/actionEventRecipes.js', 'src/combat/damage.js'],
    done: 'On seed 4242 a shot into a warded target produces one `combat:warded` recipe record oriented to the hit normal and no damage flash on the ward; a focused test pins it',
    doNot: 'Draw a permanent bubble. Change ward math' },
  { key: 'pic-detonator-row', group: 'PICTURE', area: 'fight',
    change: 'The detonator dart\'s detonation drives the choreography row that already names it',
    paths: ['src/presentation/combatChoreography.js', 'src/systems/impulseCharges.js'],
    done: 'On seed 4242 a dart detonation fires the `detonator_run` commit beat once (today the row is reached only by comment); a focused test pins the beat',
    doNot: 'Add a second burst. Change the dart\'s blast radius' },
  { key: 'pic-cloak-fade', group: 'PICTURE', area: 'fight',
    change: 'A cloak that fades out on its own looks and sounds different from a cloak the pilot dropped',
    paths: ['src/render/vfx/actionEventRecipes.js', 'src/systems/aiPorts.js', 'src/audio/audioSystem.js'],
    done: 'On seed 4242 `cloak:faded` produces a slow shimmer record and a falling cue while `cloak:dropped` keeps its snap; a focused test pins the two ids differ',
    doNot: 'Add a cloak timer readout. Change cloak duration' },
  { key: 'pic-anchor-mark', group: 'PICTURE', area: 'hands',
    change: 'A registered field anchor gets a small ring mark so the well\'s centre is nameable before it fires',
    paths: ['src/systems/fields.js', 'src/render/forceLanguage/fieldForcePresentation.js'],
    done: 'On seed 4242 `fields:anchorRegistered` produces one ring record at the anchor and `fields:cleared` removes it; a focused test pins add and remove',
    doNot: 'Draw the ring for NPC anchors the player cannot see. Add particles' },
  { key: 'pic-pod-retire', group: 'PICTURE', area: 'world',
    change: 'A survivor pod that is rescued, ransomed or lost retires its marker in the colour of its cause',
    paths: ['src/systems/survivorPod.js', 'src/render/vfx/worldCueRecipes.js'],
    done: 'On seed 4242 `survivorPod:resolved` produces one retire cue keyed by outcome and the marker is gone next frame; a focused test pins three outcomes',
    doNot: 'Show the pod\'s oxygen as a bar. Change the 210 s clock' },
  { key: 'pic-rich-seam-glint', group: 'PICTURE', area: 'world',
    change: 'A rich seam that opens glints on the rock so a miner\'s luck is visible from the lane',
    paths: ['src/systems/traffic.js', 'src/render/vfx/worldCueRecipes.js'],
    done: 'On seed 4242 `field:richSeamOpened` yields one glint record on the seam rock and `field:richSeamWorked` ends it; a focused test pins the pair',
    doNot: 'Mark the seam on the map. Change seam odds' },
  { key: 'pic-sink-ring', group: 'PICTURE', area: 'fight',
    change: 'Planting the momentum sink draws a ring where it bit, and releasing it flashes the stored work',
    paths: ['src/render/momentumSinkVfx.js', 'src/systems/weapons.js'],
    done: 'On seed 4242 `weapons:momentumSinkPlanted` and `weapons:momentumSinkReleased` each produce one record at the sink point; a focused test pins both',
    doNot: 'Change the bungee law. Add a charge meter (the overlay exists)' },
  { key: 'pic-flyby-pair', group: 'PICTURE', area: 'presentation',
    change: 'A cancelled flyby focus and a finished one both hand the camera back through one path',
    paths: ['src/systems/flybyFocus.js', 'src/render/cameraDirector.js'],
    done: 'A focused test proves `flybyFocus:end` has a director listener and `flybyFocus:cancel` has a real emitter (today the end is unheard and the cancel is never sent); seed 4242 flyby returns to FOLLOW in ≤ 30 ticks either way',
    doNot: 'Add a third focus mode. Change flyby duration' },
  { key: 'pic-gate-ring', group: 'PICTURE', area: 'world',
    change: 'The gate answers its verdict with a ring pulse: green pass, amber hold, red refusal',
    paths: ['src/systems/gateControlDirector.js', 'src/render/infrastructureMotion.js'],
    done: 'On seed 4242 each `gate:verdict` kind produces one ring-rate change on the gate\'s counter-rotating rings; a focused test pins three kinds',
    doNot: 'Add a gate HUD banner. Change verdict rules' },
  { key: 'pic-ore-intake', group: 'PICTURE', area: 'world',
    change: 'A miner collecting ore sparks at its intake, so work is visible without the HUD',
    paths: ['src/systems/traffic.js', 'src/render/npcJobSignatureVfx.js'],
    done: 'On seed 4242 `traffic:oreCollected` produces one intake record on the miner through the job signature profiles; a focused test pins it and the quiet path when no miner is on glass',
    doNot: 'Add a per-tick emitter. Change yield' },
  { key: 'pic-scavenge-cut', group: 'PICTURE', area: 'world',
    change: 'A scavenger working a wreck shows the cut it is making',
    paths: ['src/systems/aftermathWrecks.js', 'src/render/vfx/worldCueRecipes.js'],
    done: 'On seed 4242 `wreckEcology:scavenged` yields one cut record on the wreck at the scavenger\'s contact; a focused test pins it',
    doNot: 'Add a scavenger marker. Change the ecology budget' },
  { key: 'pic-salvage-core', group: 'PICTURE', area: 'world',
    change: 'A cooked reactor core in flight and an ejected core each have a shape you can track',
    paths: ['src/systems/salvageActions.js', 'src/render/vfx/worldCueRecipes.js'],
    done: 'On seed 4242 `salvage:cookerFlight` and `salvage:coreEjected` each produce one tracked-body cue record; a focused test pins both',
    doNot: 'Change core detonation timing. Add a countdown' },
  { key: 'pic-hot-dock-spill', group: 'PICTURE', area: 'world',
    change: 'A hot-dock cargo spill is seen at the berth, not only counted',
    paths: ['src/systems/cargo.js', 'src/render/vfx/worldCueRecipes.js'],
    done: 'On seed 4242 `cargo:hotDockSpill` produces one spill record at the berth with the lot count; a focused test pins it beside `test/hot-dock-cargo-spill.test.mjs`',
    doNot: 'Spawn pickups the sim did not. Change spill odds' },
  { key: 'pic-swing-trace-grade', group: 'PICTURE', area: 'hands',
    change: 'The swept swing ribbon fades in the colour of the release grade it earned',
    paths: ['src/render/masslineSwingTrace.js', 'src/systems/masslineThrow.js'],
    done: 'On seed 4242 a razor and a rough release colour the trace differently from `tether:releaseRated`; a focused test pins the band→colour map',
    doNot: 'Change the release rating law. Add particles' },

  // ───────────────────────────── VERB (VERB-14+) ─────────────────────────────
  { key: 'verb-reel-defaults', group: 'VERB', area: 'hands',
    change: 'Reel in and reel out have default keys instead of empty bindings in every scheme',
    paths: ['src/systems/input.js', 'src/ui/screens/settings.js'],
    done: 'A focused test proves `reelIn`/`reelOut` resolve non-empty codes in pilot, helm-assist and classic and that they conflict with nothing; input edits carry the focused input/rebind validation the contract requires',
    doNot: 'Remove the hold grammar path. Change any other default code' },
  { key: 'verb-vectoring-row', group: 'VERB', area: 'hands',
    change: 'The velocity-vectoring assist can be turned off in Gameplay settings like the other three assists',
    paths: ['src/ui/screens/settings.js', 'src/systems/flightV3.js'],
    done: 'A focused test proves `gameplay.velocityVectoring` false disables the assist on seed 4242 and the row persists through the profile snapshot',
    doNot: 'Change the default (on). Add a strength slider' },
  { key: 'verb-cruise-meter', group: 'VERB', area: 'hands',
    change: 'The cruise charge has a meter on the verb shelf, so the three-second spool is visible',
    paths: ['src/ui/powerRail.js', 'src/systems/cruise.js'],
    done: 'On seed 4242 the rail model exposes `cruiseChargeProgress` rising 0→1 over the charge and the engaged state after; a focused test pins it',
    doNot: 'Change charge time. Redesign the rail (ORRERY)' },
  { key: 'verb-aim-assist-toggle', group: 'VERB', area: 'parity',
    change: 'Auto-target assist has an off and a strength in Gameplay settings',
    paths: ['src/systems/autoTargetAssist.js', 'src/ui/screens/settings.js'],
    done: 'A focused test proves the assist yields zero aim correction at off and the authored correction at full on seed 4242; the key persists',
    doNot: 'Change the default strength. Touch raw aim input' },
  { key: 'verb-release-cancel-tick', group: 'VERB', area: 'hands',
    change: 'A cancelled release gives a soft tick, distinct from a refusal',
    paths: ['src/systems/masslineThrow.js', 'src/audio/audioSystem.js'],
    done: 'On seed 4242 `massline:releaseCancelled` plays one soft cue that is not `sfx_massline_deny`; a focused test pins the id',
    doNot: 'Use the deny voice. Add a caption longer than one word' },
  { key: 'verb-rebound-voice', group: 'VERB', area: 'hands',
    change: 'A line that rebounds off its limit twangs',
    paths: ['src/combat/attachments.js', 'src/audio/combatVerbCues.js'],
    done: 'On seed 4242 `tether:rebound` plays the authored twang once per rebound through the dispatched cue table; a focused test pins one play per event',
    doNot: 'Double-voice with the strain tone. Change rebound physics' },
  { key: 'verb-chain-share', group: 'VERB', area: 'hands',
    change: 'When two lines share a load, the HUD shows the split',
    paths: ['src/systems/tetherGameplay.js', 'src/ui/masslineHud.js'],
    done: 'On seed 4242 a bridle with two endpoints publishes `chain:tetherShare` and the HUD model shows both fractions summing to 1; a focused test pins it',
    doNot: 'Change the bridle law. Add a third readout element' },
  { key: 'verb-npc-counterplay', group: 'VERB', area: 'hands',
    change: 'An NPC contesting your line says what it is doing',
    paths: ['src/systems/tetherGameplay.js', 'src/systems/barkDirector.js'],
    done: 'On seed 4242 `massline:npcCounterplay` produces one bark in the contestant\'s register within the ambient gap; a focused test pins it',
    doNot: 'Bark every tick of the contest. Change the contest math' },
  { key: 'verb-moment-amended', group: 'VERB', area: 'presentation',
    change: 'A moment that is re-rated after the fact re-rates its clip',
    paths: ['src/systems/bulletTime.js', 'src/ui/screens/clips.js'],
    done: 'On seed 4242 `moment:amended` updates the clip\'s rating in the reel model without a second clip; a focused test pins one clip, new rating',
    doNot: 'Create a second clip. Change moment thresholds' },
  { key: 'verb-bomb-rack-click', group: 'VERB', area: 'fight',
    change: 'Cycling the bomb rack clicks and a changed rack is heard',
    paths: ['src/systems/bombs.js', 'src/audio/bombAudio.js'],
    done: 'On seed 4242 `bombs:cycle` and `bombs:rackChanged` each play one short authored click; a focused test pins two ids',
    doNot: 'Play on `bombs:stockChanged` per unit. Change rack rules' },
  { key: 'verb-sink-voice', group: 'VERB', area: 'fight',
    change: 'Planting and releasing the momentum sink are heard as a bite and a release',
    paths: ['src/systems/weapons.js', 'src/audio/audioSystem.js'],
    done: 'On seed 4242 the planted and released events play two distinct authored cues once each; a focused test pins them',
    doNot: 'Reuse the gravitic fire voice. Change sink capacity' },
  { key: 'verb-seed-anchor-preview', group: 'VERB', area: 'hands',
    change: 'The latch preview says when a mass seed is the anchor and whether it will hold',
    paths: ['src/systems/massSeed.js', 'src/ui/masslineHud.js'],
    done: 'On seed 4242 aiming at a seed publishes `isMassSeedTetherEligible` into the preview model and the HUD shows the seed state word; a focused test pins eligible and locking',
    doNot: 'Change seed eligibility. Add a second preview element' },
  { key: 'verb-selfsling-named', group: 'VERB', area: 'hands',
    change: 'A self-sling names the bonus speed it earned',
    paths: ['src/systems/masslineThrow.js', 'src/ui/stuntCallout.js'],
    done: 'On seed 4242 a self-sling produces one callout carrying `selfSlingBonusDv` rounded to a whole number; a focused test pins it',
    doNot: 'Change the bonus law. Add a second callout element' },
  { key: 'verb-counter-thrust-preview', group: 'VERB', area: 'hands',
    change: 'The kernel\'s counter-thrust preview is drawn as the stop vector while the pilot brakes',
    paths: ['src/core/flight/propulsionKernel.js', 'src/ui/hud.js'],
    done: 'On seed 4242 the HUD model carries `previewCounterThrust` output while brake is held and nothing otherwise; a focused test pins the two states',
    doNot: 'Change the brake law. Redesign the HUD (ORRERY)' },
  { key: 'verb-route-brake', group: 'VERB', area: 'hands',
    change: 'The route follower\'s brake is seen and heard when it fires',
    paths: ['src/systems/routeFollower.js', 'src/audio/audioSystem.js'],
    done: 'On seed 4242 `nav:routeBrake` plays one brake cue and paints one brake record; a focused test pins both',
    doNot: 'Brake earlier. Add a UI banner' },
  { key: 'verb-orbit-ring', group: 'VERB', area: 'hands',
    change: 'The orbit assist shows the ring it is holding you to',
    paths: ['src/core/flight/orbitAssist.js', 'src/ui/masslineHud.js'],
    done: 'On seed 4242 with orbit assist above 0 the HUD model carries the assist\'s target radius and zero when the assist is idle; a focused test pins both',
    doNot: 'Change the assist strength. Draw the ring for NPCs' },

  // ───────────────────────────── WORLD (WORLD-21+) ─────────────────────────────
  { key: 'world-spill-witness', group: 'WORLD', area: 'world',
    change: 'A crew that watches a cargo spill remarks on it',
    paths: ['src/systems/traffic.js', 'src/systems/barkDirector.js'],
    done: 'On seed 4242 `traffic:spillNoticed` produces one bark from the noticing hull within the ambient gap; a focused test pins one bark per notice',
    doNot: 'Bark from hulls that did not notice. Change spill physics' },
  { key: 'world-liner-news', group: 'WORLD', area: 'world',
    change: 'A passenger liner\'s receipt and a suspended liner are news lines',
    paths: ['src/systems/traffic.js', 'src/ui/marketNews.js'],
    done: 'On seed 4242 `traffic:passengerLinerReceipt` and `traffic:passengerLinerSuspended` each publish one cited headline; a focused test pins both',
    doNot: 'Publish uncited. Add a liner screen' },
  { key: 'world-pod-remembered', group: 'WORLD', area: 'world',
    change: 'A station remembers the survivor pod you delivered or the one you promoted to a crew',
    paths: ['src/systems/survivorPod.js', 'src/systems/stationContacts.js'],
    done: 'On seed 4242 `survivorPod:delivered` and `survivorPod:promoted` each add one contact memory line at the receiving station; a focused test pins both',
    doNot: 'Pay twice (SFQ-I046). Add a rescue screen' },
  { key: 'world-harasser-bark', group: 'WORLD', area: 'world',
    change: 'A harasser that gives up says so as it leaves',
    paths: ['src/systems/encounterDirector.js', 'src/systems/barkDirector.js'],
    done: 'On seed 4242 `harasser:disengaged` produces one departing bark; a focused test pins one per disengage',
    doNot: 'Change disengage rules. Bark before the disengage commits' },
  { key: 'world-hazard-alert', group: 'WORLD', area: 'world',
    change: 'Entering or leaving a hazard raises the alert line the HUD already owns',
    paths: ['src/systems/world.js', 'src/ui/alerts.js'],
    done: 'On seed 4242 `hazard:changed` raises one alert on entry and clears it on exit for radiation and nebula; a focused test pins both',
    doNot: 'Add a hazard bar. Change hazard damage' },
  { key: 'world-rumor-resolved-news', group: 'WORLD', area: 'world',
    change: 'A frontier rumour you bought and resolved becomes a news line with the payoff named',
    paths: ['src/systems/world.js', 'src/ui/marketNews.js'],
    done: 'On seed 4242 `frontierRumor:resolved` publishes one cited headline; a focused test pins it and none for an unresolved rumour',
    doNot: 'Reveal the one-off before resolution. Publish uncited' },
  { key: 'world-dock-cards-dup', group: 'WORLD', area: 'professionalism',
    change: 'The dock cards have one path: the emitted card event is consumed or removed',
    paths: ['src/ui/marketNews.js', 'src/ui/dockArrival.js'],
    done: 'A focused test proves either a `news:dockCards` listener renders the cards or the emit is gone and `cardsForStation` is the only path; today both exist and one is dead',
    doNot: 'Add a third card path' },
  { key: 'world-presence-routing', group: 'WORLD', area: 'world',
    change: 'An Archive administrative reroute or a Fulfillment provocation is announced in the faction\'s register',
    paths: ['src/systems/factionPresence.js', 'src/systems/barkDirector.js'],
    done: 'On seed 4242 `factionPresence:administrativeRouting` and `factionPresence:fulfillmentProvoked` each produce one bark in the right register; a focused test pins both',
    doNot: 'Bark on every `factionPresence:spawned`. Change presence odds' },
  { key: 'world-yard-dispatch', group: 'WORLD', area: 'world',
    change: 'A yard tug dispatch is a dock side event you can watch',
    paths: ['src/systems/npcJobsRuntime.js', 'src/systems/stationSideEventDirector.js'],
    done: 'On seed 4242 `npcjobs:yardDispatch` schedules one `station:sideEvent` of the tug kind at the yard; a focused test pins it',
    doNot: 'Add a side event kind. Change dispatch cadence' },
  { key: 'world-threatened-miner', group: 'WORLD', area: 'world',
    change: 'A threatened miner shows the same reaction it shows to a close player',
    paths: ['src/systems/npcJobsRuntime.js', 'src/render/npcJobSignatureVfx.js'],
    done: 'On seed 4242 `npcjobs:threatened` triggers the miner\'s reaction profile once; a focused test pins it',
    doNot: 'Change job graphs. Add a threat marker' },
  { key: 'world-miner-relocated', group: 'WORLD', area: 'world',
    change: 'A miner that moves to a new seam is a news line',
    paths: ['src/systems/npcJobsRuntime.js', 'src/ui/marketNews.js'],
    done: 'On seed 4242 `npcjobs:minerRelocated` publishes one cited headline naming the sector; a focused test pins it',
    doNot: 'Publish for off-glass relocations the player never saw' },
  { key: 'world-seam-help', group: 'WORLD', area: 'world',
    change: 'A miner who reserved help on a rich seam hails you when you are the help',
    paths: ['src/systems/traffic.js', 'src/systems/barkDirector.js'],
    done: 'On seed 4242 `traffic:richSeamHelpReserved` produces one hail to the player when the player is the reserved helper; a focused test pins it',
    doNot: 'Hail every nearby ship. Change seam rewards' },
  { key: 'world-mining-noise', group: 'WORLD', area: 'world',
    change: 'A loud mining operation raises local danger, so noise draws attention',
    paths: ['src/systems/mining.js', 'src/systems/sectorSim.js'],
    done: 'On seed 4242 `danger:miningNoise` applies one bounded impulse to the sector\'s danger field; a focused test pins the bound and the decay',
    doNot: 'Spawn pirates directly. Exceed the existing impulse cap' },
  { key: 'world-ghost-convoy-rumor', group: 'WORLD', area: 'world',
    change: 'A ghost convoy rumour is heard at the bar, not only rolled',
    paths: ['src/systems/lossLedger.js', 'src/ui/station/barContacts.js'],
    done: 'On seed 4242 `rumor:ghostConvoy` adds one bar rumour line at the nearest station; a focused test pins it',
    doNot: 'Reveal the convoy position. Add a rumour screen' },
  { key: 'world-tourist-hail', group: 'WORLD', area: 'world',
    change: 'A tourist liner hails in its own register once scenic sectors have tourists',
    paths: ['src/data/barks.js', 'src/systems/traffic.js'],
    done: 'On seed 4242 in a scenic sector a tourist-role hull produces a tourist-register hail within 5 minutes; a focused test pins the register',
    doNot: 'Add a role. Reuse the freighter register' },
  { key: 'world-predation-tell', group: 'WORLD', area: 'world',
    change: 'A predator\'s stalk is telegraphed before it commits',
    paths: ['src/systems/encounterScripts.js', 'src/systems/encounterDirector.js'],
    done: 'On seed 4242 `encounter:predationTelegraph` reaches the telegraph path once per stalk; a focused test pins one telegraph before the commit',
    doNot: 'Change predation odds. Telegraph twice' },
  { key: 'world-depot-patrol-chart', group: 'WORLD', area: 'longgame',
    change: 'The depot patrol your claim summoned shows on the chart as a moving law presence',
    paths: ['src/systems/claims.js', 'src/ui/galaxyMap.js'],
    done: 'On seed 4242 a supported depot\'s patrol beat publishes a moving marker that follows `DEPOT_PATROL_SHAPE_ID`; a focused test pins position updates',
    doNot: 'Add a patrol screen. Change the rotation gap' },
  { key: 'world-berth-card', group: 'WORLD', area: 'world',
    change: 'A berth assignment or a hold order shows on the dock arrival card',
    paths: ['src/systems/stationServices.js', 'src/ui/dockArrival.js'],
    done: 'On seed 4242 `station:berthAssigned` and `station:holding` each produce one card line; a focused test pins both',
    doNot: 'Change berth rules. Add a berth screen' },
  { key: 'world-lot-rumor', group: 'WORLD', area: 'world',
    change: 'A posted ore lot is a bar rumour a hauler player can act on',
    paths: ['src/systems/npcJobsRuntime.js', 'src/ui/station/barContacts.js'],
    done: 'On seed 4242 `npcjobs:lotPosted` adds one bar line naming the lot\'s sector; a focused test pins it and its removal on `npcjobs:lotClaimed`',
    doNot: 'Offer the lot as a mission. Change lot rules' },
  { key: 'world-second-lane-contact', group: 'WORLD', area: 'world',
    change: 'A busy lane carries two named contacts so repeat trips meet a second face',
    paths: ['src/data/laneContacts.js', 'src/systems/traffic.js'],
    done: 'On seed 4242 Helios and Ceres each stamp two distinct named contacts across 20 minutes of traffic; a focused test pins the count',
    doNot: 'Stamp two names on one hull. Add roles' },

  // ───────────────────────────── INSTRUMENT (INST-17+) ─────────────────────────────
  { key: 'inst-jump-arrive', group: 'INSTRUMENT', area: 'presentation',
    change: 'The stranded jump-arrival recipe plays as a layer under the travel arrival voice',
    paths: ['src/audio/audioSystem.js', 'src/data/audioRecipes.js'],
    done: 'On seed 4242 a jump arrival plays `sfx_travel_arrival` with `sfx_jump_arrive` as a layer once; a focused test pins one play each',
    doNot: 'Un-SILENT the raw `jump:arrive` row. Add samples' },
  { key: 'inst-discovery-reveal', group: 'INSTRUMENT', area: 'world',
    change: 'Discovering a point of interest plays the authored discovery reveal',
    paths: ['src/audio/audioSystem.js', 'src/systems/presentationAdapters.js'],
    done: 'On seed 4242 the first `poi:discovered` plays `sfx_discovery_reveal` once and repeats never for the same POI; a focused test pins it',
    doNot: 'Play on `poi:identified`. Add samples' },
  { key: 'inst-engine-idle', group: 'INSTRUMENT', area: 'presentation',
    change: 'An idle engine has its authored idle voice under the silent-at-zero law',
    paths: ['src/audio/audioSystem.js', 'src/presentation/throttleAnswer.js'],
    done: 'On seed 4242 `sfx_engine_idle` plays at ≤ −30 dB while docked-undocked idle and is silent at zero throttle in flight per `stepCueGain`; a focused test pins both',
    doNot: 'Break the 0.25 s silence contract. Add samples' },
  { key: 'inst-travel-motif', group: 'INSTRUMENT', area: 'presentation',
    change: 'Locking a lane plays the authored travel motif sting',
    paths: ['src/audio/audioSystem.js', 'src/data/audioRecipes.js'],
    done: 'On seed 4242 `presentation.travel.lane_lock` plays `sfx_travel_motif` once per lock; a focused test pins it',
    doNot: 'Play on every lane boost. Add samples' },
  { key: 'inst-ore-one-voice', group: 'INSTRUMENT', area: 'presentation',
    change: 'Ore collection has one voice, not the verb route and the presentation route both',
    paths: ['src/audio/audioSystem.js', 'src/audio/combatVerbCues.js'],
    done: 'On seed 4242 one `mining:yield` produces exactly one recipe play; a focused test pins the count',
    doNot: 'Silence both. Change yield' },
  { key: 'inst-cruise-one-owner', group: 'INSTRUMENT', area: 'presentation',
    change: 'Cruise engage answers once: the lane-lock voice owns it and the raw boost row goes SILENT with its reason',
    paths: ['src/audio/combatVerbCues.js', 'src/systems/presentationAdapters.js'],
    done: 'On seed 4242 one `cruise:engaged` produces one recipe play; a focused test pins the count and the SILENT reason text',
    doNot: 'Silence the lane-lock voice. Change cruise timing' },
  { key: 'inst-hitch-identity', group: 'INSTRUMENT', area: 'hands',
    change: 'Hitching a ride has a latch voice of its own, a variant of the massline latch, not a copy',
    paths: ['src/audio/combatVerbCues.js', 'src/data/audioRecipes.js'],
    done: 'On seed 4242 `fields:hitchLatched` plays a hitch-variant recipe id distinct from the massline latch; a focused test pins the ids differ',
    doNot: 'Add samples. Change hitch physics' },
  { key: 'inst-field-deploy-primary', group: 'INSTRUMENT', area: 'professionalism',
    change: 'The five field deploy voices play from the primary cue table, not only through the accessibility table',
    paths: ['src/audio/audioSystem.js', 'src/ui/captions.js'],
    done: 'A focused test proves each `fields:deployed` kind resolves a recipe with the accessibility table disabled and captions still fire with it enabled',
    doNot: 'Remove the accessibility routing. Add samples' },
  { key: 'inst-emergent-voice', group: 'INSTRUMENT', area: 'fight',
    change: 'The emergent primitives\' own voice file answers the audio event they emit',
    paths: ['src/systems/emergentPrimitives.js', 'src/audio/emergentPrimitiveVoice.js'],
    done: 'On seed 4242 `emergent:audio` reaches `emergentPrimitiveVoice.js` and plays once per event; a focused test pins it',
    doNot: 'Route through the weapon fire voice. Add samples' },
  { key: 'inst-reactor-clear', group: 'INSTRUMENT', area: 'world',
    change: 'Towing a reactor clear gets a relief tone instead of a SILENT row',
    paths: ['src/audio/combatVerbCues.js', 'src/systems/salvage.js'],
    done: 'On seed 4242 `salvage:reactorTowedClear` plays one resolving cue; a focused test pins it',
    doNot: 'Play during the tow. Add samples' },
  { key: 'inst-raid-register', group: 'INSTRUMENT', area: 'longgame',
    change: 'A claim raid warning uses the wanted-alert register at low gain, so it is urgent without being a menu beep',
    paths: ['src/audio/audioSystem.js', 'src/systems/claims.js'],
    done: 'On seed 4242 `claim:raidWarning` plays `sfx_wanted_alert` at the authored low gain once; a focused test pins id and gain',
    doNot: 'Duck music for it. Add samples' },
  { key: 'inst-search-edge', group: 'INSTRUMENT', area: 'world',
    change: 'Crossing the wanted search radius is audible in both directions',
    paths: ['src/presentation/wantedSearchVolume.js', 'src/audio/audioSystem.js'],
    done: 'On seed 4242 leaving the search ring plays one falling cue and re-entering one rising cue; a focused test pins both edges',
    doNot: 'Change heat clear timers. Add samples' },
  { key: 'inst-service-voice', group: 'INSTRUMENT', area: 'world',
    change: 'A station service starting and aborting are heard at the berth',
    paths: ['src/systems/stationServices.js', 'src/audio/audioSystem.js'],
    done: 'On seed 4242 `service:started` and `service:aborted` each play one authored cue; a focused test pins both',
    doNot: 'Voice `service:progress` ticks. Add samples' },
  { key: 'inst-magnet-chime', group: 'INSTRUMENT', area: 'hands',
    change: 'A magnet capture chimes softly, distinct from a scoop pickup',
    paths: ['src/systems/lootShards.js', 'src/audio/audioSystem.js'],
    done: 'On seed 4242 `loot:magnetCaptured` plays a recipe id different from `sfx_pickup_chime`; a focused test pins the ids differ',
    doNot: 'Chime per unit in a stream. Add samples' },
  { key: 'inst-unique-loot-voices', group: 'INSTRUMENT', area: 'longgame',
    change: 'The choir bell, the nestbreaker split and the pale coil blink each have a voice',
    paths: ['src/systems/uniqueLootAbilities.js', 'src/audio/audioSystem.js'],
    done: 'On seed 4242 the three `uniqueLoot:*` events play three distinct authored cues; a focused test pins three ids',
    doNot: 'Reuse the field deploy voices. Add samples' },
  { key: 'inst-identity-revealed', group: 'INSTRUMENT', area: 'longgame',
    change: 'A revealed build identity is heard once as a scan resolve, not read off a panel',
    paths: ['src/systems/buildIdentity.js', 'src/audio/audioSystem.js'],
    done: 'On seed 4242 `buildIdentity:revealed` plays the scan-resolve cue once per target; a focused test pins once-only',
    doNot: 'Reveal beyond the scan stage. Add samples' },
  { key: 'inst-flak-voice', group: 'INSTRUMENT', area: 'fight',
    change: 'Flak has its own muzzle voice instead of sharing the autocannon\'s',
    paths: ['src/audio/audioSystem.js', 'src/data/audioRecipes.js'],
    done: 'On seed 4242 `wpn_flak_turret_s` fire resolves a flak recipe id and `wpn_autocannon_s` keeps `sfx_wpn_autocannon`; a focused test pins the ids differ',
    doNot: 'Add samples. Change flak damage' },
  { key: 'inst-heavy-beam', group: 'INSTRUMENT', area: 'fight',
    change: 'Heavy beams sound heavier than the beam laser',
    paths: ['src/audio/audioSystem.js', 'src/data/audioRecipes.js'],
    done: 'On seed 4242 `wpn_heavy_beam_l` resolves a lower-register beam recipe than `wpn_beam_laser_m`; a focused test pins the two ids and the rate order',
    doNot: 'Add samples. Change beam dps' },
];
