// Inference lines — additions after the count check.
export const lines = [
  { key: 'pic-tanker-signature', group: 'PICTURE', area: 'world',
    change: 'The fielded tanker and cutter have job signatures like the other working craft',
    paths: ['src/render/npcJobSignatureVfx.js', 'src/data/occupationalTrafficCraft.js'],
    done: 'A focused test proves `NPC_JOB_SIGNATURE_PROFILES` resolves a profile for the tanker (heavy, clean burn) and the cutter (on the pin, scan sweep) and seed-4242 spawns carry them',
    doNot: 'Add a profile per hull. Change reaction kinds' },
  { key: 'verb-charge-capacity', group: 'VERB', area: 'fight',
    change: 'The impulse charge count on the verb shelf reads the fitted capacity, not a hardcoded rack size',
    paths: ['src/systems/impulseCharges.js', 'src/ui/powerRail.js'],
    done: 'On seed 4242 fitting `mod_charge_vector_rack` changes the rail\'s charge capacity through `resolveImpulseChargeCapacity`; a focused test pins two capacities',
    doNot: 'Change charge cost. Redesign the rail (ORRERY)' },
  { key: 'world-wreck-retired', group: 'WORLD', area: 'world',
    change: 'A retired aftermath wreck clears its chart marker and its cause line',
    paths: ['src/systems/aftermathWrecks.js', 'src/ui/galaxyMap.js'],
    done: 'On seed 4242 `aftermathWreck:retired` removes the marker and the map model no longer lists the wreck; a focused test pins removal',
    doNot: 'Retire wrecks earlier. Add a wreck list screen' },
  { key: 'world-load-empty', group: 'WORLD', area: 'world',
    change: 'A hauler that arrives to an empty lot grumbles about it',
    paths: ['src/systems/npcJobsRuntime.js', 'src/systems/barkDirector.js'],
    done: 'On seed 4242 `npcjobs:loadEmpty` produces one hauler-register bark within the ambient gap; a focused test pins one per empty load',
    doNot: 'Bark off-glass. Change lot rules' },
  { key: 'econ-insurance-upsell', group: 'ECON', area: 'longgame',
    change: 'The death screen names the insurance that would have covered this loss',
    paths: ['src/combat/playerDefeat.js', 'src/ui/screens/gameOver.js'],
    done: 'On seed 4242 an uninsured death\'s after-action model carries the hull policy name and the premium that would have applied; an insured death carries the deductible only; a focused test pins both',
    doNot: 'Sell the policy from the death screen. Change recovery cost' },
  { key: 'pro-load-latest', group: 'PRO', area: 'professionalism',
    change: 'The death screen offers Load latest beside the recovery key',
    paths: ['src/ui/screens/gameOver.js', 'src/save/saveSystem.js'],
    done: 'A focused test proves the after-action model exposes `selectLatestOccupiedSlot` as a verb that loads through the trusted-slot confirmation; Ironman deaths do not expose it',
    doNot: 'Bypass the slot-trust confirmation. Offer it in Ironman' },
  { key: 'teach-help-chords', group: 'TEACH', area: 'parity',
    change: 'The Help screen lists the live pad chords, read from the live binding table',
    paths: ['src/ui/screens/help.js', 'src/systems/gamepad.js'],
    done: 'A focused test proves the help model lists every entry of `GAMEPAD_DEFAULT_BINDINGS` (chords included) with `GAMEPAD_BUTTON_LABELS` from the active glyph set and updates after a rebind',
    doNot: 'Hardcode the list. Restyle Help (ORRERY)' },
  { key: 'fight-surge-called', group: 'FIGHT', area: 'fight',
    change: 'A swarm reinforcement surge is called before it lands',
    paths: ['src/data/swarmMode.js', 'src/systems/survivalAnnounce.js'],
    done: 'On seed 4242 each reinforcement batch is preceded by one announce line at least 60 ticks before the spawn; a focused test pins the lead time',
    doNot: 'Delay the surge. Announce every spawn' },
  { key: 'pro-motion-row-once', group: 'PRO', area: 'professionalism',
    change: 'The Motion effects and UI scale rows appear once in Settings, with a labelled mirror if a second home is kept',
    paths: ['src/ui/screens/settings.js'],
    done: 'A focused test proves each settings key has exactly one editable row and any mirror is read-only and labelled; the settings walk still reaches both tabs',
    doNot: 'Drop the Access tab entry without a mirror. Restyle (ORRERY)' },
];
