// Neighbour citations per packet slug: the landed banks this packet extends or composes after.
// SF-* = SpaceFace_Planbank_300; NXB/NXI = next-wave-2026-09-28; SFQ-B/SFQ-I = finish-expansion-2026-09;
// PB-LANE-* = build_map §1C group G rows. A citation means "read it first; do visibly more".
export const near = {
  // 01-hand
  'the-travel-drive-is-taught-and-shelved': ['SFQ-B020', 'SFQ-B063'],
  'the-pad-covers-the-whole-hand': ['SFQ-B224', 'NXB-055', 'NXI-217'],
  'aim-and-pad-response-are-tunable': ['SFQ-B224', 'NXB-055'],
  'haptics-have-their-own-axis-and-speak-per-verb': ['SFQ-B226', 'PQ-164'],
  'draw-to-fly-shows-its-ink-and-grades-the-stroke': ['SFQ-B004', 'SFQ-B011'],
  'earned-speed-shows-past-the-gauge': ['SFQ-B013', 'NXI-013'],
  // 02-massline
  'massline-receipts-reach-the-picture': ['SFQ-B192', 'NXB-007'],
  'the-massline-instrument-reads-load-and-apex': ['SFQ-B026', 'SF-017'],
  'stunts-are-named-in-adventure': ['NXB-007', 'SF-292'],
  'salvage-rights-are-heard-and-kept': ['NXB-007', 'SF-278'],
  'deployables-survive-a-save': ['SFQ-B221', 'NXB-059', 'NXI-089'],
  // 03-fight / 04-crucible
  'every-archetype-telegraphs': ['SFQ-B044', 'SFQ-B050', 'SFQ-I017'],
  'variant-pairs-become-distinct-problems': ['SFQ-B050', 'SF-049'],
  'flak-intercepts-and-the-pd-screen-is-real': ['NXB-012', 'NXI-046'],
  'hit-confirmation-in-three-states': ['SFQ-B202', 'SF-017'],
  'the-dreadnought-has-phases': ['NXB-016', 'NXI-061', 'NXI-063', 'SF-068'],
  'emergent-weapons-are-drawn-and-drafted': ['SFQ-B054', 'NXB-018'],
  'arena-props-are-bodies-the-massline-can-move': ['SFQ-B056', 'NXB-019', 'NXI-075', 'SF-071'],
  'the-geometry-problems-join-the-swarm-roster': ['SFQ-B050', 'SFQ-B048'],
  'one-boss-machine-for-the-crucible': ['SFQ-B052', 'NXB-016', 'SF-068'],
  'the-wave-intro-is-a-window': ['SFQ-B057', 'NXI-067'],
  'arc-difficulty-is-composition-not-hp': ['SFQ-B048', 'NXB-017'],
  'results-sheet-names-the-run': ['SFQ-B058', 'SFQ-I021'],
  'weapon-families-agree-on-provenance': ['SFQ-B182', 'SFQ-B193', 'SF-229'],
  // 05-world / 06-law
  'sector-flags-shape-the-population': ['SFQ-B101', 'SFQ-B116'],
  'a-third-sector-closes-the-work-loop': ['SFQ-B082', 'PB-LANE-WORLD', 'SF-078'],
  'way-of-life-reaches-the-player': ['SFQ-B101', 'SFQ-B107'],
  'every-sector-has-a-physical-row-and-a-composition': ['SFQ-B101'],
  'more-than-one-lane': ['SFQ-B103', 'NXB-036'],
  'the-poi-you-are-inside-shows-its-plan': ['SFQ-B105', 'SF-124'],
  'the-codex-gets-a-world-tab': ['SFQ-B118', 'SF-131'],
  'ceres-gets-a-unique-wreck': ['SFQ-B110', 'SF-167'],
  'the-fine-on-dock-is-a-choice': ['SFQ-B112', 'NXB-044', 'NXI-174', 'SF-161'],
  'the-law-says-what-it-did': ['SFQ-B112', 'SF-161'],
  'the-hearing-is-reachable': ['SFQ-B075', 'SF-291'],
  'a-war-changing-hands-is-news': ['SFQ-B116'],
  'six-factions-get-a-door': ['SFQ-B116'],
  // 07–10 long game
  'why-the-price-moved': ['SFQ-B081', 'NXI-108'],
  'lifetime-margins-per-commodity': ['NXB-026', 'SF-107', 'SF-115'],
  'the-cargo-deck-tells-the-truth-about-cost': ['NXI-101'],
  'debt-is-an-instrument': ['SFQ-B086', 'SF-164', 'NXB-044'],
  'the-world-reports-what-you-built': ['NXB-035', 'NXI-140', 'NXI-138'],
  'research-reads-as-a-verb': ['SFQ-B099'],
  'four-module-numbers-do-what-they-say': ['SFQ-B005', 'NXB-030'],
  'one-readout-for-all-industry': ['SFQ-B090'],
  'the-time-limit-clause-ticks': ['NXB-039', 'NXI-153', 'SFQ-B072'],
  'name-your-ship': ['SFQ-B118'],
  'build-identity-reaches-a-screen': ['NXB-031', 'SF-133'],
  'the-heavy-ladder-flies-distinct-drives': ['NXB-030', 'SF-122'],
  'more-than-one-title': ['SFQ-B113', 'SFQ-B118'],
  'a-parked-hull-keeps-its-hold': ['NXI-136'],
  'the-back-half-of-the-spine-has-recovery-lines': ['SFQ-B061', 'NXB-046'],
  'a-condition-tells-you-when-it-breaks': ['NXI-149', 'SFQ-I025'],
  'one-row-archetypes-get-variants-and-careers': ['SFQ-B073', 'SFQ-B080'],
  'an-unwinnable-contract-refunds-and-says-why': ['SFQ-B079', 'NXB-038', 'NXI-150'],
  // 11–13 presentation
  'refusal-has-a-voice-and-a-shape': ['SFQ-I078', 'SFQ-I009', 'NXI-046'],
  'severity-is-a-shape-tier-not-a-particle-count': ['SFQ-B188', 'NXB-049'],
  'pods-and-wrecks-have-role-silhouettes': ['SFQ-B171', 'SF-211'],
  'station-arms-move-when-the-station-works': ['SFQ-B187', 'SF-215'],
  'reduced-motion-declares-every-cues-form': ['SFQ-B226', 'SFQ-I084', 'NXI-196', 'SF-206', 'SF-254'],
  'kills-have-a-mass-ladder-in-the-ear': ['SFQ-B191'],
  'sustained-states-have-continuous-voices': ['SFQ-B194', 'NXB-052', 'NXI-208', 'SF-230'],
  'the-mix-bows-to-any-sustained-voice': ['SFQ-B195', 'NXB-052'],
  'one-kill-recorder': ['SFQ-B058'],
  'replay-and-clips-open-where-you-died': ['SFQ-B058'],
  // 14 machine
  'spatial-hash-rebuilds-only-when-a-body-moved': ['NXB-057', 'SFQ-B213'],
  'quiet-latches-for-the-five-loudest-idle-owners': ['SFQ-B213', 'SFQ-I085'],
  'ambient-admission-lane-is-budgeted-not-one-per-present': ['SFQ-B212', 'NXB-060'],
  'sector-arrival-gets-an-enumerated-roster-like-the-crucible': ['SFQ-B212', 'NXB-060'],
  'determinism-guard-also-bans-wall-time-in-sim-owners': ['NXI-012'],
  'vfx-slots-allocate-at-pool-construction': ['SFQ-B214'],
  'shipped-build-attributes-its-own-hitches': ['SFQ-B211'],
  'batched-instance-draw-for-one-archetype': ['SFQ-B215', 'NXB-058'],
  // 15–16 professional / teach
  'dead-settings-controls-do-something': ['SFQ-B225'],
  'video-and-audio-options-reach-parity': ['SFQ-B199', 'SFQ-I080', 'SFQ-B225'],
  'out-of-fuel-has-a-door': ['SFQ-B086', 'SFQ-B228'],
  'ironman-is-one-way': ['SFQ-B207'],
  'the-electron-shell-remembers-the-window': ['SFQ-B229'],
  'machine-locales-are-labelled-previews': ['SFQ-B227'],
  'save-fuzz-never-throws': ['SFQ-B222'],
  'quota-pressure-keeps-one-recovery': ['SFQ-B223'],
  'a-repaired-save-says-what-it-lost': ['SFQ-B228'],
  'a-stuck-ship-can-ask-for-a-tow': ['SFQ-B106', 'SFQ-B228'],
  'settings-announce-themselves-to-a-screen-reader': ['SFQ-B226', 'SFQ-I091', 'NXB-056', 'NXI-221'],
  'hold-verbs-can-toggle': ['NXB-055', 'NXI-219', 'SFQ-B224'],
  'onboarding-and-pad-settings-survive-save': ['SFQ-B221'],
  'migration-ladder-from-v1': ['SFQ-B222'],
  'every-bound-verb-is-spoken-once': ['SFQ-B063', 'SFQ-I026'],
  'prompts-speak-the-players-device': ['SFQ-B224', 'NXI-003', 'NXI-220'],
  'the-range-teaches-all-five-powers': ['SFQ-B063'],
  // 20 more
  'a-player-can-surrender-to-the-law': ['NXB-014', 'SF-161', 'SFQ-B112'],
  'champions-arrive-with-their-rooms': ['SFQ-B056', 'NXB-017'],
  'every-roster-row-declares-its-mass-class': ['SFQ-B050', 'SF-133', 'SFQ-B022'],
  'the-combat-bed-knows-the-sector': ['SF-233', 'SF-234', 'SFQ-B198'],
  'every-cue-is-captioned': ['SF-239', 'SFQ-I079'],
  'cargo-insurance-exists': ['SFQ-B086'],
  'single-instance-poi-types-get-company': ['SFQ-B109', 'SFQ-B110'],
  'focus-loss-can-mute-and-pause': ['SFQ-B199', 'SFQ-I090'],
  'career-decisions-are-in-the-ledger': ['SFQ-B118'],
  'every-sector-has-a-named-face': ['SFQ-B101', 'SF-175'],
  'the-ending-is-announced-when-it-is-ready': ['NXB-047', 'NXI-186'],
  'save-slots-have-names-and-a-picture': ['SFQ-B207'],
  'the-scanner-speaks': ['SF-124', 'SFQ-B163'],
  'the-defense-warning-is-a-choice': ['NXB-035', 'NXI-139'],
  'the-tanker-and-the-cutter-fly': ['SF-221', 'SFQ-B098'],
  'the-corridor-hears-the-real-arrival-event': ['SFQ-B004'],
  'fuel-has-a-voice-before-it-is-gone': ['SFQ-B195', 'SF-252'],
  'the-first-hour-events-get-their-receipts': ['SFQ-B063', 'NXB-046'],
  'mission-transitions-draw-their-travel-line': ['NXB-054', 'SF-245'],
  'the-wing-explains-a-refused-order': ['SFQ-B046'],
  'nemesis-and-vengeful-returns-are-announced': ['SFQ-B114'],
  'the-first-victory-wreck-is-marked-on-the-map': ['SF-286', 'NXB-007'],
  'machine-probes-have-doors': ['SFQ-B211', 'SFQ-B217'],
  'planet-verbs-have-a-voice-and-a-shape': ['SFQ-B187'],
};
