// Additional packets across domains, written after the dedupe pass against NXB/NXI and SFQ.
export const packets = [
  {
    slug: 'a-player-can-surrender-to-the-law', domain: '06-law-factions', area: 'parity',
    title: 'A player can surrender to the law: cut engines, hold, and be taken into custody instead of dying',
    kind: 'build', lane: 'THE WORLD', routing: 'open',
    seams: ['lawSecurity.js', 'surrenderRecovery.js', 'playerDefeat.js'],
    writeSet: ['src/systems/lawSecurity.js', 'src/systems/surrenderRecovery.js', 'src/combat/playerDefeat.js', 'test/fb-player-surrender.test.mjs'],
    gap: '`combat:surrendered` is emitted only for NPCs (`pirateDisengage.js`); the surrender-and-tow recovery loop (`surrenderRecovery.js`) is rich and one-directional. A player at NETS or IMPOUND tier has three exits (break the net, fly out of the yard, die) and no way to stop fighting. NXB-014 covers lawful units standing down when an NPC surrender is accepted; this is the player\'s own surrender, which NXB-014 assumes cannot happen.',
    why: 'Failure creates content: custody is a situation (a bill, a work-off, a stolen-back hull) and death is a reload. The custody and impound paths already exist for a towed ship; a surrendered player enters them without the tow.',
    mechanism: [
      'Add a surrender verb (hold still with engines cut for 4 s inside a lawful responder\'s scan cone while wanted); the law owner emits the player variant of `combat:surrendered`, lawful fire stands down through the same authority recheck NXB-014 specifies, and the player is escorted into the impound path with the existing bill.',
      'Refuse the surrender when no lawful responder is within range or the player fires during the hold; say why through the refusal voice.',
      'Pin on seed 4242: wanted at NETS tier, surrender accepted within 6 s, no damage taken after acceptance, impound bill opened once; firing during the hold cancels it.',
    ],
    done: '`test/fb-player-surrender.test.mjs`: acceptance, stand-down, one bill, and the cancel case; `pq-151-00-wanted-tiers.test.mjs` and the impound suites stay green.',
    doNot: 'Do not let surrender clear heat for free. Do not accept surrender to pirates in this packet. Do not teleport the ship to the yard.',
    tests: ['`test/pq-151-00-wanted-tiers.test.mjs`', 'Locate impound and surrender suites with `rg surrenderRecovery test/`.'],
  },
  {
    slug: 'champions-arrive-with-their-rooms', domain: '04-crucible', area: 'fight',
    title: 'Every ten-wave champion arrives with the room its note describes, installed as arena geometry',
    kind: 'build', lane: 'THE FIGHT', routing: 'open',
    seams: ['swarmMode.js', 'survivalArena.js'],
    writeSet: ['src/data/swarmMode.js', 'src/systems/survivalArena.js', 'test/fb-champion-rooms.test.mjs'],
    gap: '`SWARM_BOSS_ROTATION` names four champions and `BOSS_ROOM_NOTES` describes a room for each; the notes are prose nobody executes. `planArenaInstall` in `survivalArena.js` already installs rooms from a plan\'s arena phase. The champion fights in whatever the wave left behind.',
    why: 'A room is the physical question a champion poses; without it the champion is a bigger crowd. The install path exists; the notes become plan data.',
    mechanism: [
      'Turn each `BOSS_ROOM_NOTES` entry into an `arenaPhase` install recipe (fields, pylons, a wreck ring, a lattice cell set) attached to the rotation row.',
      'Have the wave planner attach the champion\'s room to `plan.arenaPhase` on the champion wave; `planArenaInstall` installs it and clears it with the champion.',
      'Pin four distinct installs on seed 4242 at waves 10, 20, 30 and 40 and that the room is gone at the next wave.',
    ],
    done: '`test/fb-champion-rooms.test.mjs`: four rooms, four distinct install records, cleared after; `crucible-swarm-arena.test.mjs` and `pq-174-04-arena-laws.test.mjs` stay green.',
    doNot: 'Do not add props beyond the notes. Do not raise concurrency for the champion wave. Do not persist a room past its champion.',
    tests: ['`test/crucible-swarm-arena.test.mjs`', '`test/pq-174-04-arena-laws.test.mjs`', '`test/pq-133-04-r4-boss.test.mjs`'],
  },
  {
    slug: 'every-roster-row-declares-its-mass-class', domain: '03-fight', area: 'fight',
    title: 'Every enemy declares whether it is ammunition, moving terrain or a specialist, and the scan says so',
    kind: 'build', lane: 'THE FIGHT', routing: 'open',
    seams: ['enemies.js', 'combatDefs.js', 'targetPanel.js'],
    writeSet: ['src/data/enemies.js', 'src/systems/combat.js', 'src/ui/targetPanel.js', 'test/fb-roster-mass-class.test.mjs'],
    gap: 'The vision divides enemies into ammunition, moving terrain and specialists. The sim has the number (`THROW_CLASS_MAX_MASS` in `survivalWaves.js` decides what the rope can throw) but no roster row declares its class, so the corsair (32 t, throwable) and the reaver (60 t, not) read the same on the scan until the player tries. SFQ-B050 asks for a readable roster; this is the one field that makes it readable.',
    why: 'A derived class from mass is honest and cheap; declaring it on the row lets specialists override (a 24 t tether raider is a specialist, not ammunition) and the target panel print one word.',
    mechanism: [
      'Add `+physicalClass` to every `ENEMY_TYPES` row (ammunition / terrain / specialist), derived by a table test from mass against `THROW_CLASS_MAX_MASS` unless overridden for specialists.',
      'Copy it onto the spawned entity in `combat.js` and print it on the target panel at the reveal stage SF-133 requires (functional edit).',
      'Pin the derivation rule and that every row has a class.',
    ],
    done: '`test/fb-roster-mass-class.test.mjs`: 19/19 rows classed, derivation matches mass except declared specialists, the panel model carries the word on seed 4242.',
    doNot: 'Do not change any mass. Do not add a fourth class. Do not overclaim on an unscanned contact.',
    tests: ['`test/pq-140-02-specialists.test.mjs`', 'Locate throw-class suites with `rg THROW_CLASS_MAX_MASS test/`.'],
  },
  {
    slug: 'the-combat-bed-knows-the-sector', domain: '12-ear', area: 'presentation',
    title: 'A fight in the fringe and a fight in the core mix the same four stems differently',
    kind: 'deepening', lane: 'THE EAR', routing: 'open',
    seams: ['themeMatrix.js', 'audioSystem.js'],
    writeSet: ['src/audio/themeMatrix.js', 'src/audio/audioSystem.js', 'test/fb-combat-bed-sector.test.mjs'],
    gap: 'Four stems back four theme states, so every combat bed is one bed. `SECTOR_BEDS` and `THEME_STEM_WEIGHTS` already exist in `themeMatrix.js`, and the theme resolver already receives `sectorId` and `factionId`; the stem axis stays single. Adjacent to SF-233 (a quiet-sector bed) and SF-234 (music follows the encounter arc): this is the sector register of the combat state, not the arc.',
    why: 'New stems were rejected (assets). Weighting the existing stems by sector bed is data on an axis the matrix already declares.',
    mechanism: [
      'Give `SECTOR_BEDS` entries a stem-weight vector consumed by `resolveThemeMatrix` alongside the state weights; core sectors lean on the harmonic stems, fringe on the percussive ones.',
      'Keep the state hold hysteresis; the sector weights change only on `sector:enter`.',
      'Pin that combat in Helios and combat in Sker Haven on seed 4242 produce different stem weight vectors and identical state sequences.',
    ],
    done: '`test/fb-combat-bed-sector.test.mjs`: two sectors, two weight vectors, same state machine; `pq-158-03-themes.test.mjs` stays green.',
    doNot: 'Do not add stems. Do not change the state thresholds. Do not switch beds mid-fight.',
    tests: ['`test/pq-158-03-themes.test.mjs`'],
  },
  {
    slug: 'every-cue-is-captioned', domain: '15-professional', area: 'professionalism',
    title: 'Every gameplay cue the game can play has a caption record, checked by a test that walks the recipes',
    kind: 'build', lane: 'THE EAR', routing: 'open',
    seams: ['captions.js', 'audioRecipes.js'],
    writeSet: ['src/ui/captions.js', 'test/fb-every-cue-captioned.test.mjs'],
    gap: '`everyVoicedBarkCaptioned` proves every voiced bark has a caption; `ACCESSIBILITY_AUDIO_CUE_TABLE` covers the accessibility cues. Nothing proves the 258 `RECIPES` ids that `audioSystem.js` plays as gameplay cues (kill tiers, refusals, snare and seed voices, the new loops from this bank) each map to a caption. Adjacent to SF-239 (captions carry semantics without becoming a log): this is coverage, not wording.',
    why: 'Accessibility is not optional, and every ear packet in this bank adds cues. A coverage test keeps them honest without a caption redesign.',
    mechanism: [
      'Build a caption map keyed by recipe id for gameplay-class recipes (skip UI blips and layers), with the event word and the urgency band; default a missing entry to the recipe\'s family caption so nothing is silent to a deaf player.',
      'Add the walk test: every recipe id referenced by `audioSystem.js` resolves to a caption record.',
      'Keep the caption queue\'s existing rate limit so a dense fight does not become a log.',
    ],
    done: '`test/fb-every-cue-captioned.test.mjs`: 100% of referenced gameplay recipes captioned; `pq-165-01-captions.test.mjs` stays green.',
    doNot: 'Do not caption UI blips. Do not raise the caption rate limit. Do not restyle captions (ORRERY).',
    tests: ['`test/pq-165-01-captions.test.mjs`', '`test/wave-g3-fight-captions.test.mjs`'],
  },
  {
    slug: 'cargo-insurance-exists', domain: '07-economy', area: 'parity',
    title: 'Cargo insurance is a real station service, not a line of bar fiction',
    kind: 'build', lane: 'THE LONG GAME', routing: 'open',
    seams: ['economy.js', 'serviceQuotes.js', 'playerDefeat.js'],
    writeSet: ['src/systems/economy.js', 'src/ui/station/serviceQuotes.js', 'src/combat/playerDefeat.js', 'test/fb-cargo-insurance.test.mjs'],
    gap: 'Hull insurance exists (`INSURANCE_DEFAULTS`, purchasable, honoured at death). `src/ui/station/barContacts.js` writes fiction about cargo insurance and no such service exists; a death still loses 50% of non-persistent cargo with no way to cover it.',
    why: 'Mature parity where it fits: a per-trip cargo policy priced on manifest value and route danger, paid out at the recovery dock, single writer economy.',
    mechanism: [
      'Add a `+cargo_insurance` service in `handleService` priced from manifest value times the sector danger from `sectorSim`, valid until the next dock; the economy is the only credit writer.',
      'In `buildRecoveryPlan`, pay out the covered fraction of lost cargo value at the recovery dock and name it in the coverage sentence.',
      'Pin price, payout, single-trip expiry and no double payout after load.',
    ],
    done: '`test/fb-cargo-insurance.test.mjs`: policy bought, death pays the covered fraction once, expired policy pays nothing; `station-services.test.mjs` stays green.',
    doNot: 'Do not insure contraband. Do not let the policy survive a dock. Do not add a claims screen.',
    tests: ['`test/station-services.test.mjs`', 'Locate defeat suites with `rg buildRecoveryPlan test/`.'],
  },
  {
    slug: 'single-instance-poi-types-get-company', domain: '05-world', area: 'world',
    title: 'The research, fab, debris and wormhole POI types exist more than once, each with its family\'s verb',
    kind: 'build', lane: 'THE WORLD', routing: 'open',
    seams: ['sectors.js', 'frontierRegions', 'poiBehaviorFamilies.js'],
    writeSet: ['src/data/sectors.js', 'src/data/frontierRegions/east.js', 'src/data/frontierRegions/north.js', 'src/data/poiBehaviorFamilies.js', 'test/fb-poi-types-company.test.mjs'],
    gap: 'POI type counts: beacon 10, cache 8, derelict 6, wreck 5, anomaly 5, colony 4, blackmarket 4, and one each of wormhole, research, fab and debris. The behaviour families (`poiBehaviorFamilies.js`, seven families) give a research POI a plan and a verb; a type that exists once is a mechanism that supports many with one instance. The brief names this gap class directly.',
    why: 'More POIs of the common types were rejected (density is not identity). One more instance each of the four singletons, placed where the sector\'s way of life explains it, with the family verb already authored.',
    mechanism: [
      'Author a second research POI (a frontier research station\'s field lab), a second fab (the Forge\'s outlying yard), a second debris field (Ashfall) and a second wormhole candidate (Veil\'s far side) in the sector data.',
      'Bind each to its behaviour family so the plan/readout path (see @the-poi-you-are-inside-shows-its-plan) applies.',
      'Pin type counts ≥ 2 for all types and that each new POI resolves a family plan on seed 4242.',
    ],
    done: '`test/fb-poi-types-company.test.mjs`: no POI type with count 1, four family plans resolved; `living-poi-behaviors.test.mjs` and `world-one-offs.test.mjs` stay green.',
    doNot: 'Do not add a fifth POI type. Do not place a POI without a family. Do not touch the ending-C wormhole rules.',
    tests: ['`test/living-poi-behaviors.test.mjs`', '`test/world-one-offs.test.mjs`'],
  },
  {
    slug: 'focus-loss-can-mute-and-pause', domain: '15-professional', area: 'parity',
    title: 'Losing window focus can mute the game and pause the sim, each behind its own setting',
    kind: 'build', lane: 'THE MACHINE', routing: 'open',
    seams: ['presentationRunner.js', 'audioSystem.js', 'gameState.js'],
    writeSet: ['src/core/presentationRunner.js', 'src/audio/audioSystem.js', 'src/core/gameState.js', 'src/ui/screens/settings.js', 'test/fb-focus-loss-mute-pause.test.mjs'],
    gap: '`input.js` releases held controls on blur and `presentationRunner.js` throttles on `visibilitychange`, but nothing mutes audio or pauses the sim when the window loses focus. `contextResourceLifecycle.js` already proves a sim hold through the time-effects ledger (`pauseSimForContextLoss`).',
    why: 'Two mature options with the mechanism already present for one of them. The hold must use the same ledger so the sim clock and determinism are untouched.',
    mechanism: [
      'Add `+audio.muteOnFocusLoss` and `+gameplay.pauseOnFocusLoss` to `defaultSettings()` with Settings rows; on blur, mute through the master gain (loop state preserved, NXI-206) and hold the sim through the existing time-effects minimum ledger; restore on focus.',
      'Never pause inside the Crucible results or a save write; the hold waits for the boundary.',
      'Pin both toggles and that a hold during a fight resumes the same tick with identical state.',
    ],
    done: '`test/fb-focus-loss-mute-pause.test.mjs`: mute restores loops, pause resumes deterministically; `context-resource-lifecycle.test.mjs` stays green.',
    doNot: 'Do not advance the sim clock during the hold. Do not destroy loop state on mute. Do not pause the browser-tab throttling path differently from the Electron path.',
    tests: ['`test/context-resource-lifecycle.test.mjs`', '`test/input-lifecycle.test.mjs`'],
  },
  {
    slug: 'career-decisions-are-in-the-ledger', domain: '10-story-missions', area: 'longgame',
    title: 'Career origins offered, chosen or declined and ladder steps are recorded in the ship ledger',
    kind: 'wire', lane: 'THE LONG GAME', routing: 'open',
    seams: ['haulerOriginSystem.js', 'ladderShared.js', 'shipLedger.js'],
    writeSet: ['src/careers/origins/haulerOriginSystem.js', 'src/careers/ladders/ladderShared.js', 'src/systems/shipLedger.js', 'test/fb-career-ledger.test.mjs'],
    gap: '`career:origin:offered`, `career:origin:declined` and the ladder choose/abandon/recover events are emitted with no listener; the ship ledger has nine entry types and none for the career the player chose or refused. The career becomes the ending\'s origin identity and leaves no trace in the player\'s own record.',
    why: 'The ledger is the memory surface; one entry type per career decision, projected from events the systems already emit.',
    mechanism: [
      'Add a `career` entry type in the ledger templates; subscribe the ledger builder to the origin and ladder events (the constant-named ladder events through `ladderShared.js`).',
      'Record offered-and-declined as one entry so the player can read the road not taken.',
      'Pin one entry per decision on a scripted seed-4242 career walk and no duplicates after load.',
    ],
    done: '`test/fb-career-ledger.test.mjs`: offered, declined, chosen and one ladder step each produce one entry; `career-ladders-contract.test.mjs` stays green.',
    doNot: 'Do not branch careers on ledger state. Do not add a career screen. Do not exceed the ledger cap.',
    tests: ['`test/career-ladders-contract.test.mjs`', '`test/pq146-02-titles-ledger-bark.test.mjs`'],
  },
  {
    slug: 'every-sector-has-a-named-face', domain: '05-world', area: 'world',
    title: 'The five sectors without a named lane contact get one, stamped on their traffic',
    kind: 'build', lane: 'THE WORLD', routing: 'open',
    seams: ['laneContacts.js', 'traffic.js'],
    writeSet: ['src/data/laneContacts.js', 'test/fb-named-face-every-sector.test.mjs'],
    gap: '`NAMED_LANE_CONTACTS` authors 21 named civilian identities across 20 sectors and `traffic.js` stamps them deterministically onto ambient hulls; ashfall_reach, orcus_shadow, phoebe_echo, triton_wake and sedna_dark have none. Five sectors have no face. Adjacent to SF-175 (a moving clue that belongs to a real worker).',
    why: 'Five data rows on a stamping path that already works; each name carries a job and a hail so the sector\'s way of life has a voice.',
    mechanism: [
      'Author one named contact per missing sector with a role that matches the sector (a vael research courier, a quiet-sector tanker), a hail line and a memory hook the station contact system can use.',
      'Pin that every sector resolves at least one named contact and that the stamp is deterministic on seed 4242.',
    ],
    done: '`test/fb-named-face-every-sector.test.mjs`: 24/24 sectors, deterministic stamp; `npc-jobs-runtime-occupational-heads.test.mjs` stays green.',
    doNot: 'Do not add roles. Do not stamp two names on one hull.',
    tests: ['`test/npc-jobs-runtime-occupational-heads.test.mjs`', 'Locate lane-contact suites with `rg laneContacts test/`.'],
  },
  {
    slug: 'the-ending-is-announced-when-it-is-ready', domain: '10-story-missions', area: 'longgame',
    title: 'The finale-ready signal and the written archive reach the player as a comms beat and a codex entry',
    kind: 'wire', lane: 'THE LONG GAME', routing: 'open',
    seams: ['story.js', 'comms.js', 'codex.js'],
    writeSet: ['src/systems/story.js', 'src/ui/comms.js', 'src/ui/screens/codex.js', 'test/fb-ending-announced.test.mjs'],
    gap: '`endgame:finaleReady` is emitted with the written ending archive and `endgame:archive` with the archive record; neither has a listener. A player who has qualified for an ending learns it from the eligibility gate at the board, not from the world. NXB-047 tests the endings\' permissions across return visits; NXI-186 forbids re-presenting a resolved ending; neither announces readiness.',
    why: 'The story owner already composes the archive; two consumers make it a moment: one comms line when the finale becomes ready, one codex Archive entry when the archive is written.',
    mechanism: [
      'Subscribe `comms.js` to `endgame:finaleReady` for a once-per-save comms popup naming the reachable ending(s), gated by the voice arbiter.',
      'Subscribe the codex Archive tab data path to `endgame:archive` so the written archive appears without a reload (functional edit).',
      'Pin once-only announcement across save/load and that a resolved ending never re-announces.',
    ],
    done: '`test/fb-ending-announced.test.mjs`: one comms line on readiness, one archive entry, none after resolution; `ending-choice-c-route.test.mjs` stays green.',
    doNot: 'Do not add a new ending. Do not re-present a resolved ending. Do not interrupt combat voice.',
    tests: ['`test/ending-choice-c-route.test.mjs`', '`test/post-ending-replay-chains.test.mjs`'],
  },
  {
    slug: 'save-slots-have-names-and-a-picture', domain: '15-professional', area: 'parity',
    title: 'Save slots carry a player-given label and a small still from the moment of saving',
    kind: 'build', lane: 'THE INSTRUMENT', routing: 'ORRERY lane',
    seams: ['saveLoad.js', 'saveSystem.js'],
    writeSet: ['src/ui/screens/saveLoad.js', 'src/save/saveSystem.js', 'test/fb-save-slot-label-still.test.mjs'],
    gap: 'Five slots (quick, auto, four numbered) with no names and no picture; `slotMetaFromEnvelope` in `saveSystem.js` is where a label and a thumbnail would attach. Every mature save screen shows where you were.',
    why: 'Pure UI plus one metadata field; the thumbnail is a small JPEG captured from the live canvas at save time (a product feature, not a verification still).',
    mechanism: [
      'Extend `slotMetaFromEnvelope` with `label` and a bounded thumbnail (≤ 24 KB) captured off the present canvas at save time; both optional and excluded from the envelope checksum scope for backward compatibility.',
      'Add a label input and the thumbnail to the slot card; walk the screen with `node scripts/ui-bench.mjs --walk`.',
      'Pin that old envelopes without the fields still load and that the thumbnail never exceeds the bound.',
    ],
    done: '`test/fb-save-slot-label-still.test.mjs`: label round-trips, thumbnail bounded, old envelopes load; `save-envelope-fidelity.test.mjs` stays green.',
    doNot: 'Do not grow the envelope beyond the bound. Do not capture during a present. Do not make the label required.',
    tests: ['`test/save-envelope-fidelity.test.mjs`', 'Run `node scripts/check-save-load-slot-trust.mjs`.'],
  },
  {
    slug: 'the-scanner-speaks', domain: '05-world', area: 'world',
    title: 'A ghost that escapes, a bearing that lands and a wreck that reveals each have a voice and a mark',
    kind: 'wire', lane: 'THE WORLD', routing: 'open',
    seams: ['scanner.js', 'audioSystem.js', 'worldCueRecipes.js'],
    writeSet: ['src/systems/scanner.js', 'src/audio/audioSystem.js', 'src/render/vfx/worldCueRecipes.js', 'test/fb-scanner-speaks.test.mjs'],
    gap: '`scanner:ghostEscaped`, `anomaly:bearing`, `band:bearingReceipt`, `scan:wreckRevealed` and `scan:debrisCache` are emitted with no listener. Seven scan voices exist for the pulse and classification stages; the three most consequential scanner outcomes (a contact slipped away, a bearing counted toward a fix, a wreck opened its story) are silent and unmarked.',
    why: 'The survey cue family in `worldCueRecipes.js` already composes pulse/resolved/classified; three variants and three recipe routes close it.',
    mechanism: [
      'Add `survey-escaped`, `survey-bearing` (pitched by bearing count toward the required pings) and `survey-revealed` variants to the world cue recipes and route the five events.',
      'Play the bearing ping through the existing scan voice at a pitch step per bearing; the escape gets a falling tone and the contact list note.',
      'Pin one cue per event on a seed-4242 anomaly triangulation and a ghost escape.',
    ],
    done: '`test/fb-scanner-speaks.test.mjs`: five events, five cues, bearing pitch rises with count; `world-cue-recipes.test.mjs` stays green.',
    doNot: 'Do not reveal the anomaly position before the required bearings. Do not add a scanner screen.',
    tests: ['`test/world-cue-recipes.test.mjs`', '`test/ghost-bearing-choice.test.mjs`', '`test/seam-scan-reveal.test.mjs`'],
  },
  {
    slug: 'the-defense-warning-is-a-choice', domain: '08-industry', area: 'longgame',
    title: 'A claim defense warning is a prompt with go, ignore or delegate, not only a headline',
    kind: 'build', lane: 'THE LONG GAME', routing: 'open',
    seams: ['claims.js', 'galaxyMap.js', 'encounterChoicePrompt.js'],
    writeSet: ['src/systems/claims.js', 'src/ui/encounterChoicePrompt.js', 'test/fb-defense-warning-choice.test.mjs'],
    gap: '`claims.js` listens for `claim:defenseIgnore`, which nothing emits, and emits `claim:defenseWarning` with no listener. The galaxy map shows a raid marker. The player has no explicit ignore verb and no delegate verb (a supported depot already summons a patrol beat). NXB-035 makes the raid outcome identical whether the player arrives or not; this is the decision before that outcome.',
    why: 'The encounter choice prompt is the event-only prompt precedent; three doors, engine re-validates. Ignoring explicitly settles the defense as ignored (the listener exists) instead of by timeout.',
    mechanism: [
      'On `claim:defenseWarning`, open the choice prompt with go (waypoint set), ignore (emits `claim:defenseIgnore`), delegate (spends the depot\'s patrol rotation early if supported).',
      'Pin the three outcomes on seed 4242 and that delegate is refused without a supported depot, with the reason.',
    ],
    done: '`test/fb-defense-warning-choice.test.mjs`: three doors, refusal reason, one prompt per warning; `claim-defense.test.mjs` stays green.',
    doNot: 'Do not change raid odds. Do not add a claims panel. Do not let the prompt settle the raid itself.',
    tests: ['`test/claim-defense.test.mjs`', '`test/belt-claim-jumpers.test.mjs`'],
  },
  {
    slug: 'the-tanker-and-the-cutter-fly', domain: '05-world', area: 'world',
    title: 'The packaged volatiles tanker and inspection cutter are fielded with their jobs',
    kind: 'wire', lane: 'THE WORLD', routing: 'open',
    seams: ['occupationalTrafficCraft.js', 'traffic.js'],
    writeSet: ['src/data/occupationalTrafficCraft.js', 'src/systems/traffic.js', 'test/fb-tanker-cutter-fielded.test.mjs'],
    gap: '`OCCUPATIONAL_TRAFFIC_CRAFT` maps five packaged hulls to job kinds and its own header documents `volatiles_tanker` and `inspection_cutter` as packaged but deliberately unfielded; `traffic.js` zeroes the `tanker` and `customs` ambient weights outside Helios. Two authored working craft never fly. Adjacent to SF-221 (a convoy readable as a working group).',
    why: 'Two data rows un-zero the roles; the tanker takes the hauler graph with a volatile lot and the cutter takes the patrol graph with the customs scan verb.',
    mechanism: [
      'Add the two rows; give tankers a volatile manifest (so `cargo:volatileCryo` and friends fire on a spill) and cutters the inspection graph, weighted into sectors with refuel or customs services.',
      'Pin that both spawn on seed 4242 in the right sectors and that their job signature profiles resolve.',
    ],
    done: '`test/fb-tanker-cutter-fielded.test.mjs`: both fielded, signatures resolve, no spawn in sectors without their service; `npc-jobs-runtime-occupational-heads.test.mjs` stays green.',
    doNot: 'Do not raise ambient counts. Do not add hulls. Do not field them in high-sec cores as ambient pirates\' prey without the escort mix.',
    tests: ['`test/npc-jobs-runtime-occupational-heads.test.mjs`', '`test/traffic-role-mix-reads-contents.test.mjs`'],
  },
  {
    slug: 'the-corridor-hears-the-real-arrival-event', domain: '05-world', area: 'professionalism',
    title: 'The docking corridor clears its far-quiet latch on the sector event the world actually emits',
    kind: 'CHECK', lane: 'THE WORLD', routing: 'open',
    seams: ['dockingCorridor.js'],
    writeSet: ['src/systems/dockingCorridor.js', 'test/fb-corridor-sector-enter.test.mjs'],
    gap: '`src/systems/dockingCorridor.js` subscribes its far-quiet clear to `sector:entered`; the world emits `sector:enter`. The clear-on-arrival never fires, so the corridor\'s far-quiet state can survive a jump into Helios.',
    why: 'Reproduce first, then a one-token fix with a test that pins the event name against the world\'s emit.',
    mechanism: [
      'Reproduction gate: on seed 4242 set the far-quiet state in Ceres, jump to Helios, assert the corridor is still far-quiet on arrival (today).',
      'Fix: subscribe to `sector:enter`; keep `sector:exit`, `game:new`, `save:loaded`.',
      'Pin the reproduction as the test so a renamed event fails loudly.',
    ],
    done: '`test/fb-corridor-sector-enter.test.mjs`: far-quiet clears on arrival; `docking-corridor-far-quiet-latch.test.mjs` stays green.',
    doNot: 'Do not add a `sector:entered` alias to the world. Do not change the corridor\'s quiet radius.',
    tests: ['`test/docking-corridor-far-quiet-latch.test.mjs`', '`test/station-docking-corridor.test.mjs`'],
  },
  {
    slug: 'fuel-has-a-voice-before-it-is-gone', domain: '12-ear', area: 'presentation',
    title: 'Low fuel is a two-stage voice: a reserve-crossing bed, then an empty sting, never a menu beep',
    kind: 'build', lane: 'THE EAR', routing: 'open',
    seams: ['audioSystem.js', 'fuelReserveWarning.js', 'audioRecipes.js'],
    writeSet: ['src/audio/audioSystem.js', 'src/data/audioRecipes.js', 'src/ui/fuelReserveWarning.js', 'test/fb-fuel-voice.test.mjs'],
    gap: '`fuel:empty` maps to the generic `alert` cue (`sfx_ui_alert`); the code comment admits there was no sound before. There is no cue before empty although `fuelReserveWarning.js` already detects the reserve crossing as a clean edge. A run-ending state gets a menu beep.',
    why: '`HULL_BREACH_MIX` is the precedent for a state that changes the mix rather than firing a beep; the reserve bed follows it and the empty sting is one authored synth recipe.',
    mechanism: [
      'On the reserve downward crossing (the warning\'s existing edge), start a low reserve bed on the ambient bus that ends on the upward crossing; on `fuel:empty`, play an authored `+sfx_fuel_empty` sting and hold a thinner mix until refuel.',
      'Route through the caption table (see @every-cue-is-captioned).',
      'Pin the two edges and silence after refuel on seed 4242.',
    ],
    done: '`test/fb-fuel-voice.test.mjs`: bed starts and stops on the crossings, sting once on empty, mix restored on refuel; `fuel-reserve-warning.test.mjs` stays green.',
    doNot: 'Do not add samples. Do not beep every tick below reserve. Do not touch fuel numbers.',
    tests: ['`test/fuel-reserve-warning.test.mjs`', '`test/audio-wanted-heat.test.mjs`'],
  },
  {
    slug: 'the-first-hour-events-get-their-receipts', domain: '16-teach', area: 'hands',
    title: 'The Range prompt, the first-hour sentence and the rescue beats reach a consumer',
    kind: 'wire', lane: 'THE HAND', routing: 'open',
    seams: ['onboarding.js', 'promptDeck.js', 'storeSentence.js'],
    writeSet: ['src/systems/onboarding.js', 'src/ui/promptDeck.js', 'src/onboarding/storeSentence.js', 'test/fb-first-hour-receipts.test.mjs'],
    gap: '`onboarding:rangePrompt` is emitted (and scripted in two scenario files) with no listener, so the Range is never offered when a verb is refused repeatedly. `firsthour:sentence` and the rescue beats emit into nothing outside telemetry. The first hour computes its own receipts and shows none.',
    why: 'The prompt deck is the one-voice prompt owner; the store sentence module already formats the sentence. Two subscriptions.',
    mechanism: [
      'Subscribe `promptDeck.js` to `onboarding:rangePrompt` (offer the Range rung for the refused verb; decline is remembered per profile).',
      'Publish `firsthour:sentence` through the store-sentence formatter to the dock arrival card once.',
      'Pin the offer after three refusals on seed 4242 and the single sentence card.',
    ],
    done: '`test/fb-first-hour-receipts.test.mjs`: one Range offer, one sentence card, decline remembered; onboarding scenario tests stay green.',
    doNot: 'Do not force the Range. Do not add a tutorial screen. Do not repeat the sentence.',
    tests: ['Locate onboarding suites with `rg onboarding test/ -l` and the scenario runner for `missing-three.scenario.json`.'],
  },
  {
    slug: 'mission-transitions-draw-their-travel-line', domain: '10-story-missions', area: 'longgame',
    title: 'A set-piece transition draws its travel line on the map and the HUD instead of emitting into nothing',
    kind: 'wire', lane: 'THE LONG GAME', routing: 'open',
    seams: ['missions.js', 'routeRibbon.js', 'hud.js'],
    writeSet: ['src/systems/missions.js', 'src/presentation/routeRibbon.js', 'test/fb-set-piece-travel-line.test.mjs'],
    gap: '`mission:setPieceTransition` and `mission:setPieceTravelLine` are emitted with no listener; the authored set pieces know where the next beat is and the player gets no line. The route ribbon already draws a travel line for engaged routes.',
    why: 'One consumer: the route ribbon draws the set-piece\'s travel line as a secondary ribbon until the transition completes; NXB-054 keeps knowledge distinct from the active route, so this is a second-destination ribbon, never the active route.',
    mechanism: [
      'Subscribe the route ribbon presentation to `mission:setPieceTravelLine` and draw a distinct secondary ribbon; clear on `mission:setPieceTransition` or completion.',
      'Pin one ribbon per travel line and its clearing on seed 4242\'s beat-1 set piece.',
    ],
    done: '`test/fb-set-piece-travel-line.test.mjs`: ribbon appears and clears, the active route is untouched; `pq-032-00-set-pieces.test.mjs` stays green.',
    doNot: 'Do not set the active route. Do not add a map layer file. Do not draw for unaccepted offers.',
    tests: ['`test/pq-032-00-set-pieces.test.mjs`', '`test/navigation-stale-route.test.mjs`'],
  },
  {
    slug: 'the-wing-explains-a-refused-order', domain: '03-fight', area: 'fight',
    title: 'A wingman order that is blocked or converted says why on the radial, in the moment',
    kind: 'wire', lane: 'THE FIGHT', routing: 'open',
    seams: ['automation.js', 'wingmanRadial.js'],
    writeSet: ['src/systems/automation.js', 'src/ui/wingmanRadial.js', 'test/fb-wing-order-refusal.test.mjs'],
    gap: '`wingOrder:blocked`, `wingOrder:converted` and `wingOrder:status` are emitted from `automation.js` with no listener. A player orders a wingman, the order is refused or turned into something else, and the radial shows nothing. SFQ-B046 wants morale to change commitment rather than dialogue; this is the order receipt, not morale.',
    why: 'The radial is the order surface; a one-word reason on the refused slot is the minimum receipt and it exists in the payload.',
    mechanism: [
      'Subscribe `wingmanRadial.js` to the three events: blocked shows the reason word for 2 s on the slot; converted shows the new order; status updates the slot glyph (functional edit).',
      'Pin one receipt per event on a scripted refusal on seed 4242.',
    ],
    done: '`test/fb-wing-order-refusal.test.mjs`: three receipts, correct slots; wingman suites stay green.',
    doNot: 'Do not change order rules. Do not add a bark for refusals. Do not restyle the radial (ORRERY).',
    tests: ['Locate wingman suites with `rg wingmanRadial test/` and `rg wingOrder test/`.'],
  },
  {
    slug: 'nemesis-and-vengeful-returns-are-announced', domain: '05-world', area: 'world',
    title: 'A vengeful return is announced through the ace memory voice, not only felt through spawns',
    kind: 'wire', lane: 'THE WORLD', routing: 'open',
    seams: ['e1EncounterRuntime.js', 'aceMemory.js', 'barkDirector.js'],
    writeSet: ['src/systems/e1EncounterRuntime.js', 'src/systems/aceMemory.js', 'test/fb-vengeful-return-announced.test.mjs'],
    gap: '`moralMemory:vengefulReturn` is emitted from `e1EncounterRuntime.js` with no listener anywhere. The ace memory already speaks remembered barks on return (`rememberedBarkFor`) and posts news on transitions; a return driven by moral memory (a spared pirate coming back angry) arrives without the sentence that explains it. SFQ-B114 wants rivals to change a countermeasure on return; this is the announcement of the return itself.',
    why: 'The ace memory owns return voice; one subscription routes the moral-memory return into it.',
    mechanism: [
      'Subscribe `aceMemory.js` to `moralMemory:vengefulReturn` and publish the remembered bark plus a cited news line naming the earlier mercy.',
      'Pin one bark and one line per return on a seed-4242 spare-then-return script.',
    ],
    done: '`test/fb-vengeful-return-announced.test.mjs`: one bark, one cited line, none for a first encounter; ace memory suites stay green.',
    doNot: 'Do not change return odds. Do not announce for unspared aces.',
    tests: ['Locate ace suites with `rg aceMemory test/`; `test/survivor-pod-causal.test.mjs` for the mercy path.'],
  },
  {
    slug: 'the-first-victory-wreck-is-marked-on-the-map', domain: '05-world', area: 'world',
    title: 'Wreck ecology events mark and unmark the map: a seeded wreck, a scavenger at work, a wreck gone',
    kind: 'wire', lane: 'THE WORLD', routing: 'open',
    seams: ['aftermathWrecks.js', 'galaxyMap.js', 'marketNews.js'],
    writeSet: ['src/systems/aftermathWrecks.js', 'src/ui/galaxyMap.js', 'src/ui/marketNews.js', 'test/fb-wreck-ecology-marked.test.mjs'],
    gap: '`wreckEcology:seeded`, `wreckEcology:scavenged`, `wreckEcology:departed` and `wreckEcology:decayed` are emitted with no listener. The player\'s own kills become wrecks with scavengers and a decay clock and none of it reaches the map or the news. Adjacent to SF-286 (first victory becomes the first useful wreck) and NXB-007 (one kill, one aftermath): this is the ecology\'s visibility after the aftermath is settled.',
    why: 'A wreck the player made is a place; the map marker and a news line are the two consumers that make it one.',
    mechanism: [
      'Subscribe the galaxy map\'s marker data path to seeded/decayed (add/remove a wreck marker with the cause) and `marketNews.js` to scavenged/departed (a cited line).',
      'Pin marker lifecycle and two lines on a seed-4242 kill→scavenge→decay script.',
    ],
    done: '`test/fb-wreck-ecology-marked.test.mjs`: marker appears and clears, two cited lines; `pq-154-01-wreck-ecology.test.mjs` stays green.',
    doNot: 'Do not mark NPC-vs-NPC wrecks the player never saw. Do not add a wreck screen.',
    tests: ['`test/pq-154-01-wreck-ecology.test.mjs`', '`test/aftermath-scavenger-work-loop.test.mjs`'],
  },
  {
    slug: 'machine-probes-have-doors', domain: '14-machine', area: 'machine',
    title: 'The heap-leak, main-thread and Crucible CPU probes get npm doors and a one-line index',
    kind: 'polish', lane: 'THE MACHINE', routing: 'open',
    seams: ['package.json', 'probe-heap-verify.mjs'],
    writeSet: ['package.json', 'scripts/probe-heap-verify.mjs', 'scripts/probe-main-thread-profile.mjs', 'scripts/probe-crucible-cpu-profile.mjs', 'docs/VALIDATION_WORKFLOW.md', 'test/fb-probe-doors.test.mjs'],
    gap: '77 of 99 `scripts/probe-*.mjs` have no npm script. The only forced-GC leak instrument (`probe-heap-verify.mjs`), the main-thread profiler and the Crucible CPU profile are unreachable by name, so an agent asked "is it leaking" reinvents the probe. SFQ-B211 and SFQ-B217 diagnose a hitch and a leak; these are the doors they would use.',
    why: 'Doors, not new probes: three npm scripts, a bounded default case count, and one paragraph in the validation ladder.',
    mechanism: [
      'Add `+probe:heap-verify`, `+probe:main-thread` and `+probe:crucible-cpu` npm scripts with bounded defaults; document them in the validation ladder\'s router table.',
      'Pin with a test that every `probe:*` npm script points at an existing file.',
    ],
    done: '`test/fb-probe-doors.test.mjs`: every probe script resolves; the three doors run to completion in under a minute with their default bounds on the play machine.',
    doNot: 'Do not wire all 77. Do not put a probe in the baseline gate. Do not change probe defaults beyond bounding.',
    tests: ['Locate probe contract suites with `rg "probe-" test/ -l | head`.'],
  },
  {
    slug: 'planet-verbs-have-a-voice-and-a-shape', domain: '11-vfx-picture', area: 'presentation',
    title: 'Skimming, harvesting, plunging and the recovery burn at the Anvil have voices and cues',
    kind: 'wire', lane: 'THE PICTURE', routing: 'open',
    seams: ['planetRuntime.js', 'worldCueRecipes.js', 'audioSystem.js'],
    writeSet: ['src/systems/planetRuntime.js', 'src/render/vfx/worldCueRecipes.js', 'src/audio/audioSystem.js', 'test/fb-planet-verbs-cues.test.mjs'],
    gap: 'Planets are on in production (`PRODUCTION_FEATURES.planets.enabled`), the Anvil has a band state machine, skim harvest and staged reentry, and `planet:harvest`, `planet:harvestDenied`, `planet:collector`, `planet:plungeStage` and `planet:recoveryBurn` are emitted with no listener. The HUD polls planet state (`planetHud.js`); the ear and the picture get nothing.',
    why: 'The travel cue family is the precedent (nine composed cues); five planet variants and five audio routes make a whole feature audible.',
    mechanism: [
      'Add planet variants to `worldCueRecipes.js` (skim intake, harvest deposit, plunge stage ring, recovery burn plume) and route the five events; deny goes to the refusal voice.',
      'Pin one cue per event on a seed-4242 skim→plunge→recover script.',
    ],
    done: '`test/fb-planet-verbs-cues.test.mjs`: five events, five cues, deny routed to the refusal voice; `planet-vertical.test.mjs` stays green.',
    doNot: 'Do not change band physics. Do not add particles beyond the cue budgets.',
    tests: ['`test/planet-vertical.test.mjs`', '`test/depth-program-w1-planet-states.test.mjs`', '`test/world-cue-recipes.test.mjs`'],
  },
];
