// THE HAND (01) and the Massline (02). Evidence: the hand sweep + tools/inspect-output.md.
export const packets = [
  // ───────────────────────────── 01-hand ─────────────────────────────
  {
    slug: 'pursuit-slot-assist-is-reachable', domain: '01-hand', area: 'hands',
    title: 'The pursuit-slot assist that exists becomes a reachable assisted-flight option',
    kind: 'wire', lane: 'THE HAND', routing: 'open',
    seams: ['flightV3.js', 'pursuitSlotAssist.js'],
    writeSet: ['src/systems/flightV3.js', 'src/core/flight/pursuitSlotAssist.js', 'src/core/gameState.js', 'test/fb-pursuit-slot-reachable.test.mjs'],
    gap: '`src/core/flight/pursuitSlotAssist.js` ships `createPursuitSlot`, `adjustPursuitSlot` and `stepPursuitSlotAssist` with a full tuning table, and no `src/` file calls them (`main.js` only sanitizes `state.input.pursuitSlot` on reset). Its sibling `stepAnchorRelativeOrbitAssist` is live from `flightV3.js`. A whole assist is authored and unreachable.',
    why: 'A new chase autopilot was rejected. The assist exists and is deterministic; calling it from the site that already steps orbit assist, under a setting the player can turn off, is surfacing, not inventing.',
    mechanism: [
      'Call `stepPursuitSlotAssist` from the `flightV3.js` site that steps orbit assist, active only when the player holds a lock on a moving target and the new gameplay setting `+gameplay.pursuitSlotAssist` is on (default off, so goldens are untouched).',
      'The assist steers toward the slot with thrust the hull has; it never writes velocity or clamps earned speed (invariant pinned in the test).',
      'Surface the option beside the existing orbit-assist row (task-needed functional settings edit).',
    ],
    done: 'Seed 4242 fixed scenario, NPC fleeing on a curve for 20 s: time-in-slot with the assist on is at least double time-in-slot with it off, player speed never exceeds what thrust can produce, and `test/fb-pursuit-slot-reachable.test.mjs` pins both numbers; goldens unchanged with the default off.',
    doNot: 'Do not clamp momentum or add drag. Do not make it default on. Do not give the target any counter-steer.',
    tests: ['`test/propulsion-spawned-ship-authority.test.mjs`', 'Locate orbit-assist suites with `rg orbitAssist test/` and name what you verified.'],
  },
  {
    slug: 'the-travel-drive-is-taught-and-shelved', domain: '01-hand', area: 'hands',
    title: 'The second speed is taught once and has a place on the verb shelf',
    kind: 'build', lane: 'THE HAND', routing: 'open',
    seams: ['missingThree.js', 'powerRail.js', 'input.js'],
    writeSet: ['src/onboarding/missingThree.js', 'src/ui/hudAttention.js', 'src/ui/powerRail.js', 'test/fb-travel-drive-taught.test.mjs'],
    gap: '`travelBurn` (NumLock/KeyH, pad L3) drives a full state machine (`TRAVEL_DRIVE_STATES` spooling/engaged/cooldown) and is rebindable, but `onboarding.js` never names it, `TAUGHT_FLIGHT_ACTIONS` omits it, and the power rail has no slot for it. The vision\'s "two speeds coexist" has one speed taught.',
    why: 'A tutorial screen was rejected (teaching is spoken once, in play). `MISSING_THREE_BEATS` already teaches boost, stroke and the three fields with one line each; a row for the drive uses the same rail. The shelf slot is a readout of a state that already exists.',
    mechanism: [
      'Add a `travelBurn` beat to `MISSING_THREE_BEATS` gated on the first long straight (speed above the governed combat speed for 3 s with no hostile), with a `MISSING_THREE_BEAT_LINES` line in `hudAttention.js` that names the key from the live binding.',
      'Add a rail slot fed from `inp.travelDrive` state (spooling/engaged/cooldown) in `powerRail.js`, minimal and ORRERY-consistent.',
      'Pin that the beat fires once per profile and never during combat.',
    ],
    done: '`test/fb-travel-drive-taught.test.mjs`: on seed 4242 the beat fires once on the first eligible straight and not again after save/load; the rail slot reflects the three states; existing onboarding suites stay green.',
    doNot: 'Do not add a modal. Do not fire the hint on `flight:modeChanged` after the player already found it. Do not redesign the rail (ORRERY).',
    tests: ['Locate the onboarding suites with `rg missingThree test/` and `rg onboarding test/ -l`.'],
  },
  {
    slug: 'the-pad-covers-the-whole-hand', domain: '01-hand', area: 'parity',
    title: 'A pad player can reach every bound flight verb, not two-thirds of them',
    kind: 'build', lane: 'THE HAND', routing: 'open',
    seams: ['gamepad.js', 'input.js', 'fields.js'],
    writeSet: ['src/systems/gamepad.js', 'src/systems/input.js', 'src/ui/screens/settings.js', 'test/fb-pad-covers-the-hand.test.mjs'],
    gap: '`GAMEPAD_DEFAULT_BINDINGS` carries 21 pad actions against ~30 keyboard flight verbs. `scanPulse`, `cruise`, `bulletTime`, `cloak`, `deployMassSeed`, `deployWell`, `toggleClearingCone`, `toggleSkimCollector`, `chargeThrow`, `siteBeam`, `jettisonLot`, `deployBeacon` and `autoFire` have no pad route, and `GAMEPAD_REBINDABLE` mirrors the shortfall. Half the Hand is keyboard-only.',
    why: 'A pad radial menu (modal) was rejected as the primary answer: it stops the hand. Chords on the free d-pad and stick-click space cover the verbs without a menu; a `POWER_ROSTER`-fed radial is the fallback only for the deployables. Editing `input.js` needs task ownership plus focused input/rebind/sim validation, which this packet names.',
    mechanism: [
      'Add default chords (hold LB/RB + d-pad/face) for the thirteen verbs in `GAMEPAD_DEFAULT_BINDINGS`, honouring the designed context shares checked by `findGamepadBindConflict`.',
      'Extend `GAMEPAD_REBINDABLE` so every pad action, chords included, is capturable in settings; keep the 30 s capture timeout.',
      'Pin raw-axis and action semantics unchanged for all existing pad actions (input contract).',
    ],
    done: '`test/fb-pad-covers-the-hand.test.mjs`: every id in `VERB_BINDINGS` that has a keyboard code has a pad route; conflict check passes on the default table; `pq-164-01-glyphs-remap.test.mjs` and the input lifecycle suites stay green.',
    doNot: 'Do not change any existing default pad binding. Do not add a modal radial as the only route. Do not alter `state.input.actions` semantics.',
    tests: ['`test/pq-164-01-glyphs-remap.test.mjs`', '`test/input-lifecycle.test.mjs`', '`test/pq-164-03-haptics.test.mjs`'],
  },
  {
    slug: 'aim-and-pad-response-are-tunable', domain: '01-hand', area: 'parity',
    title: 'Mouse sensitivity and invert, pad response curves and per-stick deadzones exist',
    kind: 'build', lane: 'THE HAND', routing: 'open',
    seams: ['gamepad.js', 'input.js', 'gameState.js'],
    writeSet: ['src/systems/gamepad.js', 'src/systems/input.js', 'src/core/gameState.js', 'src/ui/screens/settings.js', 'test/fb-aim-pad-response.test.mjs'],
    gap: '`applyDeadzone` is linear and one `DEFAULT_DEADZONE` (0.12) covers all four axes from one slider. There is no response curve, no outer deadzone, no per-stick deadzone and no aim-vs-fly sensitivity split (the terms curve, expo and sensitivity have zero hits in `gamepad.js` and `settings.js`). The mouse path maps `mouseNdc` to aim with no multiplier and no invert. Every modern shooter ships these.',
    why: 'Mature parity, and it fits: the settings profile already persists the whole `controls` subtree, so any key inside it survives for free. Curves are pure functions on the normalized axis.',
    mechanism: [
      'Add `+controls.gamepad.curve` (linear/expo), `+deadzoneRight`, `+sensitivityAim`, `+sensitivityFly` and `+controls.mouse.sensitivity`/`+controls.mouse.invertY` to `defaultSettings()`, consumed where axes are normalized in `gamepad.js` and where aim is derived in `input.js`.',
      'Add the rows under Controls using the existing `rowSlider`/`rowSelect` builders (functional edit, ORRERY-consistent).',
      'Pin the curve math and that raw axes reach `state.input` unchanged (the curve applies to the derived intent only).',
    ],
    done: '`test/fb-aim-pad-response.test.mjs`: expo curve monotonic, right-stick deadzone independent of left, mouse invert flips aim sign, raw axes untouched; `settings-controller-label-truth.test.mjs` and `check-settings-profile-persistence` stay green.',
    doNot: 'Do not filter raw axes. Do not change the default feel (defaults reproduce today\'s numbers). Do not edit `input.js` without the focused input validation named above.',
    tests: ['`test/settings-controller-label-truth.test.mjs`', '`test/input-lifecycle.test.mjs`', 'Run `node scripts/check-settings-profile-persistence.mjs`.'],
  },
  {
    slug: 'haptics-have-their-own-axis-and-speak-per-verb', domain: '01-hand', area: 'parity',
    title: 'Rumble has its own setting and a per-verb pulse table, no longer silenced by reduce-motion',
    kind: 'build', lane: 'THE HAND', routing: 'open',
    seams: ['gamepad.js', 'gameState.js'],
    writeSet: ['src/systems/gamepad.js', 'src/core/gameState.js', 'src/ui/screens/settings.js', 'test/fb-haptic-verbs.test.mjs'],
    gap: '`computeHapticFrame` runs four continuous channels (momentum, line, slam, boost) and one duration; it returns an all-zero frame when `reduceMotion` is set, so a vestibular preference kills rumble, which is a different axis. There is no settings row and `saveSystem.js` omits `haptics` from the default bag. No discrete pulse exists for latch, cut, release grade, snare catch, charge detonate or cloak, though every one of those events fires.',
    why: 'Coupling rumble to motion reduction is wrong: a reduce-motion player often wants more haptic substitution. An event→{strong, weak, ms} table next to the existing constants reuses the same `bus.on` sites.',
    mechanism: [
      'Add `+accessibility.haptics` (off/low/full) to `defaultSettings()` and a Controls row; stop reading `reduceMotion` in `computeHapticFrame`.',
      'Add a discrete pulse table for `tether:latched`, `tether:cut`, `tether:releaseRated` (by band), `massline:snareCaught`, `charge:detonated`, `cloak:engaged`, applied through the existing `_applyHaptics` path with the one-shot reset.',
      'Pin that low halves both motors and off produces a zero frame with no `playEffect` call.',
    ],
    done: '`test/fb-haptic-verbs.test.mjs`: six events produce six distinct pulses, reduce-motion alone no longer zeroes the frame, `pq-164-03-haptics.test.mjs` stays green.',
    doNot: 'Do not pulse on NPC events. Do not exceed one pulse per 80 ms. Do not persist haptics inside a save (profile only).',
    tests: ['`test/pq-164-03-haptics.test.mjs`', '`test/accessibility-settings-parity.test.mjs`'],
  },
  {
    slug: 'hitchhiking-is-a-verb-with-a-chip', domain: '01-hand', area: 'hands',
    title: 'Riding a faster anchor is a named state with a chip, a grade and a hint keyed on the ride',
    kind: 'deepening', lane: 'THE HAND', routing: 'open',
    seams: ['masslineHud.js', 'tetherGameplay.js', 'onboarding.js'],
    writeSet: ['src/ui/masslineHud.js', 'src/systems/tetherGameplay.js', 'src/systems/onboarding.js', 'test/fb-hitchhike-ride-chip.test.mjs'],
    gap: 'Hitchhiking is a traffic flag that adds express liners plus one post-hoc hint on `tether:latched`. There is no ride state, no tow readout and no exit grade. `resolveMassInterpretation` in `masslineHud.js` already returns `likely-anchor`, and `masslineTelemetry` already tracks tangential speed since latch.',
    why: 'A hitchhike mission was rejected (content is not a verb). The state is derivable: taut line, anchor faster than the player. Naming it and grading the exit makes the existing liners a toy.',
    mechanism: [
      'Derive a `ride` state in `tetherGameplay.js` when the line is taut and the anchor\'s speed exceeds the player\'s by a margin for 0.5 s; publish it on the player\'s tether status.',
      'Show a RIDE chip in `masslineHud.js` with the speed gained, and grade the release (kept speed / anchor speed) through the existing release rating path.',
      'Key the onboarding hint on the first ride, not on any latch.',
    ],
    done: '`test/fb-hitchhike-ride-chip.test.mjs`: on seed 4242 a latch to a liner enters `ride` within 0.5 s of taut, a release at speed grades, and the hint fires once; `massline-express-liner-runtime.test.mjs` stays green.',
    doNot: 'Do not add drag or a speed cap on release. Do not spawn extra liners. Do not fire the hint on a stationary latch.',
    tests: ['`test/massline-express-liner-runtime.test.mjs`', '`test/pq048-passenger-liner-service.test.mjs`'],
  },
  {
    slug: 'draw-to-fly-shows-its-ink-and-grades-the-stroke', domain: '01-hand', area: 'hands',
    title: 'The drawn path is visible while it is flown and the stroke is graded when it ends',
    kind: 'deepening', lane: 'THE HAND', routing: 'open',
    seams: ['drawFlightInput.js', 'drawFlightControl.js', 'masslineHud.js'],
    writeSet: ['src/systems/drawFlightInput.js', 'src/core/flight/drawFlightControl.js', 'src/ui/masslineHud.js', 'test/fb-draw-to-fly-ink.test.mjs'],
    gap: '`emptyDrawFlightPath` keeps up to 256 stroke points and `drawFlightAcceleration` flies them, but no HUD surface reads `state.input.drawFlightPath` and no grade is given. The player draws blind and learns nothing from the result.',
    why: 'A separate draw HUD was rejected; the massline HUD already paints world-anchored lines and previews. The grade is a cross-track error the follower already computes implicitly.',
    mechanism: [
      'Accumulate cross-track error and time-on-path in `drawFlightControl.js` while a stroke is being flown; publish a completed-stroke record with distance, peak speed and error band (razor/clean/good/rough) using the same band names as release rating.',
      'Paint the live stroke and the flown trace in `masslineHud.js` from `state.input.drawFlightPath`; fade the ink over 2 s after completion.',
      'Feed the band into the stunt callout so a razor stroke is named like a razor release (see @stunts-are-named-in-adventure).',
    ],
    done: '`test/fb-draw-to-fly-ink.test.mjs`: a scripted 12-point stroke on seed 4242 yields a deterministic error band and the path buffer never exceeds 256 points; the HUD paints it (record from the HUD model, not a still).',
    doNot: 'Do not change the follower\'s acceleration law. Do not add snapping to the drawn path. Do not add a draw tutorial screen.',
    tests: ['Locate the draw-flight suites with `rg drawFlight test/` and name what you verified.'],
  },
  {
    slug: 'earned-speed-shows-past-the-gauge', domain: '01-hand', area: 'hands',
    title: 'The speed gauge shows overspeed the kernel deliberately preserves',
    kind: 'polish', lane: 'THE INSTRUMENT', routing: 'ORRERY lane',
    seams: ['hud.js', 'propulsionCatalog.js'],
    writeSet: ['src/ui/hud.js', 'test/fb-overspeed-band.test.mjs'],
    gap: 'The speed gauge in `hud.js` clamps to `p.maxSpeed` (100%), so the earned momentum the propulsion kernel keeps above the governed combat speed (`OVERCAP_ASSIST_BLEND_WU_S`) is invisible exactly when it was earned. `resolveGovernedCombatSpeed` gives the reference number. Pure gauge work, hence the ORRERY lane.',
    why: 'The sim half is done; the instrument lies by omission.',
    mechanism: [
      'Paint an overspeed band on the gauge from |vel| − governed speed, in a second colour, without moving the 100% mark.',
      'Keep the 10 Hz numeric cadence the HUD already uses; no per-frame allocation.',
    ],
    done: '`test/fb-overspeed-band.test.mjs`: a seed-4242 slingshot release that exits above governed speed produces a non-zero band value in the HUD model and zero once speed decays below it.',
    doNot: 'Do not clamp or "settle" the number. Do not add a second gauge.',
    tests: ['Locate the HUD gauge suites with `rg setKitGauge test/` (the gauge helper) and name what you verified.'],
  },
  // ───────────────────────────── 02-massline ─────────────────────────────
  {
    slug: 'massline-receipts-reach-the-picture', domain: '02-massline', area: 'hands',
    title: 'Thirteen receipts from the signature verb reach the picture and the pad',
    kind: 'wire', lane: 'THE HAND', routing: 'open',
    seams: ['actionEventRecipes.js', 'tetherGameplay.js', 'gamepad.js'],
    writeSet: ['src/render/vfx/actionEventRecipes.js', 'src/systems/tetherGameplay.js', 'src/systems/gamepad.js', 'test/fb-massline-receipts-vfx.test.mjs'],
    gap: 'Emit-only from `tetherGameplay.js` and its neighbours: `massline:bridleLinked`, `massline:bridleCut`, `massline:bridleEnded`, `massline:bridleEndpointSelected`, `massline:bridleSetupEnded`, `massline:cadenceChanged`, `massline:npcCounterplay`, `massline:npcLineCut`, `massline:playerLineCut`, `chain:tetherShare`, `tether:whipSnap`, `tether:rebound`, `web:linked`. The strict pass confirms no other src file mentions them. The signature verb\'s own consequences are invisible.',
    why: 'New VFX systems were rejected; `ADDITIONAL_ACTION_VFX_RECIPES` is auto-subscribed by `vfx.js` and each row is one line naming a verb and a primitive. Denials are handled by @refusal-has-a-voice-and-a-shape; this packet covers the affirmative receipts.',
    mechanism: [
      'Add one recipe row per event with the verb it already is (link, cut, end, share, snap, rebound): bridle link draws the shared filament, a line cut by an NPC flashes the cut point with the cutter\'s colour, the web link runs a bead along the new strand.',
      'Add haptic pulses for the cut-by-NPC and whip-snap edges through the table from @haptics-have-their-own-axis-and-speak-per-verb.',
      'Pin that a scripted bridle setup→link→cut sequence produces exactly one record per edge.',
    ],
    done: '`test/fb-massline-receipts-vfx.test.mjs`: 13 events, 13 recipe rows, one record each on a seed-4242 script; no recipe fires for an event that did not occur; `wave-c5-verb-cues.test.mjs` stays green.',
    doNot: 'Do not add particles to a clean release (the release grammar is particle-silent by acceptance). Do not change the bridle or web physics.',
    tests: ['`test/wave-c5-verb-cues.test.mjs`', 'Locate `twin_bridle` suites with `rg bridle test/`.'],
  },
  {
    slug: 'the-snare-and-the-seed-speak', domain: '02-massline', area: 'hands',
    title: 'The transverse snare and the mass seed have voices for arming, catching, warning and collapse',
    kind: 'build', lane: 'THE EAR', routing: 'open',
    seams: ['audioRecipes.js', 'audioSystem.js', 'masslineSnares.js', 'massSeed.js'],
    writeSet: ['src/data/audioRecipes.js', 'src/audio/audioSystem.js', 'src/render/vfx/actionEventRecipes.js', 'test/fb-snare-seed-voices.test.mjs'],
    gap: '`massline:snareArmed`, `massline:snareDeployed`, `massline:snareCut`, `massline:snareEnded` and `massSeed:deployed`, `massSeed:locking`, `massSeed:locked`, `massSeed:warning`, `massSeed:collapsing`, `massSeed:collapsed`, `massSeed:tetherCut`, `massSeed:cleared` are all emit-only. `RECIPES` has no snare or seed ids. The HUD polls their state (`massSeedHud.js`, `masslineHud.js`), so they have an eye and no ear.',
    why: 'Two deployables with ten silent edges; the fix is recipe authoring on the existing synth voices, not assets. The seed\'s warning-then-collapse is the one that matters most: it is a timer the player is standing on.',
    mechanism: [
      'Author synth recipes in `RECIPES`: a snare arm tick, a snare catch is already covered (`massline:snareCaught` has VFX), a snare cut twang variant, a seed lock chord (locking→locked rising), a seed warning pulse that quickens, and a collapse drop.',
      'Route the ten events in `audioSystem.js` and add the arm and collapse VFX rows to `actionEventRecipes.js`.',
      'Pin one recipe per edge and silence when the deployable is gone.',
    ],
    done: '`test/fb-snare-seed-voices.test.mjs`: on seed 4242 deploy a seed, latch, wait to warning, let it collapse: four recipes in order, silence after; snare arm/cut produce two; `mass-seed-adversarial.test.mjs` stays green.',
    doNot: 'Do not add samples. Do not add a UI countdown (the seed HUD exists). Do not change seed timing.',
    tests: ['`test/mass-seed-adversarial.test.mjs`', 'Locate snare suites with `rg masslineSnare test/`.'],
  },
  {
    slug: 'the-massline-instrument-reads-load-and-apex', domain: '02-massline', area: 'hands',
    title: 'The cadence readout shows load, stored swing energy, apex proximity and the arc exit numbers',
    kind: 'polish', lane: 'THE INSTRUMENT', routing: 'ORRERY lane',
    seams: ['masslineCadenceReadout.js', 'masslineTelemetry.js'],
    writeSet: ['src/ui/masslineCadenceReadout.js', 'test/fb-massline-readout-columns.test.mjs'],
    gap: '`masslineTelemetry.js` computes `maxStrainSinceLatch`, `maxTangentialSpeedSinceLatch`, `maxAngularSpeedSinceLatch`, `arcPreview.exitSpeed` and `arcPreview.timeToWhip` every tick and no UI or render file reads them. `computeTetherLoad` and the apex ratio (`APEX_RELEASE_OMEGA_RATIO`) run in `tetherGameplay.js`. The readout shows solution, phase and rest length only. Pure readout, hence the ORRERY lane.',
    why: 'The instrument fantasy needs the numbers that exist. No sim change.',
    mechanism: [
      'Add columns: LOAD, ENERGY (stored swing energy band), APEX (ratio to release omega), EXIT (from `arcPreview.exitSpeed`), WHIP (countdown from `timeToWhip`).',
      'Keep the quiescent fast path in `masslineHud.js` (no work with no line).',
    ],
    done: '`test/fb-massline-readout-columns.test.mjs`: the readout model exposes the five values from a seed-4242 swing and all are undefined with no line attached.',
    doNot: 'Do not compute anything new in the UI. Do not change the readout\'s mount point.',
    tests: ['`test/pq-158-02-massline-instrument.test.mjs`'],
  },
  {
    slug: 'stunts-are-named-in-adventure', domain: '02-massline', area: 'hands',
    title: 'A wrecking ball, a clothesline or a tow kill is named in adventure mode, not only in the Crucible',
    kind: 'wire', lane: 'THE HAND', routing: 'open',
    seams: ['hud.js', 'stuntCallout.js', 'stuntGrammar.js'],
    writeSet: ['src/ui/hud.js', 'src/ui/stuntCallout.js', 'test/fb-stunts-named-in-adventure.test.mjs'],
    gap: '`StuntDetector` classifies sixteen tricks, `tether:whipImpact` carries rating and momentum, `massline:releaseValidated` carries the divergence receipt, and the combo math in `stuntCombo.js` runs in adventure. But `ensureStuntCallout` is imported only by `crucible.js` and `styleMultiplier` only by `survivalHud.js`, so in the sandbox the game never names the trick. "Turn enemies into ammunition" happens silently.',
    why: 'One mount call closes the loop; the callout is already built and rate-limited. Style multipliers stay Crucible-only (adventure has rep and salvage rights instead).',
    mechanism: [
      'Mount `ensureStuntCallout` from the flight HUD path in `hud.js` when not in a run; reuse its quiet path so it costs nothing idle.',
      'Feed it from the same `stunt:trickDetected` events; suppress the Crucible-only score fields.',
      'Pin that a scripted wrecking-ball kill in adventure produces one callout with the trick name and the momentum figure.',
    ],
    done: '`test/fb-stunts-named-in-adventure.test.mjs`: one callout for a seed-4242 wrecking ball outside a run, none for an ordinary kill; `crucible-results.test.mjs` unchanged.',
    doNot: 'Do not show Crucible score in adventure. Do not add a second callout element. Do not change trick definitions.',
    tests: ['Locate stunt suites with `rg stuntRecognition test/` and `rg stuntCallout test/`.'],
  },
  {
    slug: 'every-head-announces-itself', domain: '02-massline', area: 'hands',
    title: 'The tractor, frame coupler, monofilament sweep and elastic whip heads have a status row, a first-use line and a distinct receipt',
    kind: 'deepening', lane: 'THE HAND', routing: 'open',
    seams: ['hud.js', 'hudAttention.js', 'tetherGameplay.js'],
    writeSet: ['src/ui/hud.js', 'src/ui/hudAttention.js', 'src/systems/tetherGameplay.js', 'test/fb-every-head-announces.test.mjs'],
    gap: '`masslineCounters.js` authors six heads with tell and counter; all six are granted by modules. Only `transverse_snare` and `twin_bridle` have a player-facing verb, a HUD status row (`masslineTetherStatus` in `hud.js`) and a prompt. `tractor`, `frame_coupler`, `monofilament_sweep` and `elastic_whip` are spring profiles the player fits and cannot see working.',
    why: 'New verbs per head were rejected (the sweep\'s hostile cut and the whip\'s stored energy already are verbs in the sim). What is missing is the announcement: a status row per head, one first-use line, and a receipt on the head\'s defining moment.',
    mechanism: [
      'Add head-keyed branches to `masslineTetherStatus`: tractor shows pull authority, coupler shows the rigid lock, sweep shows the cut arc armed, whip shows stored energy (from `whipStoredEnergy`).',
      'Add one `firstUseLine` per head in `hudAttention.js`, spoken on the head\'s first defining event (coupler lock, sweep cut, whip snap, tractor capture).',
      'Emit a distinct receipt on that event from `tetherGameplay.js` where none exists (the whip\'s is `tether:whipSnap`; the sweep\'s is `massline:sweepImpact`).',
    ],
    done: '`test/fb-every-head-announces.test.mjs`: fitting each of the four heads on seed 4242 yields the head\'s status row and exactly one first-use line on its defining event; `massline-invariants.test.mjs` stays green.',
    doNot: 'Do not change head physics (K values, cut arcs). Do not add a modal. Do not restyle the status row (ORRERY).',
    tests: ['`test/massline-invariants.test.mjs`', 'Locate head suites with `rg masslineHeadId test/`.'],
  },
  {
    slug: 'salvage-rights-are-heard-and-kept', domain: '02-massline', area: 'longgame',
    title: 'Salvage rights minted by a stunt are announced, claimable and recorded',
    kind: 'wire', lane: 'THE HAND', routing: 'open',
    seams: ['stuntGrammar.js', 'shipLedger.js', 'stuntCallout.js'],
    writeSet: ['src/systems/stuntGrammar.js', 'src/systems/shipLedger.js', 'src/ui/stuntCallout.js', 'test/fb-salvage-rights-heard.test.mjs'],
    gap: '`stuntGrammar.js` emits `stunt:salvageRights`, `stunt:salvageRightsClaimed`, `stunt:lineContractCompleted` and `stunt:bridge`; none has a listener (`stuntCallout.js` documents `stunt:bridge` and never subscribes). A stunt mints an economic right the player is never told about and cannot see in any ledger.',
    why: 'A rights inventory screen was rejected (no empire screen). The callout, the ship ledger and the existing loot path are the three consumers the events need.',
    mechanism: [
      'Subscribe `stuntCallout.js` to the four events: rights minted → a one-line callout naming the wreck; claimed → a confirm; bridge → the combo bridge tick.',
      'Add a ledger entry type in `shipLedgerTemplates.js`-style templates for rights minted and claimed so the record shows in the ship ledger panel.',
      'Pin that a rights mint on seed 4242 yields exactly one callout and one ledger entry, and that claiming consumes the right once.',
    ],
    done: '`test/fb-salvage-rights-heard.test.mjs` pins the callout, the ledger entry and the once-only claim; `test/pq146-02-titles-ledger-bark.test.mjs` stays green.',
    doNot: 'Do not add a rights market. Do not double-pay a claim after save/load (mirror the once-only reward boundary law from SF-278).',
    tests: ['`test/pq146-02-titles-ledger-bark.test.mjs`', 'Locate stunt-grammar suites with `rg stuntGrammar test/`.'],
  },
  {
    slug: 'deployables-survive-a-save', domain: '02-massline', area: 'professionalism',
    title: 'A deployed snare, an armed charge network and a live web survive save and load',
    kind: 'build', lane: 'THE HAND', routing: 'open',
    seams: ['saveSystem.js', 'masslineSnares.js', 'impulseCharges.js', 'tetherWebs.js'],
    writeSet: ['src/save/saveSystem.js', 'src/systems/masslineSnares.js', 'src/systems/impulseCharges.js', 'src/combat/tetherWebs.js', 'test/fb-deployables-survive-save.test.mjs'],
    gap: 'Snares and their anchors spawn as non-persistent entities and `masslineSnares.js` has no serialize; `impulseCharges.js` (sole writer of the chain-primed state) has no serialize; `tetherWebs.js` keeps its links in a closure map with a 9 s lifetime and no clear on load. A save mid-snare deletes the snare; a stuck plate network vanishes; a web can outlive its limit after a restore.',
    why: 'Making them persistent entities was rejected (the capture table is deps-first and bounded). The `_callSerialize` row pattern in `saveSystem.js` (`stunts`, `fields`) is the established answer.',
    mechanism: [
      'Add `snares` and `charges` rows to the capture plan calling `_callSerialize` on the two systems; serialize positions, arm timers and the primed chain by stable ids; restore after entities.',
      'Persist web links through the snares serialize (same owner) or clear them on `save:loaded` like `massSeed.js` does; pick persist, since a web is a player investment.',
      'Pin round-trip equality for a scripted snare + charge network + web on seed 4242, and that lifetimes continue from the saved remaining time.',
    ],
    done: '`test/fb-deployables-survive-save.test.mjs`: save/load preserves snare, anchors, three charges with a primed chain and one web with remaining lifetime; `save-envelope-fidelity.test.mjs` and `bounded-autosave.test.mjs` stay green.',
    doNot: 'Do not mark the entities persistent. Do not reset lifetimes on load. Do not grow the envelope beyond the bounded capture slice.',
    tests: ['`test/save-envelope-fidelity.test.mjs`', '`test/bounded-autosave.test.mjs`', '`test/save-restore-atomicity.test.mjs`'],
  },
];
