import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './normal-fixture.mjs';
const base='file:///workspace/scratch/d2415e46e35b/recovery-latch-20261004/normal-route-v2/';
const {resolveDockAnchor,resolveCollisionProxyManifest}=await import(base+'src/data/collisionProxyManifests.js');
const {createDockIntent}=await import(base+'src/core/dockIntent.js');
const {commitDockedUiState}=await import(base+'src/ui/dockStateCommit.js');
const {readLatchNative,readLatchApproachEvidence}=await import(base+'src/core/latchNineNative.js');
const {stepLatchPropulsion,latchPropulsionFrame}=await import(base+'src/systems/latchNinePropulsion.js');
const {isLatchActor}=await import(base+'src/data/latchNineIdentity.js');
async function ready(h){const a=resolveDockAnchor(h.station,resolveCollisionProxyManifest(h.station),h.player);h.player.pos.x=a.x;h.player.pos.z=a.z;h.player.flags.noInterp=true;for(let i=0;i<3;i++){h.owner.syncFromEntities(h.state.entityList);h.owner.step(1/60);h.state.simTime+=1/60;h.runtime.update(1/60);}assert.equal(h.state.latchNine.phase,'GUIDE');assert(readLatchApproachEvidence(h.state,h.actor()).clear);}
const dock=h=>commitDockedUiState(h.state,createDockIntent(h.state,{stationId:'station_tethys'}),h.sim.bus);
test('independent: post-observation player damage refuses clean recognition despite ordinary docking',async()=>{const h=await fixture();try{await ready(h);h.player.hull--;h.player.lastDamageT=h.state.simTime;assert(dock(h));assert.equal(h.runtime.serialize().cleanArrivals,0);}finally{h.close();}});
test('independent: native observation gap cannot reuse the previous approach certificate',async()=>{const h=await fixture();try{await ready(h);h.owner.step(1/60);h.owner.step(1/60);h.state.simTime+=2/60;h.runtime.update(1/60);assert(dock(h));assert.equal(h.runtime.serialize().cleanArrivals,0);}finally{h.close();}});
test('independent: sector removal is not death; retired native life loses all leases and budget is released',async()=>{const h=await fixture();try{const e=h.actor();h.sim.bus.emit('sector:exit',{sectorId:h.state.world.currentSectorId});assert.equal(h.runtime.serialize().destroyed,false);assert.equal(h.helpers.spawnBudget.current(),0);assert.equal(readLatchNative(e),null);assert.equal(latchPropulsionFrame(h.state,e),null);h.owner.syncFromEntities(h.state.entityList);assert.equal(h.owner.records.has(e.id),false);}finally{h.close();}});
test('independent: repeated runtime reinitialization leaves one materializer and destroys every actor/slot on close',async()=>{const h=await fixture();try{for(let i=0;i<3;i++){h.runtime.init({state:h.state,bus:h.sim.bus,helpers:h.helpers});h.owner.syncFromEntities(h.state.entityList);h.owner.step(1/60);h.runtime.update(1/60);assert.equal(h.helpers.sectorCookProviders.length,1);assert.equal(h.helpers.spawnBudget.current(),1);assert.equal(h.state.entityList.filter(e=>e.alive&&isLatchActor(e)).length,1);}h.runtime.destroy();assert.equal(h.helpers.sectorCookProviders.length,0);assert.equal(h.helpers.spawnBudget.current(),0);assert.equal(h.state.entityList.filter(e=>e.alive&&isLatchActor(e)).length,0);}finally{h.close();}});
test('independent: actual killed actor remains destroyed when the service has been disabled',async()=>{const h=await fixture();try{const e=h.actor();e.data.disabled=true;h.runtime.update(1/60);assert.equal(h.state.latchNine.phase,'OFF_DUTY');e.hull=0;e.alive=false;h.sim.bus.emit('entity:killed',{id:e.id});h.runtime.update(1/60);assert.equal(h.runtime.serialize().destroyed,true,'An actual owned tender death must survive Save/Continue even while guidance is disabled');assert.equal(h.helpers.spawnBudget.current(),0);}finally{h.close();}});
test('independent: scene de-admission removes native actor before the next physics integration',async()=>{const h=await fixture();try{const e=h.actor();h.state.render={scene:{},renderer:{}};h.runtime.update(1/60);assert.equal(e.physicsBody,false);assert.equal(e.collides,false);assert.equal(readLatchNative(e),null);h.owner.syncFromEntities(h.state.entityList);assert.equal(h.owner.records.has(e.id),false);assert.equal(latchPropulsionFrame(h.state,e),null);}finally{h.close();}});
