#!/usr/bin/env python3
"""Rebuild the embedded transient density/temperature film. No network or source art needed.

A small offline incompressible-flow bake: semi-Lagrangian velocity/density transport,
pressure projection, compact impulse injection and thermal dissipation. The runtime
samples the resulting 3D field, not an animated hash mask. Python + NumPy + SciPy.
This is cosmetic authoring, not the game's physical simulation.
"""
from pathlib import Path
import base64
import hashlib
import json
import numpy as np
from scipy.ndimage import map_coordinates, gaussian_filter

N, FRAMES, STEPS, DT = 32, 12, 108, 0.013
ROOT = Path(__file__).resolve().parents[1]

def bake():
    # Array order z,y,x agrees with Three's tightly packed 3D texture convention.
    iz, iy, ix = np.mgrid[:N, :N, :N].astype(np.float32)
    x, y, z = [(a + .5) * (2 / N) - 1 for a in (ix, iy, iz)]
    dx = 2 / N
    rho = np.zeros((N, N, N), np.float32)
    heat = np.zeros_like(rho)
    velocity = np.zeros((3, N, N, N), np.float32)
    # A short torn fuel impulse with separated lobes and a central shear cavity.
    source = np.zeros_like(rho)
    for cx, cy, cz, r, amount in [(-.25,0,0,.18,1),(-.18,.16,.08,.13,.85),
                                 (-.15,-.11,.15,.13,.9),(-.21,-.12,-.14,.13,.8),
                                 (-.20,.14,-.16,.11,.8)]:
        source += amount * np.exp(-((x-cx)**2+(y-cy)**2+(z-cz)**2)/(r*r))
    source = np.minimum(source, 1)
    boundary = np.clip((.96 - np.maximum.reduce([abs(x), abs(y), abs(z)])) / .18, 0, 1)
    film = []
    captures = set(np.linspace(8, STEPS-1, FRAMES).round().astype(int).tolist())
    for step in range(STEPS):
        # A localized impulse and swirl seed coherent shear, not render noise.
        radial2 = (y-.035*np.sin(step*.035))**2 + z*z
        ring = np.exp(-((x+.06-step*.0025)**2/.14 + radial2/.14))
        force_x = 1.9 * np.exp(-radial2/.085) * np.exp(-((x+.22)**2)/.18)
        swirl = .6 * ring
        velocity[0] += DT * (force_x + .35 * (heat - rho*.3))
        velocity[1] += DT * (-z * swirl + .09 * heat)
        velocity[2] += DT * (y * swirl)
        # Incompressible projection; zero boundary avoids atlas edge density.
        divergence = (np.gradient(velocity[0], dx, axis=2)
                    + np.gradient(velocity[1], dx, axis=1)
                    + np.gradient(velocity[2], dx, axis=0))
        pressure = np.zeros_like(rho)
        for _ in range(18):
            p = pressure
            pressure = (np.roll(p,1,0)+np.roll(p,-1,0)+np.roll(p,1,1)+np.roll(p,-1,1)
                      + np.roll(p,1,2)+np.roll(p,-1,2)-divergence*dx*dx)/6
            pressure *= boundary
        for c, axis in enumerate((2,1,0)):
            velocity[c] -= np.gradient(pressure, dx, axis=axis)
        coords = [iz-velocity[2]*DT/dx, iy-velocity[1]*DT/dx, ix-velocity[0]*DT/dx]
        velocity = np.stack([map_coordinates(v, coords, order=1, mode='constant', cval=0)
                             for v in velocity]) * boundary * .997
        rho = map_coordinates(rho, coords, order=1, mode='constant', cval=0) * .996
        heat = map_coordinates(heat, coords, order=1, mode='constant', cval=0) * .984
        if step < 14:
            injection = source * (.14 if step < 8 else .08)
            rho += injection
            heat += injection
        rho = gaussian_filter(rho, .16) * boundary
        heat = gaussian_filter(heat, .24) * boundary
        if step in captures:
            # Square-root companding preserves tenuous structure in four bits/channel.
            density = np.rint(np.sqrt(np.clip(rho/.85,0,1))*15).astype(np.uint8)
            temperature = np.rint(np.sqrt(np.clip(heat/.85,0,1))*15).astype(np.uint8)
            film.append((density << 4) | temperature)
    packed = np.stack(film).tobytes()
    # (run length,value), a synchronous, portable bounded decoder; no zlib runtime dependency.
    rle = bytearray()
    cursor = 0
    while cursor < len(packed):
        value = packed[cursor]
        end = cursor + 1
        while end < len(packed) and packed[end] == value and end-cursor < 255:
            end += 1
        rle.extend((end-cursor,value))
        cursor = end
    return packed, bytes(rle)

def main():
    packed, rle = bake()
    encoded = base64.b64encode(rle).decode()
    meta = {'grid':N,'frames':FRAMES,'channels':2,'format':'RG8','encoding':'RLE-4+4',
            'packedSha256':hashlib.sha256(packed).hexdigest(), 'rleBytes':len(rle),
            'textureBytes':len(packed)*2, 'steps':STEPS,'dt':DT}
    output = ROOT / 'src/render/combat/densityVolumeData.js'
    output.write_text('// Generated by scripts/bake-vfx-density.py. Edit the simulation, not this payload.\n'
        '// Original SpaceFace source-art bake; no third-party image or runtime dependency.\n'
        + 'export const DENSITY_FILM = Object.freeze('+json.dumps(meta,separators=(',',':'))+');\n'
        + 'const RLE =\n' + '\n'.join('  '+json.dumps(encoded[i:i+120])+' +' for i in range(0,len(encoded),120))[:-2]+';\n'
        + '''
export function decodeDensityFilm() {
  const bytes = atob(RLE);
  const voxels = DENSITY_FILM.grid ** 3 * DENSITY_FILM.frames;
  const output = new Uint8Array(voxels * 2);
  let cursor = 0;
  for (let i = 0; i < bytes.length; i += 2) {
    const count = bytes.charCodeAt(i);
    const packed = bytes.charCodeAt(i + 1);
    if (!count || !Number.isFinite(packed) || cursor + count > voxels) {
      throw new Error('Corrupt transient density film');
    }
    for (let k = 0; k < count; k++) {
      output[cursor * 2] = (packed >>> 4) * 17;
      output[cursor * 2 + 1] = (packed & 15) * 17;
      cursor++;
    }
  }
  if (cursor !== voxels) throw new Error('Incomplete transient density film');
  return output;
}
''', encoding='utf-8')
    print(json.dumps(meta,indent=2))
    print('module bytes:', output.stat().st_size)

if __name__ == '__main__':
    main()
