#!/usr/bin/env node
/** Recompute economic tables and their existing catalog projections. Zero dependencies. */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { deriveEconomyTables } from '../src/economy/economyModel.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');
const table = deriveEconomyTables();
const planned = new Map();
const read = (name) => readFile(path.join(root,name),'utf8');
function once(text, regex, replacement, label) {
  const hits = [...text.matchAll(new RegExp(regex.source, regex.flags.includes('g') ? regex.flags : regex.flags+'g'))];
  if (hits.length !== 1) throw new Error(`${label}: expected exactly one projection seam; found ${hits.length}`);
  return text.replace(regex,replacement);
}
function write(name, text) { planned.set(name,text); }
write('src/data/economyDerived.js', `// GENERATED by scripts/generate-economy.mjs. Edit src/economy/economyModel.js instead.\n// Reviewed design assumptions, NOT an empirical full-game income claim.\nimport { deepFreeze } from '../economy/economyModel.js';\nexport const ECONOMY_BALANCE = deepFreeze(${JSON.stringify(table,null,2)});\n`);

let commodities = await read('src/data/commodities.js');
for (const [id,row] of Object.entries(table.commodities)) {
  const record = new RegExp(`(\\{ id: '${id}'[^\\n]*\\})`);
  commodities = once(commodities,record,(line)=>line
    .replace(/basePrice:\s*[\d.]+/,`basePrice: ${row.basePrice}`)
    .replace(/elasticity:\s*[\d.]+/,`elasticity: ${row.elasticity}`)
    .replace(/volatility:\s*[\d.]+/,`volatility: ${row.volatility}`),id);
}
commodities=commodities.replace('// 44 cmdty_* IDs:', '// 47 cmdty_* IDs:');
write('src/data/commodities.js',commodities);
let tech = await read('src/data/tech.js');
for (const [id,row] of Object.entries(table.tech)) {
  const cost=new RegExp(`(id: '${id}'[\\s\\S]*?cost: \\{ )credits: [\\d.]+, rp: [\\d.]+( \\})`);
  tech=once(tech,cost,`$1credits: ${row.credits}, rp: ${row.rp}$2`,id);
}
tech=tech.replace('// Costs in this file stay live. Do not retune them here to fake the 15-minute\n// first-upgrade gate — that faucet work is PQ-155.01.',
  '// Credit and RP costs are generated from explicit saving-time budgets in economyModel.js.\n// Hardware acquisition remains separate; the verifier never calls an unlock a fitted upgrade.');
write('src/data/tech.js',tech);
let missions=await read('src/data/missions.js');
missions=once(missions,/  BASE: \{[\s\S]*?\n  \},/,
  `  BASE: {\n    // Generated compatibility values. economyMissionTerms is the canonical live quote.\n${Object.entries(table.mission.base).map(([k,v])=>`    ${k}: ${v},`).join('\n')}\n  },`,'MISSION_TUNING.BASE');
missions=once(missions,/  RISK_MULT: \[[^\]]*\],/,`  RISK_MULT: ${JSON.stringify(table.mission.riskMult)},`,'RISK_MULT');
missions=once(missions,/  refreshSec: \d+,/,`  refreshSec: ${table.mission.refreshS},`,'refreshSec');
// Higher-tier freight remains freight; its risk is not permanently capped at starter level.
for (const id of ['cargo_delivery','bulk_trade','mining_quota','salvage_retrieval','passenger_transport','recon_scan','tow_recovery','demolition']) {
  const r=new RegExp(`(type: '${id}', riskTierRange: )\\[\\d, \\d\\]`);
  missions=once(missions,r,'$1[0, 4]',`risk range ${id}`);
}
const mixRows=Object.entries(table.offerMix).map(([profile,w])=>{
 const order=['cargo_delivery','bulk_trade','bounty_hunt','mining_quota','salvage_retrieval','escort','patrol_clear','smuggling_run','passenger_transport','recon_scan'];
 return `  ${profile}: withPhysicalMix(${JSON.stringify(order.map(k=>w[k]))}, ${w.tow_recovery}, ${w.demolition}, ${w.rescue_under_fire}),`;
});
missions=once(missions,/export const OFFER_MIX = \{[\s\S]*?\n\};/,
  `// Generated by the station workload shares; authored-only types remain structural zero.\nexport const OFFER_MIX = {\n${mixRows.join('\n')}\n};`,'OFFER_MIX');
// Display-only formula metadata must describe the same canonical quote as the owner hook.
for(const type of Object.keys(table.offerMix.trade_hub)) {
  for(const [field,value] of [['rewardFormula','economyTerms.rewardCr'],['timeFormula','economyTerms.deadlineS']]) {
    const r=new RegExp(`(type: '${type}', riskTierRange:[^\\n]*[\\s\\S]*?${field}: )'[^']*'`);
    missions=once(missions,r,`$1'${value}'`,`${type}.${field}`);
  }
}
// The generated prefix must not grow on repeated runs.
missions=missions.replace(/(?:\/\/ Generated by the station workload shares; authored-only types remain structural zero\.\n){2,}/g,
  '// Generated by the station workload shares; authored-only types remain structural zero.\n');
write('src/data/missions.js',missions);
// The demand-profiles output carries one local additive overlay (the field-memory lane's
// depletion-scarcity profile and its gate). Keep this template byte-identical to the committed
// file so `--check` stays green across lanes; the generated table itself stays authoritative.
write('src/data/economyDemandProfiles.js', `// GENERATED by scripts/generate-economy.mjs from supply-interruption assumptions.
// Role/stock is structural; these bounded deltas describe persistent sector causes.
import { ECONOMY_BALANCE } from './economyDerived.js';
export const DEMAND_MULTIPLIER_BOUNDS = ECONOMY_BALANCE.demandBounds;
// Local additive overlay, re-applied after every regeneration (the generator template emits this
// block too): the field-memory lane's depletion-scarcity profile. A sector counts as locally
// depleted once its worked fields average past this gate. Below it the scarcity profile
// contributes nothing; above it the premium scales with how worked the belt is.
export const DEMAND_DEPLETION_GATE = 0.35;
export const ECONOMY_DEMAND_PROFILES = Object.freeze({
  ...ECONOMY_BALANCE.demandProfiles,
  // Regional scarcity: the local belts have been worked out, so raw ore and the refined/component
  // goods that depend on local feedstock price up. This is the demand-model side of field memory —
  // haulers feel a sector's depletion in its market before they ever read the field band.
  depletionScarcity: Object.freeze({
    id: 'depletion-scarcity',
    label: 'Worked-out belts',
    defaultDelta: 0,
    categoryDelta: Object.freeze({
      'raw ore': 0.16,
      crystal: 0.10,
      exotic: 0.08,
      gas: 0.05,
      refined: 0.07,
      component: 0.05,
    }),
    commodityDelta: Object.freeze({
      cmdty_fuel_cells: 0.05,
    }),
  }),
});
`);

// Check before touching ANY file. A broken seam cannot produce a half-generated tree.
const differences=[];
for (const [name,next] of planned) {
 let old; try { old=await read(name); } catch (err) { if(err.code!=='ENOENT') throw err; }
 if (old !== next) differences.push(name);
}
if (check && differences.length) {
 console.error('Economic tables differ from the model:\n'+differences.join('\n'));
 process.exitCode=1;
} else {
 if (!check) for (const [name,text] of planned) await writeFile(path.join(root,name),text);
 console.log(`${check?'Verified':'Generated'}: 47 commodity valuations, 32 tech costs, 15 mission bases, 9 offer mixes, demand and resource tables.`);
}
